// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

package events

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event                string   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Container            string   `protobuf:"bytes,5,opt,name=container,proto3" json:"container,omitempty"`
	Strategy             string   `protobuf:"bytes,6,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Command              string   `protobuf:"bytes,8,opt,name=command,proto3" json:"command,omitempty"`
	Message              string   `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	Error                bool     `protobuf:"varint,10,opt,name=error,proto3" json:"error,omitempty"`
	Payload              string   `protobuf:"bytes,11,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Event) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Event) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Event) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *Event) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Event) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *Event) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "events.Event")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor_8f22242cb04491f9) }

var fileDescriptor_8f22242cb04491f9 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x41, 0x4e, 0xc4, 0x30,
	0x0c, 0x45, 0xd5, 0xce, 0xb4, 0xd3, 0x1a, 0xc4, 0xc2, 0x62, 0x61, 0x21, 0x16, 0x15, 0xab, 0xae,
	0xd8, 0x70, 0x06, 0x2e, 0xd0, 0x1b, 0x98, 0xd6, 0x1a, 0x55, 0x22, 0x49, 0x95, 0x78, 0x90, 0xe6,
	0x24, 0x5c, 0x17, 0xc5, 0x29, 0x33, 0x3b, 0xbf, 0xf7, 0x7f, 0x64, 0xc5, 0xf0, 0x28, 0x3f, 0xe2,
	0x35, 0xbd, 0x6f, 0x31, 0x68, 0xc0, 0xb6, 0xd0, 0xdb, 0x6f, 0x0d, 0xcd, 0x67, 0x1e, 0xf1, 0x09,
	0xea, 0x75, 0xa1, 0x6a, 0xa8, 0xc6, 0x7e, 0xaa, 0xd7, 0x05, 0x9f, 0xa1, 0xb1, 0x0e, 0xd5, 0xa6,
	0x0a, 0x20, 0xc2, 0xf1, 0x92, 0x24, 0xd2, 0xc1, 0xa4, 0xcd, 0x48, 0x70, 0xe2, 0x79, 0x0e, 0x17,
	0xaf, 0x74, 0x34, 0xfd, 0x8f, 0xf8, 0x0a, 0xfd, 0x1c, 0xbc, 0xf2, 0xea, 0x25, 0x52, 0x63, 0xd9,
	0x5d, 0xe0, 0x0b, 0x74, 0x49, 0x23, 0xab, 0x9c, 0xaf, 0xd4, 0x5a, 0x78, 0xe3, 0xfc, 0x52, 0x57,
	0x27, 0x49, 0xd9, 0x6d, 0x74, 0x1a, 0xaa, 0xf1, 0x30, 0xdd, 0x45, 0xde, 0x38, 0x07, 0xe7, 0xd8,
	0x2f, 0xd4, 0x95, 0x8d, 0x3b, 0xe6, 0xc4, 0x49, 0x4a, 0x7c, 0x16, 0xea, 0x4b, 0xb2, 0xa3, 0xfd,
	0x27, 0xc6, 0x10, 0x09, 0x86, 0x6a, 0xec, 0xa6, 0x02, 0xb9, 0xbf, 0xf1, 0xf5, 0x3b, 0xf0, 0x42,
	0x0f, 0xa5, 0xbf, 0xe3, 0x57, 0x6b, 0x87, 0xfa, 0xf8, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x42,
	0x32, 0xf4, 0x38, 0x01, 0x00, 0x00,
}
