// Code generated by protoc-gen-go. DO NOT EDIT.
// source: servers.proto

package west4API

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Server struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ServerDescription    string   `protobuf:"bytes,3,opt,name=server_description,json=serverDescription,proto3" json:"server_description,omitempty"`
	Host                 string   `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Version              string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Kind                 string   `protobuf:"bytes,6,opt,name=kind,proto3" json:"kind,omitempty"`
	Enabled              bool     `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6eaaceba9c5e837, []int{0}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *Server) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Server) GetServerDescription() string {
	if m != nil {
		return m.ServerDescription
	}
	return ""
}

func (m *Server) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Server) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Server) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Server) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type ServerRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ServerId             int32    `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerRequest) Reset()         { *m = ServerRequest{} }
func (m *ServerRequest) String() string { return proto.CompactTextString(m) }
func (*ServerRequest) ProtoMessage()    {}
func (*ServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6eaaceba9c5e837, []int{1}
}

func (m *ServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerRequest.Unmarshal(m, b)
}
func (m *ServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerRequest.Marshal(b, m, deterministic)
}
func (m *ServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerRequest.Merge(m, src)
}
func (m *ServerRequest) XXX_Size() int {
	return xxx_messageInfo_ServerRequest.Size(m)
}
func (m *ServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerRequest proto.InternalMessageInfo

func (m *ServerRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ServerRequest) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

type ServerResponse struct {
	Retcode              Retcode   `protobuf:"varint,1,opt,name=retcode,proto3,enum=west4API.Retcode" json:"retcode,omitempty"`
	Server               []*Server `protobuf:"bytes,2,rep,name=server,proto3" json:"server,omitempty"`
	Comment              string    `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Elapsed              string    `protobuf:"bytes,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServerResponse) Reset()         { *m = ServerResponse{} }
func (m *ServerResponse) String() string { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()    {}
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6eaaceba9c5e837, []int{2}
}

func (m *ServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResponse.Unmarshal(m, b)
}
func (m *ServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResponse.Marshal(b, m, deterministic)
}
func (m *ServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResponse.Merge(m, src)
}
func (m *ServerResponse) XXX_Size() int {
	return xxx_messageInfo_ServerResponse.Size(m)
}
func (m *ServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResponse proto.InternalMessageInfo

func (m *ServerResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECT
}

func (m *ServerResponse) GetServer() []*Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *ServerResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ServerResponse) GetElapsed() string {
	if m != nil {
		return m.Elapsed
	}
	return ""
}

type ServerPostRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Server               *Server  `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Action               Action   `protobuf:"varint,3,opt,name=action,proto3,enum=west4API.Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerPostRequest) Reset()         { *m = ServerPostRequest{} }
func (m *ServerPostRequest) String() string { return proto.CompactTextString(m) }
func (*ServerPostRequest) ProtoMessage()    {}
func (*ServerPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6eaaceba9c5e837, []int{3}
}

func (m *ServerPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPostRequest.Unmarshal(m, b)
}
func (m *ServerPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPostRequest.Marshal(b, m, deterministic)
}
func (m *ServerPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPostRequest.Merge(m, src)
}
func (m *ServerPostRequest) XXX_Size() int {
	return xxx_messageInfo_ServerPostRequest.Size(m)
}
func (m *ServerPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPostRequest proto.InternalMessageInfo

func (m *ServerPostRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ServerPostRequest) GetServer() *Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *ServerPostRequest) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_INSERT
}

type ServerPostResponse struct {
	Retcode              Retcode  `protobuf:"varint,1,opt,name=retcode,proto3,enum=west4API.Retcode" json:"retcode,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Elapsed              string   `protobuf:"bytes,3,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerPostResponse) Reset()         { *m = ServerPostResponse{} }
func (m *ServerPostResponse) String() string { return proto.CompactTextString(m) }
func (*ServerPostResponse) ProtoMessage()    {}
func (*ServerPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6eaaceba9c5e837, []int{4}
}

func (m *ServerPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPostResponse.Unmarshal(m, b)
}
func (m *ServerPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPostResponse.Marshal(b, m, deterministic)
}
func (m *ServerPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPostResponse.Merge(m, src)
}
func (m *ServerPostResponse) XXX_Size() int {
	return xxx_messageInfo_ServerPostResponse.Size(m)
}
func (m *ServerPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPostResponse proto.InternalMessageInfo

func (m *ServerPostResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECT
}

func (m *ServerPostResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ServerPostResponse) GetElapsed() string {
	if m != nil {
		return m.Elapsed
	}
	return ""
}

func init() {
	proto.RegisterType((*Server)(nil), "west4API.Server")
	proto.RegisterType((*ServerRequest)(nil), "west4API.ServerRequest")
	proto.RegisterType((*ServerResponse)(nil), "west4API.ServerResponse")
	proto.RegisterType((*ServerPostRequest)(nil), "west4API.ServerPostRequest")
	proto.RegisterType((*ServerPostResponse)(nil), "west4API.ServerPostResponse")
}

func init() { proto.RegisterFile("servers.proto", fileDescriptor_a6eaaceba9c5e837) }

var fileDescriptor_a6eaaceba9c5e837 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0xe5, 0xb4, 0x4d, 0xdb, 0x43, 0xad, 0xa8, 0xc5, 0x60, 0xc1, 0x12, 0x65, 0x8a, 0x84,
	0xe8, 0x50, 0x78, 0x81, 0x22, 0x96, 0x6e, 0x95, 0x79, 0x00, 0x94, 0xc6, 0x27, 0x11, 0xb5, 0xb1,
	0x43, 0xec, 0xc2, 0xc4, 0x93, 0xf0, 0x3a, 0x3c, 0x18, 0xb2, 0x1d, 0xd3, 0x64, 0xa0, 0x03, 0xdb,
	0xfd, 0xf9, 0xee, 0xcb, 0xfd, 0x2e, 0x86, 0x99, 0xc6, 0xe6, 0x1d, 0x1b, 0xbd, 0xac, 0x1b, 0x65,
	0x14, 0x9d, 0x7c, 0xa0, 0x36, 0x0f, 0xeb, 0xed, 0xe6, 0x1a, 0x50, 0x1e, 0x2b, 0x5f, 0x4d, 0xbf,
	0x09, 0xc4, 0xcf, 0x4e, 0x47, 0x6f, 0x60, 0xea, 0x27, 0x5e, 0x4a, 0xc1, 0x48, 0x42, 0xb2, 0x11,
	0x9f, 0xf8, 0xc2, 0x46, 0x50, 0x0a, 0x43, 0x99, 0x57, 0xc8, 0xa2, 0x84, 0x64, 0x53, 0xee, 0x62,
	0x7a, 0x07, 0xb4, 0x1d, 0x10, 0xa8, 0x8b, 0xa6, 0xac, 0x4d, 0xa9, 0x24, 0x1b, 0x38, 0xc5, 0xc2,
	0x77, 0x9e, 0x4e, 0x0d, 0x6b, 0xf1, 0xaa, 0xb4, 0x61, 0x43, 0x6f, 0x61, 0x63, 0xca, 0x60, 0x6c,
	0x57, 0xb4, 0x73, 0x23, 0x57, 0x0e, 0xa9, 0x55, 0xef, 0x4b, 0x29, 0x58, 0xec, 0xd5, 0x36, 0xb6,
	0x6a, 0x94, 0xf9, 0xee, 0x80, 0x82, 0x8d, 0x13, 0x92, 0x4d, 0x78, 0x48, 0xd3, 0x47, 0x98, 0x79,
	0x0a, 0x8e, 0x6f, 0x47, 0xd4, 0x86, 0x5e, 0xc1, 0xc8, 0xa8, 0x3d, 0x4a, 0x07, 0x32, 0xe5, 0x3e,
	0xe9, 0x23, 0x46, 0x7d, 0xc4, 0xf4, 0x8b, 0xc0, 0x3c, 0x98, 0xe8, 0x5a, 0x49, 0x8d, 0xf4, 0x16,
	0xc6, 0x0d, 0x9a, 0x42, 0x09, 0x74, 0x3e, 0xf3, 0xd5, 0x62, 0x19, 0xae, 0xb8, 0xe4, 0xbe, 0xc1,
	0x83, 0x82, 0x66, 0x10, 0x7b, 0x2f, 0x16, 0x25, 0x83, 0xec, 0x62, 0x75, 0x79, 0xd2, 0xb6, 0xb6,
	0x6d, 0xdf, 0x72, 0x14, 0xaa, 0xaa, 0x50, 0x9a, 0xf6, 0x5a, 0x21, 0x75, 0x84, 0x87, 0xbc, 0xd6,
	0x28, 0xda, 0x33, 0x85, 0x34, 0xfd, 0x84, 0x85, 0x77, 0xd9, 0x2a, 0x6d, 0xce, 0x53, 0x76, 0x17,
	0x21, 0x67, 0x17, 0xc9, 0x20, 0xce, 0x8b, 0xdf, 0xbf, 0x36, 0xef, 0x2a, 0xd7, 0xae, 0xce, 0xdb,
	0x7e, 0x7a, 0x04, 0xda, 0xfd, 0xfc, 0x7f, 0xee, 0xd3, 0xa1, 0x8e, 0xfe, 0xa4, 0x1e, 0xf4, 0xa8,
	0x77, 0xb1, 0x7b, 0xa5, 0xf7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xc9, 0xd4, 0x49, 0xcc,
	0x02, 0x00, 0x00,
}
