// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

package heraldsquareAPI

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	EventId              int64    `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SystemEventId        string   `protobuf:"bytes,2,opt,name=system_event_id,json=systemEventId,proto3" json:"system_event_id,omitempty"`
	System               System   `protobuf:"varint,3,opt,name=system,proto3,enum=heraldsquareAPI.System" json:"system,omitempty"`
	Function             string   `protobuf:"bytes,4,opt,name=function,proto3" json:"function,omitempty"`
	UserId               int64    `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp            string   `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata             string   `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Payload              string   `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	Message              string   `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	Error                bool     `protobuf:"varint,10,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *Event) GetSystemEventId() string {
	if m != nil {
		return m.SystemEventId
	}
	return ""
}

func (m *Event) GetSystem() System {
	if m != nil {
		return m.System
	}
	return System_RESERVED
}

func (m *Event) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *Event) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Event) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Event) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *Event) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Event) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

type EventRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	EventId              int64    `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{1}
}

func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (m *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(m, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *EventRequest) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

type EventResponse struct {
	Retcode              Retcode  `protobuf:"varint,1,opt,name=retcode,proto3,enum=heraldsquareAPI.Retcode" json:"retcode,omitempty"`
	Event                []*Event `protobuf:"bytes,2,rep,name=event,proto3" json:"event,omitempty"`
	Comment              string   `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Elapsed              string   `protobuf:"bytes,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResponse) Reset()         { *m = EventResponse{} }
func (m *EventResponse) String() string { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()    {}
func (*EventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{2}
}

func (m *EventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResponse.Unmarshal(m, b)
}
func (m *EventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResponse.Marshal(b, m, deterministic)
}
func (m *EventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResponse.Merge(m, src)
}
func (m *EventResponse) XXX_Size() int {
	return xxx_messageInfo_EventResponse.Size(m)
}
func (m *EventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventResponse proto.InternalMessageInfo

func (m *EventResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECT
}

func (m *EventResponse) GetEvent() []*Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *EventResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *EventResponse) GetElapsed() string {
	if m != nil {
		return m.Elapsed
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "heraldsquareAPI.Event")
	proto.RegisterType((*EventRequest)(nil), "heraldsquareAPI.EventRequest")
	proto.RegisterType((*EventResponse)(nil), "heraldsquareAPI.EventResponse")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor_8f22242cb04491f9) }

var fileDescriptor_8f22242cb04491f9 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x4d, 0x6e, 0xdb, 0x30,
	0x10, 0x85, 0x21, 0xa9, 0xfa, 0x9b, 0xfa, 0x07, 0x20, 0x8a, 0x9a, 0x35, 0xba, 0x10, 0xbc, 0x28,
	0xb4, 0x28, 0x5c, 0x40, 0x3d, 0x40, 0xd1, 0x85, 0x17, 0xde, 0x15, 0xec, 0x01, 0x0c, 0xc6, 0x9c,
	0x24, 0x46, 0x4c, 0x51, 0x26, 0xa9, 0x00, 0x3e, 0x50, 0x6e, 0x90, 0x03, 0x06, 0x24, 0x25, 0x07,
	0x8e, 0x97, 0xdf, 0xbc, 0x37, 0x6f, 0x34, 0x23, 0xc2, 0x04, 0x9f, 0xb1, 0xb5, 0x66, 0xdd, 0x69,
	0x65, 0x15, 0x99, 0x3f, 0xa2, 0xe6, 0x47, 0x61, 0x4e, 0x3d, 0xd7, 0xf8, 0xf7, 0xdf, 0x76, 0x09,
	0xd8, 0xf6, 0x32, 0x88, 0xab, 0xd7, 0x18, 0xd2, 0x8d, 0x73, 0x93, 0x6f, 0x50, 0xf8, 0xb6, 0xdd,
	0x41, 0xd0, 0xa8, 0x8a, 0xea, 0x84, 0xe5, 0x9e, 0xb7, 0x82, 0xfc, 0x80, 0xb9, 0x39, 0x1b, 0x8b,
	0x72, 0x77, 0x71, 0xc4, 0x55, 0x54, 0x97, 0x6c, 0x1a, 0xca, 0x9b, 0xc1, 0xf7, 0x0b, 0xb2, 0x50,
	0xa0, 0x49, 0x15, 0xd5, 0xb3, 0x66, 0xb1, 0xfe, 0x30, 0x7a, 0xfd, 0xdf, 0xcb, 0x6c, 0xb0, 0x91,
	0x25, 0x14, 0xf7, 0x7d, 0xbb, 0xb7, 0x07, 0xd5, 0xd2, 0x4f, 0x3e, 0xf1, 0xc2, 0x64, 0x01, 0x79,
	0x6f, 0x50, 0xbb, 0x61, 0xa9, 0xff, 0x9c, 0xcc, 0xe1, 0x56, 0x90, 0xef, 0x50, 0xda, 0x83, 0x44,
	0x63, 0xb9, 0xec, 0x68, 0xe6, 0xbb, 0xde, 0x0b, 0x2e, 0x52, 0xa2, 0xe5, 0x82, 0x5b, 0x4e, 0xf3,
	0x10, 0x39, 0x32, 0xa1, 0x90, 0x77, 0xfc, 0x7c, 0x54, 0x5c, 0xd0, 0xc2, 0x4b, 0x23, 0x3a, 0x45,
	0xa2, 0x31, 0xfc, 0x01, 0x69, 0x19, 0x94, 0x01, 0xc9, 0x17, 0x48, 0x51, 0x6b, 0xa5, 0x29, 0x54,
	0x51, 0x5d, 0xb0, 0x00, 0xab, 0x3f, 0x30, 0xf1, 0x4b, 0x33, 0x3c, 0xf5, 0x68, 0xac, 0x73, 0x59,
	0xf5, 0x84, 0xad, 0xbf, 0x5c, 0xc9, 0x02, 0x5c, 0x9d, 0x34, 0xbe, 0x3a, 0xe9, 0xea, 0x25, 0x82,
	0xe9, 0x90, 0x60, 0x3a, 0xd5, 0x1a, 0x24, 0x0d, 0xe4, 0x1a, 0xed, 0x5e, 0x09, 0xf4, 0x21, 0xb3,
	0x86, 0xde, 0x5c, 0x8f, 0x05, 0x9d, 0x8d, 0x46, 0xf2, 0x13, 0x52, 0x1f, 0x48, 0xe3, 0x2a, 0xa9,
	0x3f, 0x37, 0x5f, 0x6f, 0x3a, 0xc2, 0x88, 0x60, 0x72, 0x4b, 0xee, 0x95, 0x94, 0xce, 0x9f, 0x84,
	0x25, 0x07, 0x74, 0x0a, 0x1e, 0x79, 0x67, 0x50, 0x0c, 0xbf, 0x61, 0xc4, 0xbb, 0xcc, 0x3f, 0x93,
	0xdf, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x04, 0x2a, 0xc5, 0x19, 0x53, 0x02, 0x00, 0x00,
}
