package deribit

// Message ...
type Message struct {
	//Time          time.Time        `json:"time,string,omitempty"`
	HiveTable     string           `json:"hivetable,omitempty"`
	Type          string           `json:"type,omitempty"`
	ProductID     string           `json:"product_id,omitempty"`
	ProductIDs    []string         `json:"product_ids,omitempty"`
	TradeID       int64            `json:"trade_id,number,omitempty"`
	OrderID       string           `json:"order_id,omitempty"`
	Sequence      int64            `json:"sequence,number,omitempty"`
	MakerOrderID  string           `json:"maker_order_id,omitempty"`
	TakerOrderID  string           `json:"taker_order_id,omitempty"`
	RemainingSize float64          `json:"remaining_size,string,omitempty"`
	NewSize       float64          `json:"new_size,string,omitempty"`
	OldSize       float64          `json:"old_size,string,omitempty"`
	Size          float64          `json:"size,string,omitempty"`
	Price         float64          `json:"price,string,omitempty"`
	Side          string           `json:"side,omitempty"`
	Reason        string           `json:"reason,omitempty"`
	OrderType     string           `json:"order_type,omitempty"`
	Funds         float64          `json:"funds,string,omitempty"`
	NewFunds      float64          `json:"new_funds,string,omitempty"`
	OldFunds      float64          `json:"old_funds,string,omitempty"`
	Message       string           `json:"message,omitempty"`
	Bids          [][]string       `json:"bids,omitempty"`
	Asks          [][]string       `json:"asks,omitempty"`
	Changes       [][]string       `json:"changes,omitempty"`
	LastSize      float64          `json:"last_size,string,omitempty"`
	BestBid       float64          `json:"best_bid,string,omitempty"`
	BestAsk       float64          `json:"best_ask,string,omitempty"`
	Channels      []MessageChannel `json:"channels,omitempty"`
	UserID        string           `json:"user_id,omitempty"`
	ProfileID     string           `json:"profile_id,omitempty"`
	Open24H       float64          `json:"open_24h,string,omitempty"`
	Volume24H     float64          `json:"volume_24h,string,omitempty"`
	Low24H        float64          `json:"low_24h,string,omitempty"`
	High24H       float64          `json:"high_24h,string,omitempty"`
	Volume30D     float64          `json:"volume_30d,string,omitempty"`
}

// Params ...
type Params struct {
	Channels []string `json:"channels"`
}

// MessageChannel ...
type MessageChannel struct {
	Jsonrpc string `json:"jsonrpc"`
	ID      int64  `json:"id"`
	Method  string `json:"method"`
	Params  Params `json:"params"`
}

// WARN[0005] {"jsonrpc":"2.0","method":"subscription","params":{"channel":"book.BTC-PERPETUAL.raw","data":{"instrument_name":"BTC-PERPETUAL","bids":[["change",5485.0,727.0]],"asks":[],"prev_change_id":8399573118,"date":1542553161096,"change_id":8399573119}}}

type AutoGenerated struct {
	Jsonrpc string `json:"jsonrpc"`
	Method  string `json:"method"`
	Params  struct {
		Channel string `json:"channel"`
		Data    struct {
			InstrumentName string          `json:"instrument_name"`
			Bids           [][]interface{} `json:"bids"`
			Asks           []interface{}   `json:"asks"`
			PrevChangeID   int64           `json:"prev_change_id"`
			Date           int64           `json:"date"`
			ChangeID       int64           `json:"change_id"`
		} `json:"data"`
	} `json:"params"`
}

// ,[7033.0,25.0],[7049.5,10.0],[7050.0,741.0],[7080.0,10.0],[7094.0,20.0],[7099.5,10.0],[7100.0,25.0],[7149.5,10.0],[7167.0,50.0],[7175.0,1.0],[7199.5,10.0],[73

// AutoGenerated2 snapshot
type AutoGenerated2 struct {
	Jsonrpc string `json:"jsonrpc"`
	Method  string `json:"method"`
	Params  struct {
		Channel string `json:"channel"`
		Data    struct {
			Instrument string      `json:"instrument"`
			ChangeID   int64       `json:"change_id"`
			Bids       [][]float64 `json:"bids"`
			Asks       [][]float64 `json:"asks"`
		} `json:"data"`
	} `json:"params"`
}
