// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountDescription   string   `protobuf:"bytes,2,opt,name=account_description,json=accountDescription,proto3" json:"account_description,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountMode          string   `protobuf:"bytes,4,opt,name=account_mode,json=accountMode,proto3" json:"account_mode,omitempty"`
	AccountType          string   `protobuf:"bytes,5,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Enabled              bool     `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Account) GetAccountDescription() string {
	if m != nil {
		return m.AccountDescription
	}
	return ""
}

func (m *Account) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Account) GetAccountMode() string {
	if m != nil {
		return m.AccountMode
	}
	return ""
}

func (m *Account) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

func (m *Account) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type AccountRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AccountId            int64    `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountMode          string   `protobuf:"bytes,3,opt,name=account_mode,json=accountMode,proto3" json:"account_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{1}
}

func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (m *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(m, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AccountRequest) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *AccountRequest) GetAccountMode() string {
	if m != nil {
		return m.AccountMode
	}
	return ""
}

type AccountResponse struct {
	Retcode              Retcode    `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Accounts             []*Account `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Comment              string     `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Elapsed              string     `protobuf:"bytes,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{2}
}

func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (m *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(m, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_DONE
}

func (m *AccountResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *AccountResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *AccountResponse) GetElapsed() string {
	if m != nil {
		return m.Elapsed
	}
	return ""
}

type AccountPostRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Account              *Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Action               Action   `protobuf:"varint,3,opt,name=action,proto3,enum=api.Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountPostRequest) Reset()         { *m = AccountPostRequest{} }
func (m *AccountPostRequest) String() string { return proto.CompactTextString(m) }
func (*AccountPostRequest) ProtoMessage()    {}
func (*AccountPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{3}
}

func (m *AccountPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPostRequest.Unmarshal(m, b)
}
func (m *AccountPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPostRequest.Marshal(b, m, deterministic)
}
func (m *AccountPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPostRequest.Merge(m, src)
}
func (m *AccountPostRequest) XXX_Size() int {
	return xxx_messageInfo_AccountPostRequest.Size(m)
}
func (m *AccountPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPostRequest proto.InternalMessageInfo

func (m *AccountPostRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AccountPostRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *AccountPostRequest) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_INSERT
}

type AccountPostResponse struct {
	Retcode              Retcode  `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Elapsed              string   `protobuf:"bytes,3,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountPostResponse) Reset()         { *m = AccountPostResponse{} }
func (m *AccountPostResponse) String() string { return proto.CompactTextString(m) }
func (*AccountPostResponse) ProtoMessage()    {}
func (*AccountPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{4}
}

func (m *AccountPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPostResponse.Unmarshal(m, b)
}
func (m *AccountPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPostResponse.Marshal(b, m, deterministic)
}
func (m *AccountPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPostResponse.Merge(m, src)
}
func (m *AccountPostResponse) XXX_Size() int {
	return xxx_messageInfo_AccountPostResponse.Size(m)
}
func (m *AccountPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPostResponse proto.InternalMessageInfo

func (m *AccountPostResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_DONE
}

func (m *AccountPostResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *AccountPostResponse) GetElapsed() string {
	if m != nil {
		return m.Elapsed
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "api.Account")
	proto.RegisterType((*AccountRequest)(nil), "api.AccountRequest")
	proto.RegisterType((*AccountResponse)(nil), "api.AccountResponse")
	proto.RegisterType((*AccountPostRequest)(nil), "api.AccountPostRequest")
	proto.RegisterType((*AccountPostResponse)(nil), "api.AccountPostResponse")
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor_e1e7723af4c007b7) }

var fileDescriptor_e1e7723af4c007b7 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xd1, 0x4a, 0xeb, 0x40,
	0x14, 0x24, 0xc9, 0x6d, 0xd2, 0x9e, 0x96, 0x5e, 0xd8, 0x5e, 0xb8, 0x8b, 0x20, 0xc4, 0x08, 0x25,
	0x4f, 0x15, 0xf4, 0x0b, 0x04, 0x5f, 0xfa, 0x20, 0xc8, 0xe2, 0xbb, 0xa4, 0xd9, 0x03, 0x06, 0x9b,
	0xdd, 0x6d, 0x76, 0x83, 0xf4, 0x4b, 0xfc, 0x2f, 0xbf, 0x48, 0xb2, 0xd9, 0xad, 0x6d, 0x44, 0xc4,
	0xc7, 0x33, 0x33, 0x99, 0x73, 0x66, 0x36, 0x30, 0x2f, 0xca, 0x52, 0xb6, 0xc2, 0xe8, 0x95, 0x6a,
	0xa4, 0x91, 0x24, 0x2a, 0x54, 0x75, 0x06, 0x28, 0xda, 0xba, 0x07, 0xb2, 0xf7, 0x00, 0x92, 0xdb,
	0x5e, 0x43, 0xce, 0x01, 0x9c, 0xfc, 0xa9, 0xe2, 0x34, 0x48, 0x83, 0x3c, 0x62, 0x13, 0x87, 0xac,
	0x39, 0xb9, 0x82, 0x85, 0xa7, 0x39, 0xea, 0xb2, 0xa9, 0x94, 0xa9, 0xa4, 0xa0, 0x61, 0x1a, 0xe4,
	0x13, 0x46, 0x1c, 0x75, 0xf7, 0xc9, 0x90, 0xff, 0x90, 0xb4, 0x1a, 0x9b, 0xce, 0x2c, 0xb2, 0x66,
	0x71, 0x37, 0xae, 0x39, 0xb9, 0x80, 0x99, 0x77, 0xaa, 0x25, 0x47, 0xfa, 0xc7, 0x5a, 0x4c, 0x1d,
	0x76, 0x2f, 0x39, 0x1e, 0x4b, 0xcc, 0x5e, 0x21, 0x1d, 0x9d, 0x48, 0x1e, 0xf7, 0x0a, 0x09, 0x85,
	0x04, 0x45, 0xb1, 0xd9, 0x22, 0xa7, 0x71, 0x1a, 0xe4, 0x63, 0xe6, 0xc7, 0xec, 0x19, 0xe6, 0x2e,
	0x13, 0xc3, 0x5d, 0x8b, 0xda, 0x90, 0x7f, 0x30, 0x32, 0xf2, 0x05, 0x85, 0x4d, 0x35, 0x61, 0xfd,
	0x30, 0x08, 0x1c, 0x0e, 0x03, 0x0f, 0xcf, 0x8c, 0xbe, 0x9c, 0x99, 0xbd, 0x05, 0xf0, 0xf7, 0xb0,
	0x4a, 0x2b, 0x29, 0x34, 0x92, 0x25, 0x24, 0x0d, 0x9a, 0xb2, 0xfb, 0xa2, 0xdb, 0x36, 0xbf, 0x9e,
	0xad, 0x0a, 0x55, 0xad, 0x58, 0x8f, 0x31, 0x4f, 0x92, 0x1c, 0xc6, 0xfe, 0x75, 0x68, 0x98, 0x46,
	0xf9, 0xd4, 0x09, 0xbd, 0xdf, 0x81, 0xed, 0x92, 0x96, 0xb2, 0xae, 0x51, 0x18, 0x77, 0x83, 0x1f,
	0x6d, 0x07, 0xdb, 0x42, 0x69, 0xe4, 0xae, 0x44, 0x3f, 0x66, 0xaf, 0x40, 0x9c, 0xd1, 0x83, 0xd4,
	0x3f, 0xf4, 0xb0, 0x84, 0xc4, 0xed, 0xb2, 0x25, 0x0c, 0x0f, 0xf1, 0x24, 0xb9, 0x84, 0xb8, 0x28,
	0xed, 0xa3, 0x47, 0x36, 0xd8, 0xd4, 0xc9, 0x3a, 0x88, 0x39, 0x2a, 0xdb, 0xc1, 0xe2, 0x64, 0xf1,
	0x2f, 0x5b, 0x39, 0xca, 0x1a, 0x7e, 0x9b, 0x35, 0x3a, 0xc9, 0xba, 0x89, 0xed, 0xbf, 0x7c, 0xf3,
	0x11, 0x00, 0x00, 0xff, 0xff, 0x24, 0x0f, 0xb6, 0x1e, 0xee, 0x02, 0x00, 0x00,
}
