// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Orders struct {
	Venue                Venue            `protobuf:"varint,1,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	OrdersType           OrderType        `protobuf:"varint,2,opt,name=orders_type,json=ordersType,proto3,enum=api.OrderType" json:"orders_type,omitempty"`
	OrdersState          OrderState       `protobuf:"varint,3,opt,name=orders_state,json=ordersState,proto3,enum=api.OrderState" json:"orders_state,omitempty"`
	TimeExpiration       int64            `protobuf:"varint,4,opt,name=time_expiration,json=timeExpiration,proto3" json:"time_expiration,omitempty"`
	TimeSetup            int64            `protobuf:"varint,5,opt,name=time_setup,json=timeSetup,proto3" json:"time_setup,omitempty"`
	OrdersTypeFilling    OrderTypeFilling `protobuf:"varint,6,opt,name=orders_type_filling,json=ordersTypeFilling,proto3,enum=api.OrderTypeFilling" json:"orders_type_filling,omitempty"`
	OrdersTypeTime       OrderTypeTime    `protobuf:"varint,7,opt,name=orders_type_time,json=ordersTypeTime,proto3,enum=api.OrderTypeTime" json:"orders_type_time,omitempty"`
	OrdersReason         Reason           `protobuf:"varint,8,opt,name=orders_reason,json=ordersReason,proto3,enum=api.Reason" json:"orders_reason,omitempty"`
	Product              Product          `protobuf:"varint,9,opt,name=product,proto3,enum=api.Product" json:"product,omitempty"`
	VenueExecutionId     string           `protobuf:"bytes,10,opt,name=venue_execution_id,json=venueExecutionId,proto3" json:"venue_execution_id,omitempty"`
	Volume               float64          `protobuf:"fixed64,11,opt,name=volume,proto3" json:"volume,omitempty"`
	Price                float64          `protobuf:"fixed64,12,opt,name=price,proto3" json:"price,omitempty"`
	Fee                  float64          `protobuf:"fixed64,13,opt,name=fee,proto3" json:"fee,omitempty"`
	Comment              string           `protobuf:"bytes,14,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Orders) Reset()         { *m = Orders{} }
func (m *Orders) String() string { return proto.CompactTextString(m) }
func (*Orders) ProtoMessage()    {}
func (*Orders) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{0}
}
func (m *Orders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orders.Unmarshal(m, b)
}
func (m *Orders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orders.Marshal(b, m, deterministic)
}
func (dst *Orders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orders.Merge(dst, src)
}
func (m *Orders) XXX_Size() int {
	return xxx_messageInfo_Orders.Size(m)
}
func (m *Orders) XXX_DiscardUnknown() {
	xxx_messageInfo_Orders.DiscardUnknown(m)
}

var xxx_messageInfo_Orders proto.InternalMessageInfo

func (m *Orders) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *Orders) GetOrdersType() OrderType {
	if m != nil {
		return m.OrdersType
	}
	return OrderType_MARKET
}

func (m *Orders) GetOrdersState() OrderState {
	if m != nil {
		return m.OrdersState
	}
	return OrderState_STARTED
}

func (m *Orders) GetTimeExpiration() int64 {
	if m != nil {
		return m.TimeExpiration
	}
	return 0
}

func (m *Orders) GetTimeSetup() int64 {
	if m != nil {
		return m.TimeSetup
	}
	return 0
}

func (m *Orders) GetOrdersTypeFilling() OrderTypeFilling {
	if m != nil {
		return m.OrdersTypeFilling
	}
	return OrderTypeFilling_FOK
}

func (m *Orders) GetOrdersTypeTime() OrderTypeTime {
	if m != nil {
		return m.OrdersTypeTime
	}
	return OrderTypeTime_GTC
}

func (m *Orders) GetOrdersReason() Reason {
	if m != nil {
		return m.OrdersReason
	}
	return Reason_ORDER_CLIENT
}

func (m *Orders) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_BTC_USD
}

func (m *Orders) GetVenueExecutionId() string {
	if m != nil {
		return m.VenueExecutionId
	}
	return ""
}

func (m *Orders) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Orders) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Orders) GetFee() float64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Orders) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type OrderRequest struct {
	Action               TradeAction      `protobuf:"varint,1,opt,name=action,proto3,enum=api.TradeAction" json:"action,omitempty"`
	Venue                Venue            `protobuf:"varint,2,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	Product              Product          `protobuf:"varint,3,opt,name=product,proto3,enum=api.Product" json:"product,omitempty"`
	Order                int64            `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	Volume               float64          `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Price                float64          `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Stoplimit            float64          `protobuf:"fixed64,7,opt,name=stoplimit,proto3" json:"stoplimit,omitempty"`
	Sl                   float64          `protobuf:"fixed64,8,opt,name=sl,proto3" json:"sl,omitempty"`
	Tp                   float64          `protobuf:"fixed64,9,opt,name=tp,proto3" json:"tp,omitempty"`
	TraillingPercent     float64          `protobuf:"fixed64,10,opt,name=trailling_percent,json=traillingPercent,proto3" json:"trailling_percent,omitempty"`
	Deviation            int64            `protobuf:"varint,11,opt,name=deviation,proto3" json:"deviation,omitempty"`
	OrderType            OrderType        `protobuf:"varint,12,opt,name=order_type,json=orderType,proto3,enum=api.OrderType" json:"order_type,omitempty"`
	OrderSide            Side             `protobuf:"varint,13,opt,name=order_side,json=orderSide,proto3,enum=api.Side" json:"order_side,omitempty"`
	OrderTypeFilling     OrderTypeFilling `protobuf:"varint,14,opt,name=order_type_filling,json=orderTypeFilling,proto3,enum=api.OrderTypeFilling" json:"order_type_filling,omitempty"`
	OrderTypeTime        OrderTypeTime    `protobuf:"varint,15,opt,name=order_type_time,json=orderTypeTime,proto3,enum=api.OrderTypeTime" json:"order_type_time,omitempty"`
	OrderReason          Reason           `protobuf:"varint,16,opt,name=order_reason,json=orderReason,proto3,enum=api.Reason" json:"order_reason,omitempty"`
	Expiration           int64            `protobuf:"varint,17,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Comment              string           `protobuf:"bytes,18,opt,name=comment,proto3" json:"comment,omitempty"`
	Position             string           `protobuf:"bytes,19,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{1}
}
func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (dst *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(dst, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetAction() TradeAction {
	if m != nil {
		return m.Action
	}
	return TradeAction_DEAL
}

func (m *OrderRequest) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *OrderRequest) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_BTC_USD
}

func (m *OrderRequest) GetOrder() int64 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *OrderRequest) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *OrderRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderRequest) GetStoplimit() float64 {
	if m != nil {
		return m.Stoplimit
	}
	return 0
}

func (m *OrderRequest) GetSl() float64 {
	if m != nil {
		return m.Sl
	}
	return 0
}

func (m *OrderRequest) GetTp() float64 {
	if m != nil {
		return m.Tp
	}
	return 0
}

func (m *OrderRequest) GetTraillingPercent() float64 {
	if m != nil {
		return m.TraillingPercent
	}
	return 0
}

func (m *OrderRequest) GetDeviation() int64 {
	if m != nil {
		return m.Deviation
	}
	return 0
}

func (m *OrderRequest) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_MARKET
}

func (m *OrderRequest) GetOrderSide() Side {
	if m != nil {
		return m.OrderSide
	}
	return Side_BUY
}

func (m *OrderRequest) GetOrderTypeFilling() OrderTypeFilling {
	if m != nil {
		return m.OrderTypeFilling
	}
	return OrderTypeFilling_FOK
}

func (m *OrderRequest) GetOrderTypeTime() OrderTypeTime {
	if m != nil {
		return m.OrderTypeTime
	}
	return OrderTypeTime_GTC
}

func (m *OrderRequest) GetOrderReason() Reason {
	if m != nil {
		return m.OrderReason
	}
	return Reason_ORDER_CLIENT
}

func (m *OrderRequest) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *OrderRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *OrderRequest) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type OrderResult struct {
	Retcode              Retcode    `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Price                float64    `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Volume               float64    `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Fee                  float64    `protobuf:"fixed64,4,opt,name=fee,proto3" json:"fee,omitempty"`
	State                OrderState `protobuf:"varint,5,opt,name=state,proto3,enum=api.OrderState" json:"state,omitempty"`
	PositionId           string     `protobuf:"bytes,6,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	BrokerExecutionId    string     `protobuf:"bytes,7,opt,name=broker_execution_id,json=brokerExecutionId,proto3" json:"broker_execution_id,omitempty"`
	Comment              string     `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OrderResult) Reset()         { *m = OrderResult{} }
func (m *OrderResult) String() string { return proto.CompactTextString(m) }
func (*OrderResult) ProtoMessage()    {}
func (*OrderResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{2}
}
func (m *OrderResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResult.Unmarshal(m, b)
}
func (m *OrderResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResult.Marshal(b, m, deterministic)
}
func (dst *OrderResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResult.Merge(dst, src)
}
func (m *OrderResult) XXX_Size() int {
	return xxx_messageInfo_OrderResult.Size(m)
}
func (m *OrderResult) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResult.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResult proto.InternalMessageInfo

func (m *OrderResult) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *OrderResult) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderResult) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *OrderResult) GetFee() float64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *OrderResult) GetState() OrderState {
	if m != nil {
		return m.State
	}
	return OrderState_STARTED
}

func (m *OrderResult) GetPositionId() string {
	if m != nil {
		return m.PositionId
	}
	return ""
}

func (m *OrderResult) GetBrokerExecutionId() string {
	if m != nil {
		return m.BrokerExecutionId
	}
	return ""
}

func (m *OrderResult) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type Position struct {
	PositionId           string    `protobuf:"bytes,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	AccountId            string    `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Venue                Venue     `protobuf:"varint,3,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	Product              Product   `protobuf:"varint,4,opt,name=product,proto3,enum=api.Product" json:"product,omitempty"`
	PriceOpen            float64   `protobuf:"fixed64,5,opt,name=price_open,json=priceOpen,proto3" json:"price_open,omitempty"`
	WeightedPrice        float64   `protobuf:"fixed64,6,opt,name=weighted_price,json=weightedPrice,proto3" json:"weighted_price,omitempty"`
	Volume               float64   `protobuf:"fixed64,7,opt,name=volume,proto3" json:"volume,omitempty"`
	PositionTime         int64     `protobuf:"varint,8,opt,name=position_time,json=positionTime,proto3" json:"position_time,omitempty"`
	PositionSide         Side      `protobuf:"varint,9,opt,name=position_side,json=positionSide,proto3,enum=api.Side" json:"position_side,omitempty"`
	PositionReason       Reason    `protobuf:"varint,10,opt,name=position_reason,json=positionReason,proto3,enum=api.Reason" json:"position_reason,omitempty"`
	Sl                   float64   `protobuf:"fixed64,11,opt,name=sl,proto3" json:"sl,omitempty"`
	Tp                   float64   `protobuf:"fixed64,12,opt,name=tp,proto3" json:"tp,omitempty"`
	Swap                 float64   `protobuf:"fixed64,13,opt,name=swap,proto3" json:"swap,omitempty"`
	TraillingPercent     float64   `protobuf:"fixed64,14,opt,name=trailling_percent,json=traillingPercent,proto3" json:"trailling_percent,omitempty"`
	Comment              string    `protobuf:"bytes,15,opt,name=comment,proto3" json:"comment,omitempty"`
	ProfitLiquid         float64   `protobuf:"fixed64,16,opt,name=profit_liquid,json=profitLiquid,proto3" json:"profit_liquid,omitempty"`
	CumulativeFees       float64   `protobuf:"fixed64,17,opt,name=cumulative_fees,json=cumulativeFees,proto3" json:"cumulative_fees,omitempty"`
	Orders               []*Orders `protobuf:"bytes,18,rep,name=Orders,proto3" json:"Orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{3}
}
func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (dst *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(dst, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetPositionId() string {
	if m != nil {
		return m.PositionId
	}
	return ""
}

func (m *Position) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Position) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *Position) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_BTC_USD
}

func (m *Position) GetPriceOpen() float64 {
	if m != nil {
		return m.PriceOpen
	}
	return 0
}

func (m *Position) GetWeightedPrice() float64 {
	if m != nil {
		return m.WeightedPrice
	}
	return 0
}

func (m *Position) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Position) GetPositionTime() int64 {
	if m != nil {
		return m.PositionTime
	}
	return 0
}

func (m *Position) GetPositionSide() Side {
	if m != nil {
		return m.PositionSide
	}
	return Side_BUY
}

func (m *Position) GetPositionReason() Reason {
	if m != nil {
		return m.PositionReason
	}
	return Reason_ORDER_CLIENT
}

func (m *Position) GetSl() float64 {
	if m != nil {
		return m.Sl
	}
	return 0
}

func (m *Position) GetTp() float64 {
	if m != nil {
		return m.Tp
	}
	return 0
}

func (m *Position) GetSwap() float64 {
	if m != nil {
		return m.Swap
	}
	return 0
}

func (m *Position) GetTraillingPercent() float64 {
	if m != nil {
		return m.TraillingPercent
	}
	return 0
}

func (m *Position) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Position) GetProfitLiquid() float64 {
	if m != nil {
		return m.ProfitLiquid
	}
	return 0
}

func (m *Position) GetCumulativeFees() float64 {
	if m != nil {
		return m.CumulativeFees
	}
	return 0
}

func (m *Position) GetOrders() []*Orders {
	if m != nil {
		return m.Orders
	}
	return nil
}

type PositionRequest struct {
	Venue                Venue    `protobuf:"varint,1,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	Product              Product  `protobuf:"varint,2,opt,name=product,proto3,enum=api.Product" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PositionRequest) Reset()         { *m = PositionRequest{} }
func (m *PositionRequest) String() string { return proto.CompactTextString(m) }
func (*PositionRequest) ProtoMessage()    {}
func (*PositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{4}
}
func (m *PositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionRequest.Unmarshal(m, b)
}
func (m *PositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionRequest.Marshal(b, m, deterministic)
}
func (dst *PositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionRequest.Merge(dst, src)
}
func (m *PositionRequest) XXX_Size() int {
	return xxx_messageInfo_PositionRequest.Size(m)
}
func (m *PositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PositionRequest proto.InternalMessageInfo

func (m *PositionRequest) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *PositionRequest) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_BTC_USD
}

type PositionsResult struct {
	Retcode              Retcode     `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Positions            []*Position `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	Comment              string      `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PositionsResult) Reset()         { *m = PositionsResult{} }
func (m *PositionsResult) String() string { return proto.CompactTextString(m) }
func (*PositionsResult) ProtoMessage()    {}
func (*PositionsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{5}
}
func (m *PositionsResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionsResult.Unmarshal(m, b)
}
func (m *PositionsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionsResult.Marshal(b, m, deterministic)
}
func (dst *PositionsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionsResult.Merge(dst, src)
}
func (m *PositionsResult) XXX_Size() int {
	return xxx_messageInfo_PositionsResult.Size(m)
}
func (m *PositionsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionsResult.DiscardUnknown(m)
}

var xxx_messageInfo_PositionsResult proto.InternalMessageInfo

func (m *PositionsResult) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *PositionsResult) GetPositions() []*Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *PositionsResult) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type AccountRequest struct {
	Venue                Venue    `protobuf:"varint,1,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{6}
}
func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (dst *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(dst, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

type AccountResult struct {
	Retcode              Retcode  `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Account              *Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Comment              string   `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountResult) Reset()         { *m = AccountResult{} }
func (m *AccountResult) String() string { return proto.CompactTextString(m) }
func (*AccountResult) ProtoMessage()    {}
func (*AccountResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{7}
}
func (m *AccountResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResult.Unmarshal(m, b)
}
func (m *AccountResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResult.Marshal(b, m, deterministic)
}
func (dst *AccountResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResult.Merge(dst, src)
}
func (m *AccountResult) XXX_Size() int {
	return xxx_messageInfo_AccountResult.Size(m)
}
func (m *AccountResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResult.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResult proto.InternalMessageInfo

func (m *AccountResult) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *AccountResult) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *AccountResult) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type ProductRequest struct {
	Venue                Venue    `protobuf:"varint,1,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	Product              Product  `protobuf:"varint,2,opt,name=product,proto3,enum=api.Product" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductRequest) Reset()         { *m = ProductRequest{} }
func (m *ProductRequest) String() string { return proto.CompactTextString(m) }
func (*ProductRequest) ProtoMessage()    {}
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{8}
}
func (m *ProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductRequest.Unmarshal(m, b)
}
func (m *ProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductRequest.Marshal(b, m, deterministic)
}
func (dst *ProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductRequest.Merge(dst, src)
}
func (m *ProductRequest) XXX_Size() int {
	return xxx_messageInfo_ProductRequest.Size(m)
}
func (m *ProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductRequest proto.InternalMessageInfo

func (m *ProductRequest) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *ProductRequest) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_BTC_USD
}

type ProductResult struct {
	Retcode              Retcode       `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	VenueProducts        *VenueProduct `protobuf:"bytes,2,opt,name=venue_products,json=venueProducts,proto3" json:"venue_products,omitempty"`
	Comment              string        `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ProductResult) Reset()         { *m = ProductResult{} }
func (m *ProductResult) String() string { return proto.CompactTextString(m) }
func (*ProductResult) ProtoMessage()    {}
func (*ProductResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{9}
}
func (m *ProductResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductResult.Unmarshal(m, b)
}
func (m *ProductResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductResult.Marshal(b, m, deterministic)
}
func (dst *ProductResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductResult.Merge(dst, src)
}
func (m *ProductResult) XXX_Size() int {
	return xxx_messageInfo_ProductResult.Size(m)
}
func (m *ProductResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProductResult proto.InternalMessageInfo

func (m *ProductResult) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *ProductResult) GetVenueProducts() *VenueProduct {
	if m != nil {
		return m.VenueProducts
	}
	return nil
}

func (m *ProductResult) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type VenueProduct struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IndividualConnection bool     `protobuf:"varint,2,opt,name=individual_connection,json=individualConnection,proto3" json:"individual_connection,omitempty"`
	MinimumOrdersSize    float64  `protobuf:"fixed64,3,opt,name=minimum_orders_size,json=minimumOrdersSize,proto3" json:"minimum_orders_size,omitempty"`
	StepSize             float64  `protobuf:"fixed64,4,opt,name=step_size,json=stepSize,proto3" json:"step_size,omitempty"`
	MakerFee             float64  `protobuf:"fixed64,5,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`
	TakerFee             float64  `protobuf:"fixed64,6,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VenueProduct) Reset()         { *m = VenueProduct{} }
func (m *VenueProduct) String() string { return proto.CompactTextString(m) }
func (*VenueProduct) ProtoMessage()    {}
func (*VenueProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{10}
}
func (m *VenueProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VenueProduct.Unmarshal(m, b)
}
func (m *VenueProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VenueProduct.Marshal(b, m, deterministic)
}
func (dst *VenueProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VenueProduct.Merge(dst, src)
}
func (m *VenueProduct) XXX_Size() int {
	return xxx_messageInfo_VenueProduct.Size(m)
}
func (m *VenueProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_VenueProduct.DiscardUnknown(m)
}

var xxx_messageInfo_VenueProduct proto.InternalMessageInfo

func (m *VenueProduct) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *VenueProduct) GetIndividualConnection() bool {
	if m != nil {
		return m.IndividualConnection
	}
	return false
}

func (m *VenueProduct) GetMinimumOrdersSize() float64 {
	if m != nil {
		return m.MinimumOrdersSize
	}
	return 0
}

func (m *VenueProduct) GetStepSize() float64 {
	if m != nil {
		return m.StepSize
	}
	return 0
}

func (m *VenueProduct) GetMakerFee() float64 {
	if m != nil {
		return m.MakerFee
	}
	return 0
}

func (m *VenueProduct) GetTakerFee() float64 {
	if m != nil {
		return m.TakerFee
	}
	return 0
}

type HistoricalTradesRequest struct {
	Venue                Venue    `protobuf:"varint,1,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	Product              Product  `protobuf:"varint,2,opt,name=product,proto3,enum=api.Product" json:"product,omitempty"`
	Begin                int64    `protobuf:"varint,3,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  int64    `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoricalTradesRequest) Reset()         { *m = HistoricalTradesRequest{} }
func (m *HistoricalTradesRequest) String() string { return proto.CompactTextString(m) }
func (*HistoricalTradesRequest) ProtoMessage()    {}
func (*HistoricalTradesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{11}
}
func (m *HistoricalTradesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoricalTradesRequest.Unmarshal(m, b)
}
func (m *HistoricalTradesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoricalTradesRequest.Marshal(b, m, deterministic)
}
func (dst *HistoricalTradesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoricalTradesRequest.Merge(dst, src)
}
func (m *HistoricalTradesRequest) XXX_Size() int {
	return xxx_messageInfo_HistoricalTradesRequest.Size(m)
}
func (m *HistoricalTradesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoricalTradesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HistoricalTradesRequest proto.InternalMessageInfo

func (m *HistoricalTradesRequest) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *HistoricalTradesRequest) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_BTC_USD
}

func (m *HistoricalTradesRequest) GetBegin() int64 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *HistoricalTradesRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type HistoricalTradesResult struct {
	Retcode              Retcode  `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Trades               *Trade   `protobuf:"bytes,2,opt,name=trades,proto3" json:"trades,omitempty"`
	Comment              string   `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoricalTradesResult) Reset()         { *m = HistoricalTradesResult{} }
func (m *HistoricalTradesResult) String() string { return proto.CompactTextString(m) }
func (*HistoricalTradesResult) ProtoMessage()    {}
func (*HistoricalTradesResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{12}
}
func (m *HistoricalTradesResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoricalTradesResult.Unmarshal(m, b)
}
func (m *HistoricalTradesResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoricalTradesResult.Marshal(b, m, deterministic)
}
func (dst *HistoricalTradesResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoricalTradesResult.Merge(dst, src)
}
func (m *HistoricalTradesResult) XXX_Size() int {
	return xxx_messageInfo_HistoricalTradesResult.Size(m)
}
func (m *HistoricalTradesResult) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoricalTradesResult.DiscardUnknown(m)
}

var xxx_messageInfo_HistoricalTradesResult proto.InternalMessageInfo

func (m *HistoricalTradesResult) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *HistoricalTradesResult) GetTrades() *Trade {
	if m != nil {
		return m.Trades
	}
	return nil
}

func (m *HistoricalTradesResult) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type User struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Accounts             []*Account `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{13}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type Account struct {
	AccountId            string                   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountType          AccountType              `protobuf:"varint,2,opt,name=account_type,json=accountType,proto3,enum=api.AccountType" json:"account_type,omitempty"`
	AccountMode          AccountMode              `protobuf:"varint,3,opt,name=account_mode,json=accountMode,proto3,enum=api.AccountMode" json:"account_mode,omitempty"`
	Balances             map[string]*VenueBalance `protobuf:"bytes,4,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Active               bool                     `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{14}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Account) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_NET
}

func (m *Account) GetAccountMode() AccountMode {
	if m != nil {
		return m.AccountMode
	}
	return AccountMode_LIVE
}

func (m *Account) GetBalances() map[string]*VenueBalance {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *Account) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type VenueBalance struct {
	Id                   Venue               `protobuf:"varint,1,opt,name=id,proto3,enum=api.Venue" json:"id,omitempty"`
	Currency             map[string]*Balance `protobuf:"bytes,2,rep,name=currency,proto3" json:"currency,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *VenueBalance) Reset()         { *m = VenueBalance{} }
func (m *VenueBalance) String() string { return proto.CompactTextString(m) }
func (*VenueBalance) ProtoMessage()    {}
func (*VenueBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{15}
}
func (m *VenueBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VenueBalance.Unmarshal(m, b)
}
func (m *VenueBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VenueBalance.Marshal(b, m, deterministic)
}
func (dst *VenueBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VenueBalance.Merge(dst, src)
}
func (m *VenueBalance) XXX_Size() int {
	return xxx_messageInfo_VenueBalance.Size(m)
}
func (m *VenueBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_VenueBalance.DiscardUnknown(m)
}

var xxx_messageInfo_VenueBalance proto.InternalMessageInfo

func (m *VenueBalance) GetId() Venue {
	if m != nil {
		return m.Id
	}
	return Venue_DARKPOOL
}

func (m *VenueBalance) GetCurrency() map[string]*Balance {
	if m != nil {
		return m.Currency
	}
	return nil
}

type Balance struct {
	Available            float64  `protobuf:"fixed64,1,opt,name=available,proto3" json:"available,omitempty"`
	Hold                 float64  `protobuf:"fixed64,2,opt,name=hold,proto3" json:"hold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{16}
}
func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (dst *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(dst, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetAvailable() float64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *Balance) GetHold() float64 {
	if m != nil {
		return m.Hold
	}
	return 0
}

// Backtesting
type Backtesting struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Venue                Venue    `protobuf:"varint,2,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	Product              Product  `protobuf:"varint,3,opt,name=product,proto3,enum=api.Product" json:"product,omitempty"`
	StartDate            int64    `protobuf:"varint,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              int64    `protobuf:"varint,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Backtesting) Reset()         { *m = Backtesting{} }
func (m *Backtesting) String() string { return proto.CompactTextString(m) }
func (*Backtesting) ProtoMessage()    {}
func (*Backtesting) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{17}
}
func (m *Backtesting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Backtesting.Unmarshal(m, b)
}
func (m *Backtesting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Backtesting.Marshal(b, m, deterministic)
}
func (dst *Backtesting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Backtesting.Merge(dst, src)
}
func (m *Backtesting) XXX_Size() int {
	return xxx_messageInfo_Backtesting.Size(m)
}
func (m *Backtesting) XXX_DiscardUnknown() {
	xxx_messageInfo_Backtesting.DiscardUnknown(m)
}

var xxx_messageInfo_Backtesting proto.InternalMessageInfo

func (m *Backtesting) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Backtesting) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *Backtesting) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_BTC_USD
}

func (m *Backtesting) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *Backtesting) GetEndDate() int64 {
	if m != nil {
		return m.EndDate
	}
	return 0
}

type BacktestingRequest struct {
	Venue                Venue    `protobuf:"varint,1,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	Product              Product  `protobuf:"varint,2,opt,name=product,proto3,enum=api.Product" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BacktestingRequest) Reset()         { *m = BacktestingRequest{} }
func (m *BacktestingRequest) String() string { return proto.CompactTextString(m) }
func (*BacktestingRequest) ProtoMessage()    {}
func (*BacktestingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{18}
}
func (m *BacktestingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BacktestingRequest.Unmarshal(m, b)
}
func (m *BacktestingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BacktestingRequest.Marshal(b, m, deterministic)
}
func (dst *BacktestingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BacktestingRequest.Merge(dst, src)
}
func (m *BacktestingRequest) XXX_Size() int {
	return xxx_messageInfo_BacktestingRequest.Size(m)
}
func (m *BacktestingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BacktestingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BacktestingRequest proto.InternalMessageInfo

func (m *BacktestingRequest) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *BacktestingRequest) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_BTC_USD
}

type BacktestingResponse struct {
	Retcode              Retcode       `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	VenueProducts        *VenueProduct `protobuf:"bytes,2,opt,name=venue_products,json=venueProducts,proto3" json:"venue_products,omitempty"`
	Comment              string        `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BacktestingResponse) Reset()         { *m = BacktestingResponse{} }
func (m *BacktestingResponse) String() string { return proto.CompactTextString(m) }
func (*BacktestingResponse) ProtoMessage()    {}
func (*BacktestingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{19}
}
func (m *BacktestingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BacktestingResponse.Unmarshal(m, b)
}
func (m *BacktestingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BacktestingResponse.Marshal(b, m, deterministic)
}
func (dst *BacktestingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BacktestingResponse.Merge(dst, src)
}
func (m *BacktestingResponse) XXX_Size() int {
	return xxx_messageInfo_BacktestingResponse.Size(m)
}
func (m *BacktestingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BacktestingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BacktestingResponse proto.InternalMessageInfo

func (m *BacktestingResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *BacktestingResponse) GetVenueProducts() *VenueProduct {
	if m != nil {
		return m.VenueProducts
	}
	return nil
}

func (m *BacktestingResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

// Market Data
type Item struct {
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{20}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Item) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ClientInitilization struct {
	ClientMode           ClientMode    `protobuf:"varint,1,opt,name=client_mode,json=clientMode,proto3,enum=api.ClientMode" json:"client_mode,omitempty"`
	Subscription         *Subscription `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	CandleGranularity    Granularity   `protobuf:"varint,3,opt,name=candle_granularity,json=candleGranularity,proto3,enum=api.Granularity" json:"candle_granularity,omitempty"`
	CandleGroupBy        CandleGroupBy `protobuf:"varint,4,opt,name=candle_group_by,json=candleGroupBy,proto3,enum=api.CandleGroupBy" json:"candle_group_by,omitempty"`
	Verbose              bool          `protobuf:"varint,5,opt,name=verbose,proto3" json:"verbose,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ClientInitilization) Reset()         { *m = ClientInitilization{} }
func (m *ClientInitilization) String() string { return proto.CompactTextString(m) }
func (*ClientInitilization) ProtoMessage()    {}
func (*ClientInitilization) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{21}
}
func (m *ClientInitilization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInitilization.Unmarshal(m, b)
}
func (m *ClientInitilization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInitilization.Marshal(b, m, deterministic)
}
func (dst *ClientInitilization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInitilization.Merge(dst, src)
}
func (m *ClientInitilization) XXX_Size() int {
	return xxx_messageInfo_ClientInitilization.Size(m)
}
func (m *ClientInitilization) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInitilization.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInitilization proto.InternalMessageInfo

func (m *ClientInitilization) GetClientMode() ClientMode {
	if m != nil {
		return m.ClientMode
	}
	return ClientMode_BACKTESTING
}

func (m *ClientInitilization) GetSubscription() *Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

func (m *ClientInitilization) GetCandleGranularity() Granularity {
	if m != nil {
		return m.CandleGranularity
	}
	return Granularity_GRANULARITY_0M
}

func (m *ClientInitilization) GetCandleGroupBy() CandleGroupBy {
	if m != nil {
		return m.CandleGroupBy
	}
	return CandleGroupBy_TIME
}

func (m *ClientInitilization) GetVerbose() bool {
	if m != nil {
		return m.Verbose
	}
	return false
}

type Subscription struct {
	Subscribe            []*SubscriptionItems `protobuf:"bytes,1,rep,name=subscribe,proto3" json:"subscribe,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{22}
}
func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (dst *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(dst, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetSubscribe() []*SubscriptionItems {
	if m != nil {
		return m.Subscribe
	}
	return nil
}

type SubscriptionItems struct {
	Venue                Venue    `protobuf:"varint,1,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	Product              Product  `protobuf:"varint,2,opt,name=product,proto3,enum=api.Product" json:"product,omitempty"`
	Orderbook            bool     `protobuf:"varint,3,opt,name=orderbook,proto3" json:"orderbook,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriptionItems) Reset()         { *m = SubscriptionItems{} }
func (m *SubscriptionItems) String() string { return proto.CompactTextString(m) }
func (*SubscriptionItems) ProtoMessage()    {}
func (*SubscriptionItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{23}
}
func (m *SubscriptionItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionItems.Unmarshal(m, b)
}
func (m *SubscriptionItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionItems.Marshal(b, m, deterministic)
}
func (dst *SubscriptionItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionItems.Merge(dst, src)
}
func (m *SubscriptionItems) XXX_Size() int {
	return xxx_messageInfo_SubscriptionItems.Size(m)
}
func (m *SubscriptionItems) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionItems.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionItems proto.InternalMessageInfo

func (m *SubscriptionItems) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *SubscriptionItems) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_BTC_USD
}

func (m *SubscriptionItems) GetOrderbook() bool {
	if m != nil {
		return m.Orderbook
	}
	return false
}

type Orderbook struct {
	Product              Product   `protobuf:"varint,1,opt,name=product,proto3,enum=api.Product" json:"product,omitempty"`
	Venue                Venue     `protobuf:"varint,2,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	Timestamp            int64     `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Levels               int32     `protobuf:"varint,4,opt,name=levels,proto3" json:"levels,omitempty"`
	Asks                 []*Item   `protobuf:"bytes,5,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids                 []*Item   `protobuf:"bytes,6,rep,name=bids,proto3" json:"bids,omitempty"`
	VenueType            VenueType `protobuf:"varint,7,opt,name=venue_type,json=venueType,proto3,enum=api.VenueType" json:"venue_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Orderbook) Reset()         { *m = Orderbook{} }
func (m *Orderbook) String() string { return proto.CompactTextString(m) }
func (*Orderbook) ProtoMessage()    {}
func (*Orderbook) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{24}
}
func (m *Orderbook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orderbook.Unmarshal(m, b)
}
func (m *Orderbook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orderbook.Marshal(b, m, deterministic)
}
func (dst *Orderbook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orderbook.Merge(dst, src)
}
func (m *Orderbook) XXX_Size() int {
	return xxx_messageInfo_Orderbook.Size(m)
}
func (m *Orderbook) XXX_DiscardUnknown() {
	xxx_messageInfo_Orderbook.DiscardUnknown(m)
}

var xxx_messageInfo_Orderbook proto.InternalMessageInfo

func (m *Orderbook) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_BTC_USD
}

func (m *Orderbook) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *Orderbook) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Orderbook) GetLevels() int32 {
	if m != nil {
		return m.Levels
	}
	return 0
}

func (m *Orderbook) GetAsks() []*Item {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *Orderbook) GetBids() []*Item {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *Orderbook) GetVenueType() VenueType {
	if m != nil {
		return m.VenueType
	}
	return VenueType_SPOT
}

type Trade struct {
	Product              Product   `protobuf:"varint,1,opt,name=product,proto3,enum=api.Product" json:"product,omitempty"`
	Venue                Venue     `protobuf:"varint,2,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	Timestamp            int64     `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Price                float64   `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Size                 float64   `protobuf:"fixed64,5,opt,name=size,proto3" json:"size,omitempty"`
	OrderSide            Side      `protobuf:"varint,6,opt,name=order_side,json=orderSide,proto3,enum=api.Side" json:"order_side,omitempty"`
	VenueType            VenueType `protobuf:"varint,7,opt,name=venue_type,json=venueType,proto3,enum=api.VenueType" json:"venue_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{25}
}
func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (dst *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(dst, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_BTC_USD
}

func (m *Trade) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *Trade) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Trade) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetSize() float64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Trade) GetOrderSide() Side {
	if m != nil {
		return m.OrderSide
	}
	return Side_BUY
}

func (m *Trade) GetVenueType() VenueType {
	if m != nil {
		return m.VenueType
	}
	return VenueType_SPOT
}

type Ticker struct {
	Product              Product   `protobuf:"varint,1,opt,name=product,proto3,enum=api.Product" json:"product,omitempty"`
	Venue                Venue     `protobuf:"varint,2,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	Timestamp            int64     `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Price                float64   `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	OrderSide            Side      `protobuf:"varint,5,opt,name=order_side,json=orderSide,proto3,enum=api.Side" json:"order_side,omitempty"`
	BestBid              float64   `protobuf:"fixed64,6,opt,name=best_bid,json=bestBid,proto3" json:"best_bid,omitempty"`
	BestAsk              float64   `protobuf:"fixed64,7,opt,name=best_ask,json=bestAsk,proto3" json:"best_ask,omitempty"`
	VenueType            VenueType `protobuf:"varint,8,opt,name=venue_type,json=venueType,proto3,enum=api.VenueType" json:"venue_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Ticker) Reset()         { *m = Ticker{} }
func (m *Ticker) String() string { return proto.CompactTextString(m) }
func (*Ticker) ProtoMessage()    {}
func (*Ticker) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{26}
}
func (m *Ticker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticker.Unmarshal(m, b)
}
func (m *Ticker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticker.Marshal(b, m, deterministic)
}
func (dst *Ticker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticker.Merge(dst, src)
}
func (m *Ticker) XXX_Size() int {
	return xxx_messageInfo_Ticker.Size(m)
}
func (m *Ticker) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticker.DiscardUnknown(m)
}

var xxx_messageInfo_Ticker proto.InternalMessageInfo

func (m *Ticker) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_BTC_USD
}

func (m *Ticker) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *Ticker) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Ticker) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Ticker) GetOrderSide() Side {
	if m != nil {
		return m.OrderSide
	}
	return Side_BUY
}

func (m *Ticker) GetBestBid() float64 {
	if m != nil {
		return m.BestBid
	}
	return 0
}

func (m *Ticker) GetBestAsk() float64 {
	if m != nil {
		return m.BestAsk
	}
	return 0
}

func (m *Ticker) GetVenueType() VenueType {
	if m != nil {
		return m.VenueType
	}
	return VenueType_SPOT
}

type Candle struct {
	Venue                Venue    `protobuf:"varint,1,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	Product              Product  `protobuf:"varint,2,opt,name=product,proto3,enum=api.Product" json:"product,omitempty"`
	Granularity          int32    `protobuf:"varint,3,opt,name=granularity,proto3" json:"granularity,omitempty"`
	Point                int32    `protobuf:"varint,4,opt,name=point,proto3" json:"point,omitempty"`
	Open                 float64  `protobuf:"fixed64,5,opt,name=open,proto3" json:"open,omitempty"`
	Close                float64  `protobuf:"fixed64,6,opt,name=close,proto3" json:"close,omitempty"`
	High                 float64  `protobuf:"fixed64,7,opt,name=high,proto3" json:"high,omitempty"`
	Low                  float64  `protobuf:"fixed64,8,opt,name=low,proto3" json:"low,omitempty"`
	Volume               float64  `protobuf:"fixed64,9,opt,name=volume,proto3" json:"volume,omitempty"`
	Total                float64  `protobuf:"fixed64,10,opt,name=total,proto3" json:"total,omitempty"`
	TotalTrades          int32    `protobuf:"varint,11,opt,name=total_trades,json=totalTrades,proto3" json:"total_trades,omitempty"`
	BuyTotal             int32    `protobuf:"varint,12,opt,name=buy_total,json=buyTotal,proto3" json:"buy_total,omitempty"`
	SellTotal            int32    `protobuf:"varint,13,opt,name=sell_total,json=sellTotal,proto3" json:"sell_total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candle) Reset()         { *m = Candle{} }
func (m *Candle) String() string { return proto.CompactTextString(m) }
func (*Candle) ProtoMessage()    {}
func (*Candle) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{27}
}
func (m *Candle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candle.Unmarshal(m, b)
}
func (m *Candle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candle.Marshal(b, m, deterministic)
}
func (dst *Candle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candle.Merge(dst, src)
}
func (m *Candle) XXX_Size() int {
	return xxx_messageInfo_Candle.Size(m)
}
func (m *Candle) XXX_DiscardUnknown() {
	xxx_messageInfo_Candle.DiscardUnknown(m)
}

var xxx_messageInfo_Candle proto.InternalMessageInfo

func (m *Candle) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *Candle) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_BTC_USD
}

func (m *Candle) GetGranularity() int32 {
	if m != nil {
		return m.Granularity
	}
	return 0
}

func (m *Candle) GetPoint() int32 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *Candle) GetOpen() float64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *Candle) GetClose() float64 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *Candle) GetHigh() float64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *Candle) GetLow() float64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *Candle) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Candle) GetTotal() float64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Candle) GetTotalTrades() int32 {
	if m != nil {
		return m.TotalTrades
	}
	return 0
}

func (m *Candle) GetBuyTotal() int32 {
	if m != nil {
		return m.BuyTotal
	}
	return 0
}

func (m *Candle) GetSellTotal() int32 {
	if m != nil {
		return m.SellTotal
	}
	return 0
}

// Events
type Event struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event                string   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Container            string   `protobuf:"bytes,5,opt,name=container,proto3" json:"container,omitempty"`
	Strategy             string   `protobuf:"bytes,6,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Command              string   `protobuf:"bytes,8,opt,name=command,proto3" json:"command,omitempty"`
	Message              string   `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	Error                bool     `protobuf:"varint,10,opt,name=error,proto3" json:"error,omitempty"`
	Payload              string   `protobuf:"bytes,11,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_036db6dff88974e4, []int{28}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Event) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Event) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Event) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *Event) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Event) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *Event) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterType((*Orders)(nil), "api.Orders")
	proto.RegisterType((*OrderRequest)(nil), "api.OrderRequest")
	proto.RegisterType((*OrderResult)(nil), "api.OrderResult")
	proto.RegisterType((*Position)(nil), "api.Position")
	proto.RegisterType((*PositionRequest)(nil), "api.PositionRequest")
	proto.RegisterType((*PositionsResult)(nil), "api.PositionsResult")
	proto.RegisterType((*AccountRequest)(nil), "api.AccountRequest")
	proto.RegisterType((*AccountResult)(nil), "api.AccountResult")
	proto.RegisterType((*ProductRequest)(nil), "api.ProductRequest")
	proto.RegisterType((*ProductResult)(nil), "api.ProductResult")
	proto.RegisterType((*VenueProduct)(nil), "api.VenueProduct")
	proto.RegisterType((*HistoricalTradesRequest)(nil), "api.HistoricalTradesRequest")
	proto.RegisterType((*HistoricalTradesResult)(nil), "api.HistoricalTradesResult")
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*Account)(nil), "api.Account")
	proto.RegisterMapType((map[string]*VenueBalance)(nil), "api.Account.BalancesEntry")
	proto.RegisterType((*VenueBalance)(nil), "api.VenueBalance")
	proto.RegisterMapType((map[string]*Balance)(nil), "api.VenueBalance.CurrencyEntry")
	proto.RegisterType((*Balance)(nil), "api.Balance")
	proto.RegisterType((*Backtesting)(nil), "api.Backtesting")
	proto.RegisterType((*BacktestingRequest)(nil), "api.BacktestingRequest")
	proto.RegisterType((*BacktestingResponse)(nil), "api.BacktestingResponse")
	proto.RegisterType((*Item)(nil), "api.Item")
	proto.RegisterType((*ClientInitilization)(nil), "api.ClientInitilization")
	proto.RegisterType((*Subscription)(nil), "api.Subscription")
	proto.RegisterType((*SubscriptionItems)(nil), "api.SubscriptionItems")
	proto.RegisterType((*Orderbook)(nil), "api.Orderbook")
	proto.RegisterType((*Trade)(nil), "api.Trade")
	proto.RegisterType((*Ticker)(nil), "api.Ticker")
	proto.RegisterType((*Candle)(nil), "api.Candle")
	proto.RegisterType((*Event)(nil), "api.Event")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	// Get all Order for a user with filter - A server-to-client streaming RPC.
	// rpc GetOrders(OrderFilter) returns (stream Order) {}
	// Order request - A simple RPC
	OrderSend(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResult, error)
	GetPositions(ctx context.Context, in *PositionRequest, opts ...grpc.CallOption) (*PositionsResult, error)
	GetAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResult, error)
	GetProductDetails(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResult, error)
	GetHistoticalTrades(ctx context.Context, in *HistoricalTradesRequest, opts ...grpc.CallOption) (API_GetHistoticalTradesClient, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) OrderSend(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResult, error) {
	out := new(OrderResult)
	err := c.cc.Invoke(ctx, "/api.API/OrderSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetPositions(ctx context.Context, in *PositionRequest, opts ...grpc.CallOption) (*PositionsResult, error) {
	out := new(PositionsResult)
	err := c.cc.Invoke(ctx, "/api.API/GetPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResult, error) {
	out := new(AccountResult)
	err := c.cc.Invoke(ctx, "/api.API/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetProductDetails(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResult, error) {
	out := new(ProductResult)
	err := c.cc.Invoke(ctx, "/api.API/GetProductDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetHistoticalTrades(ctx context.Context, in *HistoricalTradesRequest, opts ...grpc.CallOption) (API_GetHistoticalTradesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[0], "/api.API/GetHistoticalTrades", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIGetHistoticalTradesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_GetHistoticalTradesClient interface {
	Recv() (*HistoricalTradesResult, error)
	grpc.ClientStream
}

type aPIGetHistoticalTradesClient struct {
	grpc.ClientStream
}

func (x *aPIGetHistoticalTradesClient) Recv() (*HistoricalTradesResult, error) {
	m := new(HistoricalTradesResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	// Get all Order for a user with filter - A server-to-client streaming RPC.
	// rpc GetOrders(OrderFilter) returns (stream Order) {}
	// Order request - A simple RPC
	OrderSend(context.Context, *OrderRequest) (*OrderResult, error)
	GetPositions(context.Context, *PositionRequest) (*PositionsResult, error)
	GetAccount(context.Context, *AccountRequest) (*AccountResult, error)
	GetProductDetails(context.Context, *ProductRequest) (*ProductResult, error)
	GetHistoticalTrades(*HistoricalTradesRequest, API_GetHistoticalTradesServer) error
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_OrderSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).OrderSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.API/OrderSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).OrderSend(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.API/GetPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetPositions(ctx, req.(*PositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.API/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetAccount(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetProductDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetProductDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.API/GetProductDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetProductDetails(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetHistoticalTrades_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HistoricalTradesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).GetHistoticalTrades(m, &aPIGetHistoticalTradesServer{stream})
}

type API_GetHistoticalTradesServer interface {
	Send(*HistoricalTradesResult) error
	grpc.ServerStream
}

type aPIGetHistoticalTradesServer struct {
	grpc.ServerStream
}

func (x *aPIGetHistoticalTradesServer) Send(m *HistoricalTradesResult) error {
	return x.ServerStream.SendMsg(m)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderSend",
			Handler:    _API_OrderSend_Handler,
		},
		{
			MethodName: "GetPositions",
			Handler:    _API_GetPositions_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _API_GetAccount_Handler,
		},
		{
			MethodName: "GetProductDetails",
			Handler:    _API_GetProductDetails_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetHistoticalTrades",
			Handler:       _API_GetHistoticalTrades_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_036db6dff88974e4) }

var fileDescriptor_api_036db6dff88974e4 = []byte{
	// 2170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x59, 0xcd, 0x6f, 0x24, 0x47,
	0x15, 0x4f, 0xcf, 0x77, 0xbf, 0xf9, 0xb0, 0x5d, 0xde, 0x2c, 0x1d, 0xc7, 0x4b, 0x4c, 0x47, 0x49,
	0x2c, 0x85, 0x98, 0x95, 0x77, 0x81, 0x28, 0x89, 0x80, 0xfd, 0xc6, 0x12, 0xb0, 0x56, 0xd9, 0x70,
	0x00, 0x89, 0x51, 0x4f, 0x77, 0xad, 0xb7, 0xe4, 0x9e, 0xee, 0x4e, 0x57, 0xf5, 0x6c, 0x66, 0x91,
	0x10, 0x37, 0x0e, 0x9c, 0x38, 0x44, 0xfc, 0x19, 0x48, 0xb9, 0x71, 0xe1, 0xc8, 0x5f, 0x82, 0xc4,
	0x81, 0x1b, 0x27, 0x8e, 0xa8, 0x5e, 0x55, 0xf5, 0xc7, 0xd8, 0x3b, 0x1b, 0x4b, 0x16, 0xb9, 0xf5,
	0xfb, 0xbd, 0xf7, 0x6a, 0xaa, 0x5e, 0xbd, 0xdf, 0xab, 0x57, 0x35, 0xe0, 0x06, 0x19, 0x3f, 0xc8,
	0xf2, 0x54, 0xa6, 0xa4, 0x1d, 0x64, 0x7c, 0x07, 0x58, 0x52, 0xcc, 0x35, 0xe0, 0xff, 0xbd, 0x03,
	0xbd, 0xa7, 0x79, 0xc4, 0x72, 0x41, 0xf6, 0xa0, 0xbb, 0x60, 0x49, 0xc1, 0x3c, 0x67, 0xcf, 0xd9,
	0x9f, 0x1c, 0xc2, 0x81, 0x72, 0xfb, 0x95, 0x42, 0xa8, 0x56, 0x90, 0xef, 0xc1, 0x30, 0x45, 0xdb,
	0xa9, 0x5c, 0x66, 0xcc, 0x6b, 0xa1, 0xdd, 0x04, 0xed, 0x70, 0x8c, 0xd3, 0x65, 0xc6, 0x28, 0x68,
	0x13, 0xf5, 0x4d, 0x0e, 0x61, 0x64, 0x1c, 0x84, 0x0c, 0x24, 0xf3, 0xda, 0xe8, 0xb1, 0x51, 0x79,
	0x9c, 0x28, 0x98, 0x9a, 0x51, 0x51, 0x20, 0x1f, 0xc0, 0x86, 0xe4, 0x73, 0x36, 0x65, 0x5f, 0x64,
	0x3c, 0x0f, 0x24, 0x4f, 0x13, 0xaf, 0xb3, 0xe7, 0xec, 0xb7, 0xe9, 0x44, 0xc1, 0x8f, 0x4a, 0x94,
	0xdc, 0x02, 0x40, 0x43, 0xc1, 0x64, 0x91, 0x79, 0x5d, 0xb4, 0x71, 0x15, 0x72, 0xa2, 0x00, 0xf2,
	0x08, 0xb6, 0x6b, 0x93, 0x9d, 0x3e, 0xe3, 0x71, 0xcc, 0x93, 0x33, 0xaf, 0x87, 0x53, 0x78, 0xb3,
	0x39, 0xe9, 0xc7, 0x5a, 0x49, 0xb7, 0xaa, 0xb9, 0x1b, 0x88, 0x7c, 0x06, 0x9b, 0xf5, 0x61, 0xd4,
	0xf8, 0x5e, 0x1f, 0xc7, 0x20, 0xcd, 0x31, 0x4e, 0xf9, 0x9c, 0xd1, 0x49, 0x35, 0x80, 0x92, 0xc9,
	0x6d, 0x18, 0x1b, 0xef, 0x9c, 0x05, 0x22, 0x4d, 0xbc, 0x01, 0xba, 0x0e, 0xd1, 0x95, 0x22, 0x44,
	0x4d, 0x88, 0xb4, 0x44, 0xde, 0x87, 0x7e, 0x96, 0xa7, 0x51, 0x11, 0x4a, 0xcf, 0x45, 0xdb, 0x11,
	0xda, 0x1e, 0x6b, 0x8c, 0x5a, 0x25, 0xf9, 0x2e, 0x10, 0xdc, 0x94, 0x29, 0xfb, 0x82, 0x85, 0x85,
	0x0a, 0xc8, 0x94, 0x47, 0x1e, 0xec, 0x39, 0xfb, 0x2e, 0xdd, 0x44, 0xcd, 0x23, 0xab, 0x38, 0x8a,
	0xc8, 0x4d, 0xe8, 0x2d, 0xd2, 0xb8, 0x98, 0x33, 0x6f, 0xb8, 0xe7, 0xec, 0x3b, 0xd4, 0x48, 0xe4,
	0x06, 0x74, 0xb3, 0x9c, 0x87, 0xcc, 0x1b, 0x21, 0xac, 0x05, 0xb2, 0x09, 0xed, 0x67, 0x8c, 0x79,
	0x63, 0xc4, 0xd4, 0x27, 0xf1, 0xa0, 0x1f, 0xa6, 0xf3, 0x39, 0x4b, 0xa4, 0x37, 0xc1, 0x9f, 0xb0,
	0xa2, 0xff, 0xd7, 0x2e, 0x8c, 0x30, 0x06, 0x94, 0x7d, 0x5e, 0x30, 0x21, 0xc9, 0x3e, 0xf4, 0x82,
	0x10, 0xb7, 0x4d, 0xe7, 0xd1, 0x26, 0xce, 0xff, 0x34, 0x0f, 0x22, 0x76, 0x0f, 0x71, 0x6a, 0xf4,
	0x55, 0xc2, 0xb5, 0x5e, 0x95, 0x70, 0xb5, 0x60, 0xb4, 0xd7, 0x05, 0xe3, 0x06, 0x74, 0x31, 0x88,
	0x26, 0x53, 0xb4, 0x50, 0x5b, 0x74, 0xf7, 0xf2, 0x45, 0xf7, 0xea, 0x8b, 0xde, 0x05, 0x57, 0xc8,
	0x34, 0x8b, 0xf9, 0x9c, 0x4b, 0xdc, 0x61, 0x87, 0x56, 0x00, 0x99, 0x40, 0x4b, 0xc4, 0xb8, 0x7b,
	0x0e, 0x6d, 0x89, 0x58, 0xc9, 0x32, 0xc3, 0x1d, 0x72, 0x68, 0x4b, 0x66, 0xe4, 0x43, 0xd8, 0x92,
	0x79, 0xa0, 0x73, 0x66, 0x9a, 0xb1, 0x3c, 0x54, 0xa1, 0x02, 0x54, 0x6f, 0x96, 0x8a, 0x63, 0x8d,
	0xab, 0x9f, 0x8a, 0xd8, 0x82, 0xeb, 0xe4, 0x1e, 0xea, 0xc4, 0x2d, 0x01, 0xf2, 0x11, 0x68, 0x0a,
	0x69, 0x92, 0x8d, 0x2e, 0x25, 0x99, 0x9b, 0xda, 0x4f, 0xb2, 0x6f, 0xcd, 0x05, 0x8f, 0xf4, 0x9e,
	0x4d, 0x0e, 0x5d, 0x34, 0x3f, 0xe1, 0x91, 0xb5, 0x54, 0x9f, 0xe4, 0x01, 0x90, 0x6a, 0xe0, 0x92,
	0x10, 0x93, 0x75, 0x84, 0xd8, 0x4c, 0x57, 0x10, 0xf2, 0x09, 0x6c, 0xd4, 0x06, 0x41, 0x3a, 0x6c,
	0xbc, 0x92, 0x0e, 0xe3, 0xb4, 0x2e, 0x92, 0x03, 0x53, 0x0e, 0x2c, 0x19, 0x36, 0x2f, 0x92, 0x41,
	0x97, 0x02, 0xc3, 0x85, 0x6f, 0x03, 0xd4, 0xaa, 0xc0, 0x16, 0x06, 0xaa, 0x86, 0xd4, 0xb3, 0x92,
	0x34, 0xb2, 0x92, 0xec, 0xc0, 0x20, 0x4b, 0x05, 0x47, 0xbf, 0x6d, 0x54, 0x95, 0xb2, 0xff, 0xc7,
	0x16, 0x0c, 0x4d, 0xc6, 0x8a, 0x22, 0x96, 0x2a, 0xc9, 0x72, 0x26, 0xc3, 0x34, 0xb2, 0x95, 0x6f,
	0x64, 0x26, 0x84, 0x18, 0xb5, 0xca, 0x2a, 0x6d, 0x5a, 0xf5, 0xb4, 0xa9, 0x92, 0xac, 0xdd, 0x48,
	0x32, 0xc3, 0xa1, 0x4e, 0xc5, 0xa1, 0xf7, 0xa0, 0xab, 0xab, 0x60, 0xf7, 0xf2, 0x2a, 0xa8, 0xb5,
	0xe4, 0x1d, 0x18, 0xda, 0xa9, 0x2a, 0x46, 0xf7, 0x70, 0xf6, 0x60, 0xa1, 0xa3, 0x88, 0x1c, 0xc0,
	0xf6, 0x2c, 0x4f, 0xcf, 0x59, 0xde, 0xa4, 0x7e, 0x1f, 0x0d, 0xb7, 0xb4, 0xaa, 0xce, 0xfd, 0x5a,
	0x94, 0x06, 0x4d, 0xee, 0xfe, 0xbb, 0x03, 0x83, 0x63, 0x33, 0xf0, 0xea, 0xef, 0x3a, 0x17, 0x7e,
	0xf7, 0x16, 0x40, 0x10, 0x86, 0x69, 0x91, 0x48, 0xa5, 0x6f, 0xa1, 0xde, 0x35, 0xc8, 0x51, 0x54,
	0xb1, 0xb9, 0xfd, 0x35, 0xd8, 0xdc, 0x59, 0xc7, 0xe6, 0x5b, 0x00, 0x18, 0xdb, 0x69, 0x9a, 0xb1,
	0xc4, 0x70, 0xd7, 0x45, 0xe4, 0x69, 0xc6, 0x12, 0xf2, 0x1e, 0x4c, 0x5e, 0x30, 0x7e, 0xf6, 0x5c,
	0xb2, 0x68, 0x5a, 0xe7, 0xf1, 0xd8, 0xa2, 0xc7, 0x2b, 0x1b, 0xd3, 0x6f, 0x6c, 0xcc, 0xbb, 0x30,
	0x2e, 0xd7, 0x89, 0xe9, 0x3b, 0xc0, 0xbc, 0x1a, 0x59, 0xd0, 0x64, 0x6a, 0x65, 0x84, 0xbc, 0x72,
	0x57, 0x79, 0x55, 0xda, 0x23, 0xb5, 0xee, 0xc2, 0x46, 0x69, 0x6f, 0x92, 0x1b, 0x2e, 0x26, 0xf7,
	0xc4, 0xda, 0x98, 0xfc, 0xd6, 0x45, 0x65, 0xb8, 0x52, 0x54, 0x46, 0x65, 0x51, 0x21, 0xd0, 0x11,
	0x2f, 0x82, 0xcc, 0x14, 0x62, 0xfc, 0xbe, 0xbc, 0xd0, 0x4c, 0x5e, 0x51, 0x68, 0x6a, 0x5b, 0xbf,
	0xd1, 0x24, 0x88, 0x8a, 0x42, 0x9e, 0x3e, 0xe3, 0x72, 0x1a, 0xf3, 0xcf, 0x0b, 0x1e, 0x21, 0x17,
	0x1d, 0x3a, 0xd2, 0xe0, 0xcf, 0x10, 0x53, 0x47, 0x71, 0x58, 0xcc, 0x8b, 0x38, 0x90, 0x7c, 0xc1,
	0xa6, 0xcf, 0x18, 0x13, 0x48, 0x42, 0x87, 0x4e, 0x2a, 0xf8, 0x31, 0x63, 0x82, 0xbc, 0x6b, 0x9b,
	0x08, 0x8f, 0xec, 0xb5, 0xf7, 0x87, 0x66, 0xd5, 0x1a, 0xa2, 0x46, 0xe5, 0xff, 0x06, 0x36, 0x8e,
	0xcb, 0xf5, 0xeb, 0xb3, 0xe2, 0xf5, 0x2d, 0x47, 0x2d, 0x67, 0x5a, 0x6b, 0x72, 0xc6, 0xff, 0x83,
	0x53, 0x8d, 0x2e, 0xae, 0x48, 0xec, 0x0f, 0xc1, 0xb5, 0x1b, 0x23, 0xbc, 0x16, 0x2e, 0x60, 0xac,
	0x7f, 0xc5, 0x4e, 0xb7, 0xd2, 0xd7, 0x43, 0xda, 0x6e, 0xb2, 0xe9, 0x10, 0x26, 0xf7, 0x34, 0x1b,
	0xbe, 0xf6, 0xf2, 0xfc, 0x25, 0x8c, 0x4b, 0x9f, 0x2b, 0xcd, 0xf9, 0x7d, 0xe8, 0x1b, 0xea, 0x61,
	0x5c, 0x86, 0xc6, 0xce, 0x0e, 0x66, 0x95, 0x6b, 0xa6, 0xfb, 0x6b, 0x98, 0xd8, 0x28, 0x5e, 0xfb,
	0x6e, 0xfc, 0xc9, 0x81, 0x71, 0x39, 0xf8, 0x95, 0xd6, 0xf5, 0x31, 0x4c, 0x74, 0x5b, 0x63, 0x86,
	0x12, 0x66, 0x79, 0x5b, 0xd5, 0x64, 0xec, 0xc0, 0xe3, 0x45, 0x4d, 0x5a, 0xb7, 0x31, 0xff, 0x74,
	0x60, 0x54, 0xf7, 0x54, 0xa6, 0x2c, 0x09, 0x66, 0x31, 0xd3, 0x65, 0x6e, 0x40, 0xad, 0x48, 0xee,
	0xc0, 0x9b, 0x3c, 0x89, 0xf8, 0x82, 0x47, 0x45, 0x10, 0x4f, 0xc3, 0x34, 0x49, 0x98, 0xee, 0x65,
	0x5a, 0x68, 0x77, 0xa3, 0x52, 0x3e, 0x28, 0x75, 0xaa, 0x20, 0xcf, 0x79, 0xc2, 0xe7, 0xc5, 0x7c,
	0x6a, 0xbb, 0x5d, 0xfe, 0xd2, 0x9e, 0x07, 0x5b, 0x46, 0xa5, 0x49, 0x70, 0xc2, 0x5f, 0x32, 0xf2,
	0xb6, 0xea, 0x34, 0x58, 0xa6, 0xad, 0xf4, 0x01, 0x31, 0x50, 0x80, 0x55, 0xce, 0x03, 0x55, 0xdc,
	0xd5, 0xe9, 0xa1, 0x6b, 0xdf, 0x00, 0x81, 0xc7, 0x0c, 0x95, 0xb2, 0x54, 0xea, 0xaa, 0x37, 0x90,
	0x46, 0xa9, 0x82, 0xfe, 0xad, 0x9f, 0x72, 0x21, 0xd3, 0x9c, 0x87, 0x41, 0x8c, 0x0d, 0x97, 0xb8,
	0xf6, 0xad, 0x55, 0xa7, 0xe0, 0x8c, 0x9d, 0xf1, 0x04, 0x97, 0xd7, 0xa6, 0x5a, 0x50, 0xa7, 0x1d,
	0x4b, 0x22, 0xd3, 0x7e, 0xa9, 0x4f, 0xff, 0xf7, 0x70, 0xf3, 0xe2, 0x64, 0xae, 0x94, 0x0a, 0x3e,
	0xf4, 0x24, 0xfa, 0x99, 0x14, 0x80, 0xaa, 0x91, 0xa4, 0x46, 0xb3, 0x66, 0xd3, 0x7f, 0x02, 0x9d,
	0x5f, 0x0a, 0x96, 0xab, 0x9a, 0x5a, 0x9e, 0x66, 0x2d, 0x1e, 0x91, 0x7d, 0x18, 0x18, 0x6e, 0x58,
	0xae, 0x37, 0x99, 0x53, 0x6a, 0xfd, 0xaf, 0x5a, 0xd0, 0x37, 0xe8, 0xca, 0xd9, 0xe7, 0xac, 0x9e,
	0x7d, 0x77, 0x60, 0x64, 0xd5, 0xb5, 0x9b, 0xd1, 0x66, 0x7d, 0x60, 0x6c, 0xdb, 0x86, 0x41, 0x25,
	0xd4, 0x9d, 0xe6, 0x2a, 0x18, 0xed, 0x8b, 0x4e, 0x3f, 0x57, 0x01, 0xb1, 0x4e, 0x4a, 0x20, 0x3f,
	0x80, 0xc1, 0x2c, 0x88, 0x83, 0x24, 0x64, 0xc2, 0xeb, 0xe0, 0xf4, 0x77, 0xea, 0x0e, 0x07, 0xf7,
	0x8d, 0xf2, 0x51, 0x22, 0xf3, 0x25, 0x2d, 0x6d, 0xd5, 0x69, 0xa8, 0xba, 0xee, 0x85, 0xce, 0xa9,
	0x01, 0x35, 0xd2, 0xce, 0x2f, 0x60, 0xdc, 0x70, 0x51, 0x3b, 0x79, 0xce, 0x96, 0x66, 0x89, 0xea,
	0x93, 0x7c, 0x00, 0xdd, 0x45, 0x10, 0x9b, 0x36, 0xbd, 0xc1, 0x44, 0xe3, 0x49, 0xb5, 0xfe, 0x93,
	0xd6, 0xc7, 0x8e, 0xff, 0x95, 0xe5, 0x9a, 0xd1, 0x91, 0x9d, 0x32, 0xfe, 0xcd, 0xb4, 0x53, 0x7b,
	0xf1, 0x29, 0x0c, 0xc2, 0x22, 0xcf, 0x59, 0x12, 0x2e, 0xcd, 0x5e, 0xbc, 0x73, 0x61, 0xf0, 0x83,
	0x07, 0xc6, 0xc2, 0xac, 0xc8, 0x3a, 0xec, 0x1c, 0xc1, 0xb8, 0xa1, 0xba, 0x64, 0xe6, 0x7e, 0x73,
	0xe6, 0x7a, 0xa3, 0x2f, 0x99, 0xf4, 0xa7, 0xd0, 0xb7, 0xd3, 0xdd, 0x05, 0x37, 0x58, 0x04, 0x3c,
	0x56, 0xe5, 0x00, 0x87, 0x72, 0x68, 0x05, 0xa8, 0x03, 0xf9, 0x79, 0x1a, 0x47, 0xa6, 0x03, 0xc4,
	0x6f, 0xff, 0x6f, 0x0e, 0x0c, 0xef, 0x07, 0xe1, 0xb9, 0x64, 0x42, 0xaa, 0x06, 0xb9, 0x56, 0x99,
	0x9d, 0x75, 0x95, 0xf9, 0xfa, 0x6e, 0x3f, 0xb7, 0x00, 0x84, 0x0c, 0x72, 0x39, 0x8d, 0x54, 0x77,
	0xa9, 0x39, 0xe8, 0x22, 0xf2, 0x50, 0x35, 0x94, 0x6f, 0xc1, 0x80, 0x25, 0x91, 0x56, 0xea, 0x5b,
	0x72, 0x9f, 0x25, 0x91, 0x52, 0xf9, 0xbf, 0x05, 0x52, 0x9b, 0xfa, 0xf5, 0x9f, 0x03, 0x7f, 0x76,
	0x60, 0xbb, 0xf1, 0x03, 0x22, 0x4b, 0x13, 0xc1, 0xbe, 0xd1, 0xd3, 0xe0, 0x2e, 0x74, 0x8e, 0x24,
	0x9b, 0x23, 0x23, 0xe6, 0xe5, 0x36, 0x39, 0xd4, 0x48, 0x97, 0xb7, 0xf9, 0xfe, 0x97, 0x2d, 0xd8,
	0x7e, 0x10, 0x73, 0x96, 0xc8, 0xa3, 0x84, 0x4b, 0x1e, 0xf3, 0x97, 0xfa, 0x0a, 0x72, 0x1b, 0x86,
	0x21, 0xc2, 0x9a, 0xc3, 0x4e, 0xad, 0xb5, 0xd7, 0xe6, 0x48, 0x61, 0x08, 0xcb, 0x6f, 0xf2, 0x7d,
	0x18, 0x89, 0x62, 0x26, 0xc2, 0x9c, 0x67, 0xe5, 0xc9, 0x62, 0x57, 0x74, 0x52, 0x53, 0xd0, 0x86,
	0x19, 0xf9, 0x31, 0x90, 0x30, 0x48, 0xa2, 0x98, 0x4d, 0xcf, 0xf2, 0x20, 0x29, 0xe2, 0x20, 0xe7,
	0x72, 0xd9, 0xa8, 0x19, 0x4f, 0x2a, 0x9c, 0x6e, 0x69, 0xdb, 0x1a, 0xa4, 0x2e, 0x6e, 0xe5, 0x00,
	0x69, 0x91, 0x4d, 0x67, 0x4b, 0xd3, 0x85, 0xeb, 0x8b, 0xdb, 0x03, 0xe3, 0x90, 0x16, 0xd9, 0xfd,
	0x25, 0x1d, 0x87, 0x75, 0x51, 0x45, 0x73, 0xc1, 0xf2, 0x59, 0x2a, 0x6c, 0xf9, 0xb0, 0xa2, 0xff,
	0x10, 0x46, 0xf5, 0x49, 0x93, 0xbb, 0xe0, 0x9a, 0x69, 0xcf, 0x54, 0x34, 0x14, 0xa7, 0x6f, 0x5e,
	0x58, 0x9a, 0x8a, 0xbf, 0xa0, 0x95, 0xa1, 0xff, 0x3b, 0xd8, 0xba, 0xa0, 0xbf, 0xc6, 0x33, 0x6b,
	0x17, 0xf4, 0x2d, 0x78, 0x96, 0xa6, 0xe7, 0x18, 0xb2, 0x01, 0xad, 0x00, 0xff, 0xbf, 0x0e, 0xb8,
	0x4f, 0xad, 0x54, 0x1f, 0xd3, 0x59, 0x37, 0xe6, 0xeb, 0xe9, 0xbb, 0x0b, 0xf8, 0x1a, 0x25, 0x64,
	0x30, 0xcf, 0xcc, 0x69, 0x59, 0x01, 0x2a, 0xfd, 0x62, 0xb6, 0x60, 0xb1, 0xc0, 0x5d, 0xe8, 0x52,
	0x23, 0x91, 0x5b, 0xd0, 0x09, 0xc4, 0xb9, 0xf0, 0xba, 0x18, 0x3b, 0x7d, 0xe1, 0x50, 0xf1, 0xa0,
	0x08, 0x2b, 0xf5, 0x8c, 0x47, 0xc2, 0xeb, 0x5d, 0x50, 0x2b, 0x98, 0x7c, 0x04, 0xa0, 0x09, 0x83,
	0xc7, 0x50, 0xbf, 0xf6, 0x76, 0x80, 0x53, 0xd3, 0x6f, 0x07, 0x0b, 0xfb, 0xe9, 0xff, 0xc7, 0x81,
	0x2e, 0x1e, 0xa8, 0xff, 0xb7, 0x65, 0x97, 0xec, 0xea, 0xd4, 0x2f, 0xd1, 0xea, 0xa2, 0xa3, 0x9a,
	0xa1, 0xae, 0xb9, 0xe8, 0xa8, 0x46, 0xa8, 0xf9, 0xae, 0xd1, 0x5b, 0xf3, 0xae, 0x71, 0xc5, 0x45,
	0x7f, 0xd9, 0x82, 0xde, 0x29, 0x0f, 0xcf, 0x59, 0xfe, 0x0d, 0xaf, 0xba, 0xb9, 0xc2, 0xee, 0x9a,
	0x15, 0xbe, 0x05, 0x83, 0x19, 0x13, 0x72, 0x3a, 0x33, 0x0f, 0x02, 0x0e, 0xed, 0x2b, 0xf9, 0x3e,
	0x8f, 0x4a, 0x55, 0x20, 0xce, 0xcd, 0x45, 0x17, 0x55, 0xf7, 0xc4, 0xf9, 0x4a, 0x5c, 0x06, 0xaf,
	0x8b, 0xcb, 0xbf, 0x5a, 0xd0, 0xd3, 0x55, 0xe0, 0x1a, 0xa9, 0xb7, 0x07, 0xc3, 0xd5, 0x7a, 0xd5,
	0xa5, 0x75, 0x08, 0x63, 0x93, 0xf2, 0x44, 0x1a, 0x1e, 0x68, 0x41, 0x65, 0x44, 0xed, 0xf6, 0x8f,
	0xdf, 0xca, 0x32, 0x8c, 0x55, 0x0d, 0x32, 0xef, 0x76, 0x28, 0xe0, 0x99, 0xcc, 0xcf, 0x9e, 0x9b,
	0xc5, 0xe3, 0xb7, 0x6a, 0x05, 0xe2, 0xf4, 0x85, 0x79, 0xae, 0x53, 0x9f, 0xb5, 0xd7, 0x00, 0x77,
	0xf5, 0x2d, 0x50, 0xa6, 0x32, 0x88, 0xcd, 0x5b, 0x9d, 0x16, 0xc8, 0x77, 0x60, 0x84, 0x1f, 0x53,
	0xd3, 0x80, 0x0e, 0xf5, 0xb4, 0x11, 0xd3, 0xbd, 0xac, 0x6a, 0xc5, 0x67, 0xc5, 0x72, 0xaa, 0x9d,
	0x47, 0xa8, 0x1f, 0xcc, 0x8a, 0xe5, 0x29, 0xfa, 0xab, 0x13, 0x99, 0xc5, 0xb1, 0xd1, 0x8e, 0x51,
	0xeb, 0x2a, 0x04, 0xd5, 0xfe, 0x5f, 0x5a, 0xd0, 0x7d, 0xb4, 0x50, 0xd7, 0xf0, 0xd5, 0xee, 0xf4,
	0x06, 0x74, 0x99, 0x52, 0x98, 0xe7, 0x15, 0x2d, 0xa8, 0x25, 0x16, 0x82, 0xe5, 0xe6, 0x24, 0xc3,
	0x6f, 0x55, 0x92, 0x6d, 0x9b, 0xd1, 0xd1, 0x07, 0x9c, 0x6d, 0x2c, 0x76, 0xc1, 0x0d, 0xd3, 0x44,
	0x06, 0x3c, 0x61, 0x39, 0xc6, 0xcf, 0xa5, 0x15, 0x40, 0x76, 0x60, 0x20, 0x64, 0x1e, 0x48, 0x76,
	0xb6, 0x34, 0x6f, 0x4b, 0xa5, 0xdc, 0x4c, 0xe2, 0xfe, 0x6a, 0x12, 0x9b, 0x23, 0x35, 0x48, 0xa2,
	0xfa, 0x3b, 0x52, 0x90, 0xe0, 0x0b, 0xd3, 0x9c, 0x09, 0x11, 0x9c, 0xe9, 0xe8, 0xba, 0xd4, 0x8a,
	0xb8, 0x9e, 0x3c, 0x4f, 0x73, 0x0c, 0xef, 0x80, 0x6a, 0x41, 0xd9, 0x67, 0xc1, 0x32, 0x4e, 0x83,
	0x08, 0x23, 0xeb, 0x52, 0x2b, 0x1e, 0xfe, 0xa3, 0x05, 0xed, 0x7b, 0xc7, 0x47, 0xe4, 0xd0, 0x94,
	0xe4, 0x13, 0x96, 0x44, 0x64, 0xab, 0x7a, 0x4d, 0x30, 0x2d, 0xca, 0xce, 0x66, 0x1d, 0x52, 0xb7,
	0x0a, 0xff, 0x0d, 0xf2, 0x19, 0x8c, 0x9e, 0x30, 0x59, 0x3e, 0x02, 0x90, 0x1b, 0xcd, 0x3b, 0xbc,
	0xf1, 0x6c, 0xa2, 0xa2, 0xf4, 0xfe, 0x21, 0xc0, 0x13, 0x26, 0x6d, 0xbf, 0xbf, 0xdd, 0xe8, 0xd9,
	0x8c, 0x2b, 0x69, 0x82, 0xc6, 0xf1, 0x47, 0xb0, 0xa5, 0x7e, 0x56, 0xe7, 0xfb, 0x43, 0x26, 0x03,
	0x1e, 0x0b, 0xe3, 0xdf, 0xbc, 0x5f, 0x1b, 0xff, 0xc6, 0xbd, 0xd8, 0x7f, 0x83, 0x9c, 0xc2, 0xf6,
	0x13, 0x26, 0xf1, 0xae, 0x24, 0xab, 0xbb, 0x12, 0xd9, 0x45, 0xe3, 0x57, 0xdc, 0xe7, 0x76, 0xde,
	0x7e, 0x85, 0x56, 0x8f, 0x79, 0xdb, 0x99, 0xf5, 0xf0, 0xef, 0x9d, 0x3b, 0xff, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x85, 0xd5, 0xd0, 0x0c, 0xfc, 0x19, 0x00, 0x00,
}
