// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backtesting.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Subscription struct {
	Subscribe            []*SubscriptionItems `protobuf:"bytes,1,rep,name=subscribe,proto3" json:"subscribe,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_cad29974f829cd17, []int{0}
}
func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (dst *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(dst, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetSubscribe() []*SubscriptionItems {
	if m != nil {
		return m.Subscribe
	}
	return nil
}

type SubscriptionItems struct {
	Venue                Venue    `protobuf:"varint,1,opt,name=venue,proto3,enum=api.Venue" json:"venue,omitempty"`
	Product              string   `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Orderbook            bool     `protobuf:"varint,3,opt,name=orderbook,proto3" json:"orderbook,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriptionItems) Reset()         { *m = SubscriptionItems{} }
func (m *SubscriptionItems) String() string { return proto.CompactTextString(m) }
func (*SubscriptionItems) ProtoMessage()    {}
func (*SubscriptionItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_cad29974f829cd17, []int{1}
}
func (m *SubscriptionItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionItems.Unmarshal(m, b)
}
func (m *SubscriptionItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionItems.Marshal(b, m, deterministic)
}
func (dst *SubscriptionItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionItems.Merge(dst, src)
}
func (m *SubscriptionItems) XXX_Size() int {
	return xxx_messageInfo_SubscriptionItems.Size(m)
}
func (m *SubscriptionItems) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionItems.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionItems proto.InternalMessageInfo

func (m *SubscriptionItems) GetVenue() Venue {
	if m != nil {
		return m.Venue
	}
	return Venue_DARKPOOL
}

func (m *SubscriptionItems) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *SubscriptionItems) GetOrderbook() bool {
	if m != nil {
		return m.Orderbook
	}
	return false
}

type BacktestingTokenRequest struct {
	Initialization       *ClientInitilization `protobuf:"bytes,1,opt,name=initialization,proto3" json:"initialization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BacktestingTokenRequest) Reset()         { *m = BacktestingTokenRequest{} }
func (m *BacktestingTokenRequest) String() string { return proto.CompactTextString(m) }
func (*BacktestingTokenRequest) ProtoMessage()    {}
func (*BacktestingTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cad29974f829cd17, []int{2}
}
func (m *BacktestingTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BacktestingTokenRequest.Unmarshal(m, b)
}
func (m *BacktestingTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BacktestingTokenRequest.Marshal(b, m, deterministic)
}
func (dst *BacktestingTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BacktestingTokenRequest.Merge(dst, src)
}
func (m *BacktestingTokenRequest) XXX_Size() int {
	return xxx_messageInfo_BacktestingTokenRequest.Size(m)
}
func (m *BacktestingTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BacktestingTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BacktestingTokenRequest proto.InternalMessageInfo

func (m *BacktestingTokenRequest) GetInitialization() *ClientInitilization {
	if m != nil {
		return m.Initialization
	}
	return nil
}

type BacktestingTokenResponse struct {
	Retcode              Retcode  `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Comment              string   `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BacktestingTokenResponse) Reset()         { *m = BacktestingTokenResponse{} }
func (m *BacktestingTokenResponse) String() string { return proto.CompactTextString(m) }
func (*BacktestingTokenResponse) ProtoMessage()    {}
func (*BacktestingTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cad29974f829cd17, []int{3}
}
func (m *BacktestingTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BacktestingTokenResponse.Unmarshal(m, b)
}
func (m *BacktestingTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BacktestingTokenResponse.Marshal(b, m, deterministic)
}
func (dst *BacktestingTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BacktestingTokenResponse.Merge(dst, src)
}
func (m *BacktestingTokenResponse) XXX_Size() int {
	return xxx_messageInfo_BacktestingTokenResponse.Size(m)
}
func (m *BacktestingTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BacktestingTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BacktestingTokenResponse proto.InternalMessageInfo

func (m *BacktestingTokenResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *BacktestingTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *BacktestingTokenResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type BacktestingRequest struct {
	Account              string          `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Subscription         *Subscription   `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	StartDate            int64           `protobuf:"varint,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              int64           `protobuf:"varint,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Code                 BacktestingCode `protobuf:"varint,5,opt,name=code,proto3,enum=api.BacktestingCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BacktestingRequest) Reset()         { *m = BacktestingRequest{} }
func (m *BacktestingRequest) String() string { return proto.CompactTextString(m) }
func (*BacktestingRequest) ProtoMessage()    {}
func (*BacktestingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cad29974f829cd17, []int{4}
}
func (m *BacktestingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BacktestingRequest.Unmarshal(m, b)
}
func (m *BacktestingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BacktestingRequest.Marshal(b, m, deterministic)
}
func (dst *BacktestingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BacktestingRequest.Merge(dst, src)
}
func (m *BacktestingRequest) XXX_Size() int {
	return xxx_messageInfo_BacktestingRequest.Size(m)
}
func (m *BacktestingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BacktestingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BacktestingRequest proto.InternalMessageInfo

func (m *BacktestingRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *BacktestingRequest) GetSubscription() *Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

func (m *BacktestingRequest) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *BacktestingRequest) GetEndDate() int64 {
	if m != nil {
		return m.EndDate
	}
	return 0
}

func (m *BacktestingRequest) GetCode() BacktestingCode {
	if m != nil {
		return m.Code
	}
	return BacktestingCode_START
}

type BacktestingResponse struct {
	Retcode              Retcode         `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Code                 BacktestingCode `protobuf:"varint,2,opt,name=code,proto3,enum=api.BacktestingCode" json:"code,omitempty"`
	Trade                *Trade          `protobuf:"bytes,3,opt,name=trade,proto3" json:"trade,omitempty"`
	Orderbook            *Orderbook      `protobuf:"bytes,4,opt,name=orderbook,proto3" json:"orderbook,omitempty"`
	Comment              string          `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BacktestingResponse) Reset()         { *m = BacktestingResponse{} }
func (m *BacktestingResponse) String() string { return proto.CompactTextString(m) }
func (*BacktestingResponse) ProtoMessage()    {}
func (*BacktestingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cad29974f829cd17, []int{5}
}
func (m *BacktestingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BacktestingResponse.Unmarshal(m, b)
}
func (m *BacktestingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BacktestingResponse.Marshal(b, m, deterministic)
}
func (dst *BacktestingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BacktestingResponse.Merge(dst, src)
}
func (m *BacktestingResponse) XXX_Size() int {
	return xxx_messageInfo_BacktestingResponse.Size(m)
}
func (m *BacktestingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BacktestingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BacktestingResponse proto.InternalMessageInfo

func (m *BacktestingResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *BacktestingResponse) GetCode() BacktestingCode {
	if m != nil {
		return m.Code
	}
	return BacktestingCode_START
}

func (m *BacktestingResponse) GetTrade() *Trade {
	if m != nil {
		return m.Trade
	}
	return nil
}

func (m *BacktestingResponse) GetOrderbook() *Orderbook {
	if m != nil {
		return m.Orderbook
	}
	return nil
}

func (m *BacktestingResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type ClientInitilization struct {
	AccountMode          AccountMode   `protobuf:"varint,1,opt,name=account_mode,json=accountMode,proto3,enum=api.AccountMode" json:"account_mode,omitempty"`
	Subscription         *Subscription `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Balances             []*Balance    `protobuf:"bytes,3,rep,name=balances,proto3" json:"balances,omitempty"`
	StartDate            int64         `protobuf:"varint,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              int64         `protobuf:"varint,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	CandleGranularity    string        `protobuf:"bytes,6,opt,name=candle_granularity,json=candleGranularity,proto3" json:"candle_granularity,omitempty"`
	CandleGroupBy        CandleGroupBy `protobuf:"varint,7,opt,name=candle_group_by,json=candleGroupBy,proto3,enum=api.CandleGroupBy" json:"candle_group_by,omitempty"`
	Verbose              bool          `protobuf:"varint,8,opt,name=verbose,proto3" json:"verbose,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ClientInitilization) Reset()         { *m = ClientInitilization{} }
func (m *ClientInitilization) String() string { return proto.CompactTextString(m) }
func (*ClientInitilization) ProtoMessage()    {}
func (*ClientInitilization) Descriptor() ([]byte, []int) {
	return fileDescriptor_cad29974f829cd17, []int{6}
}
func (m *ClientInitilization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInitilization.Unmarshal(m, b)
}
func (m *ClientInitilization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInitilization.Marshal(b, m, deterministic)
}
func (dst *ClientInitilization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInitilization.Merge(dst, src)
}
func (m *ClientInitilization) XXX_Size() int {
	return xxx_messageInfo_ClientInitilization.Size(m)
}
func (m *ClientInitilization) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInitilization.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInitilization proto.InternalMessageInfo

func (m *ClientInitilization) GetAccountMode() AccountMode {
	if m != nil {
		return m.AccountMode
	}
	return AccountMode_DEMO
}

func (m *ClientInitilization) GetSubscription() *Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

func (m *ClientInitilization) GetBalances() []*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *ClientInitilization) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *ClientInitilization) GetEndDate() int64 {
	if m != nil {
		return m.EndDate
	}
	return 0
}

func (m *ClientInitilization) GetCandleGranularity() string {
	if m != nil {
		return m.CandleGranularity
	}
	return ""
}

func (m *ClientInitilization) GetCandleGroupBy() CandleGroupBy {
	if m != nil {
		return m.CandleGroupBy
	}
	return CandleGroupBy_TIME
}

func (m *ClientInitilization) GetVerbose() bool {
	if m != nil {
		return m.Verbose
	}
	return false
}

func init() {
	proto.RegisterType((*Subscription)(nil), "api.Subscription")
	proto.RegisterType((*SubscriptionItems)(nil), "api.SubscriptionItems")
	proto.RegisterType((*BacktestingTokenRequest)(nil), "api.BacktestingTokenRequest")
	proto.RegisterType((*BacktestingTokenResponse)(nil), "api.BacktestingTokenResponse")
	proto.RegisterType((*BacktestingRequest)(nil), "api.BacktestingRequest")
	proto.RegisterType((*BacktestingResponse)(nil), "api.BacktestingResponse")
	proto.RegisterType((*ClientInitilization)(nil), "api.ClientInitilization")
}

func init() { proto.RegisterFile("backtesting.proto", fileDescriptor_cad29974f829cd17) }

var fileDescriptor_cad29974f829cd17 = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x56, 0xd6, 0x76, 0x6d, 0x5e, 0x4b, 0x59, 0xbd, 0x09, 0xc2, 0x04, 0x52, 0x95, 0x03, 0xca,
	0x01, 0x7a, 0xe8, 0xe0, 0xc2, 0x09, 0xb6, 0x49, 0x68, 0x07, 0x84, 0x64, 0x26, 0x2e, 0x1c, 0x2a,
	0x27, 0xb1, 0xa6, 0xa8, 0x8d, 0x1d, 0x6c, 0x67, 0x52, 0xf9, 0x87, 0x1c, 0xf9, 0x1b, 0xfc, 0x0a,
	0xe4, 0xe7, 0x78, 0x49, 0x57, 0x04, 0x82, 0xe3, 0xfb, 0xbe, 0x2f, 0xfe, 0xfc, 0xbd, 0xf7, 0x1c,
	0x98, 0xa5, 0x2c, 0x5b, 0x1b, 0xae, 0x4d, 0x21, 0x6e, 0x16, 0x95, 0x92, 0x46, 0x92, 0x1e, 0xab,
	0x8a, 0x53, 0xe0, 0xa2, 0x2e, 0x1d, 0x70, 0x7a, 0x54, 0x32, 0xb5, 0xe6, 0x26, 0x67, 0x86, 0x35,
	0xc8, 0x34, 0x65, 0x1b, 0x26, 0x32, 0xae, 0x5d, 0x1d, 0x5f, 0xc2, 0xe4, 0x53, 0x9d, 0xea, 0x4c,
	0x15, 0x95, 0x29, 0xa4, 0x20, 0xaf, 0x20, 0xd4, 0xae, 0x4e, 0x79, 0x14, 0xcc, 0x7b, 0xc9, 0x78,
	0xf9, 0x68, 0xc1, 0xaa, 0x62, 0xd1, 0x55, 0x5d, 0x19, 0x5e, 0x6a, 0xda, 0x0a, 0xe3, 0x12, 0x66,
	0x7b, 0x3c, 0x99, 0xc3, 0xe0, 0x96, 0x8b, 0xda, 0x1e, 0x13, 0x24, 0xd3, 0x25, 0xe0, 0x31, 0x9f,
	0x2d, 0x42, 0x1d, 0x41, 0x22, 0x18, 0x56, 0x4a, 0xe6, 0x75, 0x66, 0xa2, 0x83, 0x79, 0x90, 0x84,
	0xd4, 0x97, 0xe4, 0x29, 0x84, 0x52, 0xe5, 0x5c, 0xa5, 0x52, 0xae, 0xa3, 0xde, 0x3c, 0x48, 0x46,
	0xb4, 0x05, 0xe2, 0x2f, 0xf0, 0xf8, 0xbc, 0x0d, 0x7f, 0x2d, 0xd7, 0x5c, 0x50, 0xfe, 0xb5, 0xe6,
	0xda, 0x90, 0xb7, 0x30, 0x2d, 0x44, 0x61, 0x0a, 0xb6, 0x29, 0xbe, 0x31, 0x7b, 0x17, 0x74, 0x1f,
	0x2f, 0x23, 0x74, 0xbf, 0xd8, 0x14, 0x5c, 0x98, 0x2b, 0x2b, 0xf0, 0x3c, 0xbd, 0xa7, 0x8f, 0x15,
	0x44, 0xfb, 0x87, 0xeb, 0x4a, 0x0a, 0xcd, 0xc9, 0x73, 0x18, 0x2a, 0x6e, 0x32, 0x99, 0xfb, 0x50,
	0x13, 0x3c, 0x96, 0x3a, 0x8c, 0x7a, 0x92, 0x9c, 0xc0, 0xc0, 0xd8, 0x0f, 0x9b, 0x58, 0xae, 0xb0,
	0x71, 0x33, 0x59, 0x96, 0x5c, 0x18, 0x8c, 0x14, 0x52, 0x5f, 0xc6, 0xdf, 0x03, 0x20, 0x1d, 0x53,
	0x1f, 0x26, 0x82, 0x21, 0xcb, 0x32, 0x59, 0x0b, 0x83, 0x76, 0x21, 0xf5, 0x25, 0x79, 0x0d, 0x13,
	0xdd, 0x69, 0x38, 0xfa, 0x8c, 0x97, 0xb3, 0xbd, 0x49, 0xd1, 0x1d, 0x19, 0x79, 0x06, 0xa0, 0x0d,
	0x53, 0x66, 0x95, 0x33, 0xc3, 0xf1, 0x12, 0x3d, 0x1a, 0x22, 0x72, 0xc9, 0x0c, 0x27, 0x4f, 0x60,
	0xc4, 0x45, 0xee, 0xc8, 0x3e, 0x92, 0x43, 0x2e, 0x72, 0xa4, 0x12, 0xe8, 0x63, 0xec, 0x01, 0xc6,
	0x3e, 0x41, 0xa3, 0xce, 0x8d, 0x2f, 0x6c, 0x7c, 0x54, 0xc4, 0x3f, 0x02, 0x38, 0xde, 0xc9, 0xf2,
	0x8f, 0xbd, 0xf3, 0x4e, 0x07, 0x7f, 0x73, 0xb2, 0x0b, 0x66, 0x14, 0xcb, 0x5d, 0x90, 0x71, 0xb3,
	0x60, 0xd7, 0x16, 0xa1, 0x8e, 0x20, 0x2f, 0xba, 0x6b, 0xd4, 0x47, 0xd5, 0x14, 0x55, 0x1f, 0x3d,
	0xda, 0x59, 0xab, 0xee, 0x7c, 0x06, 0xbb, 0xf3, 0xf9, 0x79, 0x00, 0xc7, 0xbf, 0xd9, 0x1d, 0x72,
	0x06, 0x93, 0x66, 0x22, 0xab, 0xb2, 0x0d, 0x76, 0x84, 0x16, 0xef, 0x1c, 0xf1, 0xc1, 0xde, 0x77,
	0xcc, 0xda, 0xe2, 0x7f, 0x67, 0x97, 0xc0, 0xc8, 0xbf, 0xdd, 0xa8, 0x87, 0x0f, 0x73, 0xd2, 0xf4,
	0x06, 0x41, 0x7a, 0xc7, 0xde, 0x9b, 0x72, 0xff, 0x4f, 0x53, 0x1e, 0xec, 0x4e, 0xf9, 0x25, 0x90,
	0x8c, 0x89, 0x7c, 0xc3, 0x57, 0x37, 0x8a, 0x89, 0x7a, 0xc3, 0x54, 0x61, 0xb6, 0xd1, 0x21, 0x36,
	0x63, 0xe6, 0x98, 0xf7, 0x2d, 0x41, 0xde, 0xc0, 0xc3, 0x3b, 0xb9, 0xac, 0xab, 0x55, 0xba, 0x8d,
	0x86, 0xd8, 0x01, 0xe2, 0x5e, 0x5b, 0xf3, 0x81, 0xac, 0xab, 0xf3, 0x2d, 0x7d, 0x90, 0x75, 0x4b,
	0xdb, 0xec, 0x5b, 0xdb, 0x77, 0xcd, 0xa3, 0x11, 0xbe, 0x6f, 0x5f, 0xa6, 0x87, 0xf8, 0x67, 0x3a,
	0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x91, 0x29, 0x47, 0xe1, 0x04, 0x00, 0x00,
}
