// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currencies.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Currency struct {
	CurrencyId           int32    `protobuf:"varint,1,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CurrencyDescription  string   `protobuf:"bytes,3,opt,name=currency_description,json=currencyDescription,proto3" json:"currency_description,omitempty"`
	MinConfirmation      int32    `protobuf:"varint,4,opt,name=min_confirmation,json=minConfirmation,proto3" json:"min_confirmation,omitempty"`
	Enabled              bool     `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TxFee                float64  `protobuf:"fixed64,6,opt,name=tx_fee,json=txFee,proto3" json:"tx_fee,omitempty"`
	CreateDate           string   `protobuf:"bytes,7,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	LastUpdate           string   `protobuf:"bytes,8,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Currency) Reset()         { *m = Currency{} }
func (m *Currency) String() string { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()    {}
func (*Currency) Descriptor() ([]byte, []int) {
	return fileDescriptor_1988b70e90d5a630, []int{0}
}
func (m *Currency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Currency.Unmarshal(m, b)
}
func (m *Currency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Currency.Marshal(b, m, deterministic)
}
func (dst *Currency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Currency.Merge(dst, src)
}
func (m *Currency) XXX_Size() int {
	return xxx_messageInfo_Currency.Size(m)
}
func (m *Currency) XXX_DiscardUnknown() {
	xxx_messageInfo_Currency.DiscardUnknown(m)
}

var xxx_messageInfo_Currency proto.InternalMessageInfo

func (m *Currency) GetCurrencyId() int32 {
	if m != nil {
		return m.CurrencyId
	}
	return 0
}

func (m *Currency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Currency) GetCurrencyDescription() string {
	if m != nil {
		return m.CurrencyDescription
	}
	return ""
}

func (m *Currency) GetMinConfirmation() int32 {
	if m != nil {
		return m.MinConfirmation
	}
	return 0
}

func (m *Currency) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Currency) GetTxFee() float64 {
	if m != nil {
		return m.TxFee
	}
	return 0
}

func (m *Currency) GetCreateDate() string {
	if m != nil {
		return m.CreateDate
	}
	return ""
}

func (m *Currency) GetLastUpdate() string {
	if m != nil {
		return m.LastUpdate
	}
	return ""
}

type CurrencyRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CurrencyId           int32    `protobuf:"varint,2,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrencyRequest) Reset()         { *m = CurrencyRequest{} }
func (m *CurrencyRequest) String() string { return proto.CompactTextString(m) }
func (*CurrencyRequest) ProtoMessage()    {}
func (*CurrencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1988b70e90d5a630, []int{1}
}
func (m *CurrencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyRequest.Unmarshal(m, b)
}
func (m *CurrencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyRequest.Marshal(b, m, deterministic)
}
func (dst *CurrencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyRequest.Merge(dst, src)
}
func (m *CurrencyRequest) XXX_Size() int {
	return xxx_messageInfo_CurrencyRequest.Size(m)
}
func (m *CurrencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyRequest proto.InternalMessageInfo

func (m *CurrencyRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CurrencyRequest) GetCurrencyId() int32 {
	if m != nil {
		return m.CurrencyId
	}
	return 0
}

func (m *CurrencyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CurrencyResponse struct {
	Retcode              Retcode     `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Currencies           []*Currency `protobuf:"bytes,2,rep,name=currencies,proto3" json:"currencies,omitempty"`
	Comment              string      `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Elapsed              string      `protobuf:"bytes,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CurrencyResponse) Reset()         { *m = CurrencyResponse{} }
func (m *CurrencyResponse) String() string { return proto.CompactTextString(m) }
func (*CurrencyResponse) ProtoMessage()    {}
func (*CurrencyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1988b70e90d5a630, []int{2}
}
func (m *CurrencyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyResponse.Unmarshal(m, b)
}
func (m *CurrencyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyResponse.Marshal(b, m, deterministic)
}
func (dst *CurrencyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyResponse.Merge(dst, src)
}
func (m *CurrencyResponse) XXX_Size() int {
	return xxx_messageInfo_CurrencyResponse.Size(m)
}
func (m *CurrencyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyResponse proto.InternalMessageInfo

func (m *CurrencyResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *CurrencyResponse) GetCurrencies() []*Currency {
	if m != nil {
		return m.Currencies
	}
	return nil
}

func (m *CurrencyResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *CurrencyResponse) GetElapsed() string {
	if m != nil {
		return m.Elapsed
	}
	return ""
}

type CurrencyPostRequest struct {
	Token                string    `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Currency             *Currency `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Action               Action    `protobuf:"varint,3,opt,name=action,proto3,enum=api.Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CurrencyPostRequest) Reset()         { *m = CurrencyPostRequest{} }
func (m *CurrencyPostRequest) String() string { return proto.CompactTextString(m) }
func (*CurrencyPostRequest) ProtoMessage()    {}
func (*CurrencyPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1988b70e90d5a630, []int{3}
}
func (m *CurrencyPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyPostRequest.Unmarshal(m, b)
}
func (m *CurrencyPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyPostRequest.Marshal(b, m, deterministic)
}
func (dst *CurrencyPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyPostRequest.Merge(dst, src)
}
func (m *CurrencyPostRequest) XXX_Size() int {
	return xxx_messageInfo_CurrencyPostRequest.Size(m)
}
func (m *CurrencyPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyPostRequest proto.InternalMessageInfo

func (m *CurrencyPostRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CurrencyPostRequest) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *CurrencyPostRequest) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_INSERT
}

type CurrencyPostResponse struct {
	Retcode              Retcode  `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Elapsed              string   `protobuf:"bytes,3,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrencyPostResponse) Reset()         { *m = CurrencyPostResponse{} }
func (m *CurrencyPostResponse) String() string { return proto.CompactTextString(m) }
func (*CurrencyPostResponse) ProtoMessage()    {}
func (*CurrencyPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1988b70e90d5a630, []int{4}
}
func (m *CurrencyPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyPostResponse.Unmarshal(m, b)
}
func (m *CurrencyPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyPostResponse.Marshal(b, m, deterministic)
}
func (dst *CurrencyPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyPostResponse.Merge(dst, src)
}
func (m *CurrencyPostResponse) XXX_Size() int {
	return xxx_messageInfo_CurrencyPostResponse.Size(m)
}
func (m *CurrencyPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyPostResponse proto.InternalMessageInfo

func (m *CurrencyPostResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *CurrencyPostResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *CurrencyPostResponse) GetElapsed() string {
	if m != nil {
		return m.Elapsed
	}
	return ""
}

func init() {
	proto.RegisterType((*Currency)(nil), "api.Currency")
	proto.RegisterType((*CurrencyRequest)(nil), "api.CurrencyRequest")
	proto.RegisterType((*CurrencyResponse)(nil), "api.CurrencyResponse")
	proto.RegisterType((*CurrencyPostRequest)(nil), "api.CurrencyPostRequest")
	proto.RegisterType((*CurrencyPostResponse)(nil), "api.CurrencyPostResponse")
}

func init() { proto.RegisterFile("currencies.proto", fileDescriptor_1988b70e90d5a630) }

var fileDescriptor_1988b70e90d5a630 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xd1, 0x6a, 0xd4, 0x40,
	0x14, 0x86, 0x49, 0xd2, 0x64, 0xb3, 0x67, 0xb5, 0x5d, 0xa6, 0x2b, 0x0c, 0xde, 0x18, 0x22, 0x48,
	0x7a, 0xe1, 0x82, 0xeb, 0x13, 0x48, 0x8b, 0xe0, 0x9d, 0x0c, 0x78, 0x27, 0x84, 0x69, 0x72, 0x0a,
	0x83, 0x9b, 0x99, 0x38, 0x33, 0x81, 0x16, 0x5f, 0xc2, 0x17, 0xf0, 0x5d, 0xa5, 0x27, 0x3b, 0xc9,
	0x56, 0x59, 0xc1, 0xbb, 0x9c, 0xff, 0xfc, 0x33, 0xe7, 0xfc, 0x5f, 0x12, 0x58, 0x37, 0x83, 0xb5,
	0xa8, 0x1b, 0x85, 0x6e, 0xdb, 0x5b, 0xe3, 0x0d, 0x4b, 0x64, 0xaf, 0x5e, 0x02, 0xea, 0xa1, 0x1b,
	0x85, 0xf2, 0x67, 0x0c, 0xf9, 0xf5, 0xe8, 0x7a, 0x60, 0xaf, 0x60, 0x75, 0x38, 0xf1, 0x50, 0xab,
	0x96, 0x47, 0x45, 0x54, 0xa5, 0x02, 0x82, 0xf4, 0xa9, 0x65, 0x0c, 0xce, 0xb4, 0xec, 0x90, 0xc7,
	0x45, 0x54, 0x2d, 0x05, 0x3d, 0xb3, 0x77, 0xb0, 0x99, 0x0e, 0xb5, 0xe8, 0x1a, 0xab, 0x7a, 0xaf,
	0x8c, 0xe6, 0x09, 0x79, 0x2e, 0x43, 0xef, 0x66, 0x6e, 0xb1, 0x2b, 0x58, 0x77, 0x4a, 0xd7, 0x8d,
	0xd1, 0x77, 0xca, 0x76, 0x92, 0xec, 0x67, 0x34, 0xec, 0xa2, 0x53, 0xfa, 0xfa, 0x48, 0x66, 0x1c,
	0x16, 0xa8, 0xe5, 0xed, 0x1e, 0x5b, 0x9e, 0x16, 0x51, 0x95, 0x8b, 0x50, 0xb2, 0x17, 0x90, 0xf9,
	0xfb, 0xfa, 0x0e, 0x91, 0x67, 0x45, 0x54, 0x45, 0x22, 0xf5, 0xf7, 0x1f, 0x11, 0x29, 0x83, 0x45,
	0xe9, 0xb1, 0x6e, 0xa5, 0x47, 0xbe, 0xa0, 0x2d, 0x60, 0x94, 0x6e, 0xa4, 0x27, 0xc3, 0x5e, 0x3a,
	0x5f, 0x0f, 0x3d, 0x19, 0xf2, 0xd1, 0xf0, 0x28, 0x7d, 0x21, 0xa5, 0xfc, 0x0a, 0x17, 0x81, 0x88,
	0xc0, 0xef, 0x03, 0x3a, 0xcf, 0x36, 0x90, 0x7a, 0xf3, 0x0d, 0x35, 0x21, 0x59, 0x8a, 0xb1, 0xf8,
	0x13, 0x57, 0x7c, 0x12, 0x57, 0x32, 0xe3, 0x2a, 0x7f, 0x45, 0xb0, 0x9e, 0xaf, 0x77, 0xbd, 0xd1,
	0x0e, 0xd9, 0x1b, 0x58, 0x58, 0xf4, 0x8d, 0x69, 0x91, 0x26, 0x9c, 0xef, 0x9e, 0x6d, 0x65, 0xaf,
	0xb6, 0x62, 0xd4, 0x44, 0x68, 0xb2, 0xb7, 0x00, 0xf3, 0x2b, 0xe5, 0x71, 0x91, 0x54, 0xab, 0xdd,
	0x73, 0xb2, 0x4e, 0x57, 0x1e, 0x19, 0x1e, 0xe1, 0x35, 0xa6, 0xeb, 0x50, 0xfb, 0xc3, 0x0a, 0xa1,
	0x24, 0xac, 0x7b, 0xd9, 0x3b, 0x6c, 0x09, 0xfc, 0x52, 0x84, 0xb2, 0xfc, 0x01, 0x97, 0xe1, 0xae,
	0xcf, 0xc6, 0xf9, 0x7f, 0x13, 0xb8, 0x82, 0x3c, 0xc4, 0xa5, 0xf8, 0x7f, 0x6d, 0x33, 0xb5, 0xd9,
	0x6b, 0xc8, 0x64, 0x33, 0x7d, 0x18, 0xe7, 0xbb, 0x15, 0x19, 0x3f, 0x90, 0x24, 0x0e, 0xad, 0xd2,
	0xc2, 0xe6, 0xe9, 0xf0, 0xff, 0xe4, 0x73, 0x14, 0x38, 0x3e, 0x19, 0x38, 0x79, 0x12, 0xf8, 0x36,
	0xa3, 0x1f, 0xe1, 0xfd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x47, 0x19, 0xfd, 0x2d, 0x03,
	0x00, 0x00,
}
