// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enum.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Venue int32

const (
	Venue_DARKPOOL    Venue = 0
	Venue_COINBASEPRO Venue = 1
	Venue_BITMEX      Venue = 2
	Venue_BITFINEX    Venue = 3
	Venue_BINANCE     Venue = 4
	Venue_GEMINI      Venue = 5
)

var Venue_name = map[int32]string{
	0: "DARKPOOL",
	1: "COINBASEPRO",
	2: "BITMEX",
	3: "BITFINEX",
	4: "BINANCE",
	5: "GEMINI",
}
var Venue_value = map[string]int32{
	"DARKPOOL":    0,
	"COINBASEPRO": 1,
	"BITMEX":      2,
	"BITFINEX":    3,
	"BINANCE":     4,
	"GEMINI":      5,
}

func (x Venue) String() string {
	return proto.EnumName(Venue_name, int32(x))
}
func (Venue) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{0}
}

type AccountMode int32

const (
	AccountMode_DEMO        AccountMode = 0
	AccountMode_LIVE        AccountMode = 1
	AccountMode_BACKTESTING AccountMode = 2
)

var AccountMode_name = map[int32]string{
	0: "DEMO",
	1: "LIVE",
	2: "BACKTESTING",
}
var AccountMode_value = map[string]int32{
	"DEMO":        0,
	"LIVE":        1,
	"BACKTESTING": 2,
}

func (x AccountMode) String() string {
	return proto.EnumName(AccountMode_name, int32(x))
}
func (AccountMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{1}
}

type AccountType int32

const (
	AccountType_NET   AccountType = 0
	AccountType_HEDGE AccountType = 1
)

var AccountType_name = map[int32]string{
	0: "NET",
	1: "HEDGE",
}
var AccountType_value = map[string]int32{
	"NET":   0,
	"HEDGE": 1,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{2}
}

type VenueType int32

const (
	VenueType_SPOT    VenueType = 0
	VenueType_FUTURES VenueType = 1
)

var VenueType_name = map[int32]string{
	0: "SPOT",
	1: "FUTURES",
}
var VenueType_value = map[string]int32{
	"SPOT":    0,
	"FUTURES": 1,
}

func (x VenueType) String() string {
	return proto.EnumName(VenueType_name, int32(x))
}
func (VenueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{3}
}

type Currency int32

const (
	Currency_BTC Currency = 0
	Currency_USD Currency = 1
	Currency_ETH Currency = 2
	Currency_LTC Currency = 3
	Currency_BCH Currency = 4
	Currency_ETC Currency = 5
)

var Currency_name = map[int32]string{
	0: "BTC",
	1: "USD",
	2: "ETH",
	3: "LTC",
	4: "BCH",
	5: "ETC",
}
var Currency_value = map[string]int32{
	"BTC": 0,
	"USD": 1,
	"ETH": 2,
	"LTC": 3,
	"BCH": 4,
	"ETC": 5,
}

func (x Currency) String() string {
	return proto.EnumName(Currency_name, int32(x))
}
func (Currency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{4}
}

type Product int32

const (
	Product_BTC_USD Product = 0
	Product_ETH_BTC Product = 1
	Product_ETH_USD Product = 2
	Product_LTC_USD Product = 3
	Product_LTC_BTC Product = 4
	Product_LTC_ETH Product = 5
	Product_BCH_USD Product = 6
	Product_BCH_BTC Product = 7
	Product_BCH_ETH Product = 8
	Product_ETC_USD Product = 9
	Product_ETC_BTC Product = 10
	Product_ETC_ETH Product = 11
)

var Product_name = map[int32]string{
	0:  "BTC_USD",
	1:  "ETH_BTC",
	2:  "ETH_USD",
	3:  "LTC_USD",
	4:  "LTC_BTC",
	5:  "LTC_ETH",
	6:  "BCH_USD",
	7:  "BCH_BTC",
	8:  "BCH_ETH",
	9:  "ETC_USD",
	10: "ETC_BTC",
	11: "ETC_ETH",
}
var Product_value = map[string]int32{
	"BTC_USD": 0,
	"ETH_BTC": 1,
	"ETH_USD": 2,
	"LTC_USD": 3,
	"LTC_BTC": 4,
	"LTC_ETH": 5,
	"BCH_USD": 6,
	"BCH_BTC": 7,
	"BCH_ETH": 8,
	"ETC_USD": 9,
	"ETC_BTC": 10,
	"ETC_ETH": 11,
}

func (x Product) String() string {
	return proto.EnumName(Product_name, int32(x))
}
func (Product) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{5}
}

type OrderState int32

const (
	OrderState_STARTED        OrderState = 0
	OrderState_PLACED         OrderState = 1
	OrderState_CANCELED       OrderState = 2
	OrderState_PARTIAL        OrderState = 3
	OrderState_FILLED         OrderState = 4
	OrderState_REJECTED       OrderState = 5
	OrderState_EXPIRED        OrderState = 6
	OrderState_REQUEST_ADD    OrderState = 7
	OrderState_REQUEST_MODIFY OrderState = 8
	OrderState_REQUEST_CANCEL OrderState = 9
)

var OrderState_name = map[int32]string{
	0: "STARTED",
	1: "PLACED",
	2: "CANCELED",
	3: "PARTIAL",
	4: "FILLED",
	5: "REJECTED",
	6: "EXPIRED",
	7: "REQUEST_ADD",
	8: "REQUEST_MODIFY",
	9: "REQUEST_CANCEL",
}
var OrderState_value = map[string]int32{
	"STARTED":        0,
	"PLACED":         1,
	"CANCELED":       2,
	"PARTIAL":        3,
	"FILLED":         4,
	"REJECTED":       5,
	"EXPIRED":        6,
	"REQUEST_ADD":    7,
	"REQUEST_MODIFY": 8,
	"REQUEST_CANCEL": 9,
}

func (x OrderState) String() string {
	return proto.EnumName(OrderState_name, int32(x))
}
func (OrderState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{6}
}

type OrderTypeFilling int32

const (
	OrderTypeFilling_FOK    OrderTypeFilling = 0
	OrderTypeFilling_IOC    OrderTypeFilling = 1
	OrderTypeFilling_RETURN OrderTypeFilling = 2
)

var OrderTypeFilling_name = map[int32]string{
	0: "FOK",
	1: "IOC",
	2: "RETURN",
}
var OrderTypeFilling_value = map[string]int32{
	"FOK":    0,
	"IOC":    1,
	"RETURN": 2,
}

func (x OrderTypeFilling) String() string {
	return proto.EnumName(OrderTypeFilling_name, int32(x))
}
func (OrderTypeFilling) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{7}
}

type Reason int32

const (
	Reason_ORDER_CLIENT   Reason = 0
	Reason_ORDER_MOBILE   Reason = 1
	Reason_ORDER_WEB      Reason = 2
	Reason_ORDER_STRATEGY Reason = 3
	Reason_ORDER_SL       Reason = 4
	Reason_ORDER_TP       Reason = 5
	Reason_ORDER_SO       Reason = 6
)

var Reason_name = map[int32]string{
	0: "ORDER_CLIENT",
	1: "ORDER_MOBILE",
	2: "ORDER_WEB",
	3: "ORDER_STRATEGY",
	4: "ORDER_SL",
	5: "ORDER_TP",
	6: "ORDER_SO",
}
var Reason_value = map[string]int32{
	"ORDER_CLIENT":   0,
	"ORDER_MOBILE":   1,
	"ORDER_WEB":      2,
	"ORDER_STRATEGY": 3,
	"ORDER_SL":       4,
	"ORDER_TP":       5,
	"ORDER_SO":       6,
}

func (x Reason) String() string {
	return proto.EnumName(Reason_name, int32(x))
}
func (Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{8}
}

type OrderTypeTime int32

const (
	OrderTypeTime_GTC           OrderTypeTime = 0
	OrderTypeTime_DAY           OrderTypeTime = 1
	OrderTypeTime_SPECIFIED     OrderTypeTime = 2
	OrderTypeTime_SPECIFIED_DAY OrderTypeTime = 3
)

var OrderTypeTime_name = map[int32]string{
	0: "GTC",
	1: "DAY",
	2: "SPECIFIED",
	3: "SPECIFIED_DAY",
}
var OrderTypeTime_value = map[string]int32{
	"GTC":           0,
	"DAY":           1,
	"SPECIFIED":     2,
	"SPECIFIED_DAY": 3,
}

func (x OrderTypeTime) String() string {
	return proto.EnumName(OrderTypeTime_name, int32(x))
}
func (OrderTypeTime) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{9}
}

type OrderEntryType int32

const (
	OrderEntryType_IN     OrderEntryType = 0
	OrderEntryType_OUT    OrderEntryType = 1
	OrderEntryType_INOUT  OrderEntryType = 2
	OrderEntryType_OUT_BY OrderEntryType = 3
)

var OrderEntryType_name = map[int32]string{
	0: "IN",
	1: "OUT",
	2: "INOUT",
	3: "OUT_BY",
}
var OrderEntryType_value = map[string]int32{
	"IN":     0,
	"OUT":    1,
	"INOUT":  2,
	"OUT_BY": 3,
}

func (x OrderEntryType) String() string {
	return proto.EnumName(OrderEntryType_name, int32(x))
}
func (OrderEntryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{10}
}

type Side int32

const (
	Side_BUY  Side = 0
	Side_SELL Side = 1
)

var Side_name = map[int32]string{
	0: "BUY",
	1: "SELL",
}
var Side_value = map[string]int32{
	"BUY":  0,
	"SELL": 1,
}

func (x Side) String() string {
	return proto.EnumName(Side_name, int32(x))
}
func (Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{11}
}

type OrderType int32

const (
	OrderType_MARKET     OrderType = 0
	OrderType_LIMIT      OrderType = 1
	OrderType_STOP       OrderType = 2
	OrderType_STOP_LIMIT OrderType = 3
	OrderType_CLOSING_BY OrderType = 4
)

var OrderType_name = map[int32]string{
	0: "MARKET",
	1: "LIMIT",
	2: "STOP",
	3: "STOP_LIMIT",
	4: "CLOSING_BY",
}
var OrderType_value = map[string]int32{
	"MARKET":     0,
	"LIMIT":      1,
	"STOP":       2,
	"STOP_LIMIT": 3,
	"CLOSING_BY": 4,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{12}
}

type DealType int32

const (
	DealType_POSITION      DealType = 0
	DealType_BALANCE       DealType = 1
	DealType_CREDIT        DealType = 2
	DealType_CHARGE        DealType = 3
	DealType_CORRECTION    DealType = 4
	DealType_BONUS         DealType = 5
	DealType_COMMISSION    DealType = 6
	DealType_INTEREST      DealType = 7
	DealType_BUY_CANCELED  DealType = 8
	DealType_SELL_CANCELED DealType = 9
	DealType_DIVIDEND      DealType = 10
)

var DealType_name = map[int32]string{
	0:  "POSITION",
	1:  "BALANCE",
	2:  "CREDIT",
	3:  "CHARGE",
	4:  "CORRECTION",
	5:  "BONUS",
	6:  "COMMISSION",
	7:  "INTEREST",
	8:  "BUY_CANCELED",
	9:  "SELL_CANCELED",
	10: "DIVIDEND",
}
var DealType_value = map[string]int32{
	"POSITION":      0,
	"BALANCE":       1,
	"CREDIT":        2,
	"CHARGE":        3,
	"CORRECTION":    4,
	"BONUS":         5,
	"COMMISSION":    6,
	"INTEREST":      7,
	"BUY_CANCELED":  8,
	"SELL_CANCELED": 9,
	"DIVIDEND":      10,
}

func (x DealType) String() string {
	return proto.EnumName(DealType_name, int32(x))
}
func (DealType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{13}
}

type TradeAction int32

const (
	TradeAction_DEAL     TradeAction = 0
	TradeAction_PENDING  TradeAction = 1
	TradeAction_SLTP     TradeAction = 2
	TradeAction_MODIFY   TradeAction = 3
	TradeAction_REMOVE   TradeAction = 4
	TradeAction_CLOSE_BY TradeAction = 5
)

var TradeAction_name = map[int32]string{
	0: "DEAL",
	1: "PENDING",
	2: "SLTP",
	3: "MODIFY",
	4: "REMOVE",
	5: "CLOSE_BY",
}
var TradeAction_value = map[string]int32{
	"DEAL":     0,
	"PENDING":  1,
	"SLTP":     2,
	"MODIFY":   3,
	"REMOVE":   4,
	"CLOSE_BY": 5,
}

func (x TradeAction) String() string {
	return proto.EnumName(TradeAction_name, int32(x))
}
func (TradeAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{14}
}

type Retcode int32

const (
	Retcode_REJECTX               Retcode = 0
	Retcode_REJECT                Retcode = 2
	Retcode_CANCEL                Retcode = 3
	Retcode_PLACED_TRADE          Retcode = 4
	Retcode_DONE                  Retcode = 5
	Retcode_DONE_PARTIAL          Retcode = 6
	Retcode_ERROR                 Retcode = 7
	Retcode_TIMEOUT               Retcode = 8
	Retcode_INVALID               Retcode = 9
	Retcode_INVALID_VOLUME        Retcode = 10
	Retcode_INVALID_PRICE         Retcode = 11
	Retcode_INVALID_STOPS         Retcode = 12
	Retcode_TRADE_DISABLED        Retcode = 13
	Retcode_MARKET_CLOSED         Retcode = 14
	Retcode_NO_MONEY              Retcode = 15
	Retcode_PRICE_CHANGED         Retcode = 16
	Retcode_PRICE_OFF             Retcode = 17
	Retcode_INVALID_EXPIRATION    Retcode = 18
	Retcode_ORDER_CHANGED         Retcode = 19
	Retcode_TOO_MANY_REQUESTS     Retcode = 21
	Retcode_NO_CHANGES            Retcode = 22
	Retcode_SERVER_DISABLES_AT    Retcode = 23
	Retcode_CLIENT_DISABLES_AT    Retcode = 24
	Retcode_LOCKED                Retcode = 25
	Retcode_FROZEN                Retcode = 26
	Retcode_INVALID_FILL          Retcode = 27
	Retcode_CONNECTION            Retcode = 28
	Retcode_ONLY_REAL             Retcode = 29
	Retcode_LIMIT_ORDERS          Retcode = 30
	Retcode_LIMIT_VOLUME          Retcode = 31
	Retcode_INVALID_ORDER         Retcode = 32
	Retcode_POSITION_CLOSED       Retcode = 33
	Retcode_CLOSE_ORDER_EXIST     Retcode = 34
	Retcode_LIMIT_POSITIONS       Retcode = 35
	Retcode_REJECT_CANCEL         Retcode = 36
	Retcode_LONG_ONLY             Retcode = 37
	Retcode_SHORT_ONLY            Retcode = 38
	Retcode_CLOSE_ONLY            Retcode = 39
	Retcode_REQUEST_WITH_NO_TOKEN Retcode = 40
	Retcode_INVALID_TOKEN         Retcode = 41
	Retcode_INVALID_REQUEST       Retcode = 42
)

var Retcode_name = map[int32]string{
	0:  "REJECTX",
	2:  "REJECT",
	3:  "CANCEL",
	4:  "PLACED_TRADE",
	5:  "DONE",
	6:  "DONE_PARTIAL",
	7:  "ERROR",
	8:  "TIMEOUT",
	9:  "INVALID",
	10: "INVALID_VOLUME",
	11: "INVALID_PRICE",
	12: "INVALID_STOPS",
	13: "TRADE_DISABLED",
	14: "MARKET_CLOSED",
	15: "NO_MONEY",
	16: "PRICE_CHANGED",
	17: "PRICE_OFF",
	18: "INVALID_EXPIRATION",
	19: "ORDER_CHANGED",
	21: "TOO_MANY_REQUESTS",
	22: "NO_CHANGES",
	23: "SERVER_DISABLES_AT",
	24: "CLIENT_DISABLES_AT",
	25: "LOCKED",
	26: "FROZEN",
	27: "INVALID_FILL",
	28: "CONNECTION",
	29: "ONLY_REAL",
	30: "LIMIT_ORDERS",
	31: "LIMIT_VOLUME",
	32: "INVALID_ORDER",
	33: "POSITION_CLOSED",
	34: "CLOSE_ORDER_EXIST",
	35: "LIMIT_POSITIONS",
	36: "REJECT_CANCEL",
	37: "LONG_ONLY",
	38: "SHORT_ONLY",
	39: "CLOSE_ONLY",
	40: "REQUEST_WITH_NO_TOKEN",
	41: "INVALID_TOKEN",
	42: "INVALID_REQUEST",
}
var Retcode_value = map[string]int32{
	"REJECTX":               0,
	"REJECT":                2,
	"CANCEL":                3,
	"PLACED_TRADE":          4,
	"DONE":                  5,
	"DONE_PARTIAL":          6,
	"ERROR":                 7,
	"TIMEOUT":               8,
	"INVALID":               9,
	"INVALID_VOLUME":        10,
	"INVALID_PRICE":         11,
	"INVALID_STOPS":         12,
	"TRADE_DISABLED":        13,
	"MARKET_CLOSED":         14,
	"NO_MONEY":              15,
	"PRICE_CHANGED":         16,
	"PRICE_OFF":             17,
	"INVALID_EXPIRATION":    18,
	"ORDER_CHANGED":         19,
	"TOO_MANY_REQUESTS":     21,
	"NO_CHANGES":            22,
	"SERVER_DISABLES_AT":    23,
	"CLIENT_DISABLES_AT":    24,
	"LOCKED":                25,
	"FROZEN":                26,
	"INVALID_FILL":          27,
	"CONNECTION":            28,
	"ONLY_REAL":             29,
	"LIMIT_ORDERS":          30,
	"LIMIT_VOLUME":          31,
	"INVALID_ORDER":         32,
	"POSITION_CLOSED":       33,
	"CLOSE_ORDER_EXIST":     34,
	"LIMIT_POSITIONS":       35,
	"REJECT_CANCEL":         36,
	"LONG_ONLY":             37,
	"SHORT_ONLY":            38,
	"CLOSE_ONLY":            39,
	"REQUEST_WITH_NO_TOKEN": 40,
	"INVALID_TOKEN":         41,
	"INVALID_REQUEST":       42,
}

func (x Retcode) String() string {
	return proto.EnumName(Retcode_name, int32(x))
}
func (Retcode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{15}
}

type Granularity int32

const (
	Granularity_GRANULARITY_0M  Granularity = 0
	Granularity_GRANULARITY_1M  Granularity = 60
	Granularity_GRANULARITY_2M  Granularity = 120
	Granularity_GRANULARITY_3M  Granularity = 180
	Granularity_GRANULARITY_4M  Granularity = 240
	Granularity_GRANULARITY_5M  Granularity = 300
	Granularity_GRANULARITY_6M  Granularity = 360
	Granularity_GRANULARITY_7M  Granularity = 420
	Granularity_GRANULARITY_8M  Granularity = 480
	Granularity_GRANULARITY_9M  Granularity = 540
	Granularity_GRANULARITY_10M Granularity = 600
	Granularity_GRANULARITY_15M Granularity = 900
	Granularity_GRANULARITY_20M Granularity = 1200
	Granularity_GRANULARITY_30M Granularity = 1800
	Granularity_GRANULARITY_40M Granularity = 2400
	Granularity_GRANULARITY_50M Granularity = 3000
	Granularity_GRANULARITY_1H  Granularity = 3600
	Granularity_GRANULARITY_2H  Granularity = 7200
	Granularity_GRANULARITY_3H  Granularity = 10800
	Granularity_GRANULARITY_4H  Granularity = 14400
	Granularity_GRANULARITY_5H  Granularity = 18000
	Granularity_GRANULARITY_6H  Granularity = 21600
	Granularity_GRANULARITY_7H  Granularity = 25200
	Granularity_GRANULARITY_8H  Granularity = 28800
	Granularity_GRANULARITY_9H  Granularity = 32400
	Granularity_GRANULARITY_10H Granularity = 36000
	Granularity_GRANULARITY_11H Granularity = 39600
	Granularity_GRANULARITY_12H Granularity = 43200
	Granularity_GRANULARITY_1D  Granularity = 86400
)

var Granularity_name = map[int32]string{
	0:     "GRANULARITY_0M",
	60:    "GRANULARITY_1M",
	120:   "GRANULARITY_2M",
	180:   "GRANULARITY_3M",
	240:   "GRANULARITY_4M",
	300:   "GRANULARITY_5M",
	360:   "GRANULARITY_6M",
	420:   "GRANULARITY_7M",
	480:   "GRANULARITY_8M",
	540:   "GRANULARITY_9M",
	600:   "GRANULARITY_10M",
	900:   "GRANULARITY_15M",
	1200:  "GRANULARITY_20M",
	1800:  "GRANULARITY_30M",
	2400:  "GRANULARITY_40M",
	3000:  "GRANULARITY_50M",
	3600:  "GRANULARITY_1H",
	7200:  "GRANULARITY_2H",
	10800: "GRANULARITY_3H",
	14400: "GRANULARITY_4H",
	18000: "GRANULARITY_5H",
	21600: "GRANULARITY_6H",
	25200: "GRANULARITY_7H",
	28800: "GRANULARITY_8H",
	32400: "GRANULARITY_9H",
	36000: "GRANULARITY_10H",
	39600: "GRANULARITY_11H",
	43200: "GRANULARITY_12H",
	86400: "GRANULARITY_1D",
}
var Granularity_value = map[string]int32{
	"GRANULARITY_0M":  0,
	"GRANULARITY_1M":  60,
	"GRANULARITY_2M":  120,
	"GRANULARITY_3M":  180,
	"GRANULARITY_4M":  240,
	"GRANULARITY_5M":  300,
	"GRANULARITY_6M":  360,
	"GRANULARITY_7M":  420,
	"GRANULARITY_8M":  480,
	"GRANULARITY_9M":  540,
	"GRANULARITY_10M": 600,
	"GRANULARITY_15M": 900,
	"GRANULARITY_20M": 1200,
	"GRANULARITY_30M": 1800,
	"GRANULARITY_40M": 2400,
	"GRANULARITY_50M": 3000,
	"GRANULARITY_1H":  3600,
	"GRANULARITY_2H":  7200,
	"GRANULARITY_3H":  10800,
	"GRANULARITY_4H":  14400,
	"GRANULARITY_5H":  18000,
	"GRANULARITY_6H":  21600,
	"GRANULARITY_7H":  25200,
	"GRANULARITY_8H":  28800,
	"GRANULARITY_9H":  32400,
	"GRANULARITY_10H": 36000,
	"GRANULARITY_11H": 39600,
	"GRANULARITY_12H": 43200,
	"GRANULARITY_1D":  86400,
}

func (x Granularity) String() string {
	return proto.EnumName(Granularity_name, int32(x))
}
func (Granularity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{16}
}

type CandleGroupBy int32

const (
	CandleGroupBy_TIME   CandleGroupBy = 0
	CandleGroupBy_VOLUME CandleGroupBy = 1
	CandleGroupBy_TRADE  CandleGroupBy = 2
)

var CandleGroupBy_name = map[int32]string{
	0: "TIME",
	1: "VOLUME",
	2: "TRADE",
}
var CandleGroupBy_value = map[string]int32{
	"TIME":   0,
	"VOLUME": 1,
	"TRADE":  2,
}

func (x CandleGroupBy) String() string {
	return proto.EnumName(CandleGroupBy_name, int32(x))
}
func (CandleGroupBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_275994fad69e7835, []int{17}
}

func init() {
	proto.RegisterEnum("api.Venue", Venue_name, Venue_value)
	proto.RegisterEnum("api.AccountMode", AccountMode_name, AccountMode_value)
	proto.RegisterEnum("api.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("api.VenueType", VenueType_name, VenueType_value)
	proto.RegisterEnum("api.Currency", Currency_name, Currency_value)
	proto.RegisterEnum("api.Product", Product_name, Product_value)
	proto.RegisterEnum("api.OrderState", OrderState_name, OrderState_value)
	proto.RegisterEnum("api.OrderTypeFilling", OrderTypeFilling_name, OrderTypeFilling_value)
	proto.RegisterEnum("api.Reason", Reason_name, Reason_value)
	proto.RegisterEnum("api.OrderTypeTime", OrderTypeTime_name, OrderTypeTime_value)
	proto.RegisterEnum("api.OrderEntryType", OrderEntryType_name, OrderEntryType_value)
	proto.RegisterEnum("api.Side", Side_name, Side_value)
	proto.RegisterEnum("api.OrderType", OrderType_name, OrderType_value)
	proto.RegisterEnum("api.DealType", DealType_name, DealType_value)
	proto.RegisterEnum("api.TradeAction", TradeAction_name, TradeAction_value)
	proto.RegisterEnum("api.Retcode", Retcode_name, Retcode_value)
	proto.RegisterEnum("api.Granularity", Granularity_name, Granularity_value)
	proto.RegisterEnum("api.CandleGroupBy", CandleGroupBy_name, CandleGroupBy_value)
}

func init() { proto.RegisterFile("enum.proto", fileDescriptor_enum_275994fad69e7835) }

var fileDescriptor_enum_275994fad69e7835 = []byte{
	// 1396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x56, 0x3b, 0x8f, 0x1c, 0x45,
	0x10, 0xbe, 0x7d, 0xef, 0xf6, 0xde, 0xa3, 0x3c, 0xf6, 0xd9, 0x18, 0xcc, 0xc3, 0xe6, 0x3d, 0x01,
	0xda, 0x3b, 0xbf, 0xce, 0x12, 0x01, 0xf3, 0xe8, 0xdd, 0x69, 0x6e, 0xba, 0x7b, 0xe9, 0xe9, 0x3d,
	0xdf, 0x92, 0x8c, 0x96, 0xbb, 0x15, 0x3a, 0xe9, 0xbc, 0x7b, 0x5a, 0xf6, 0x24, 0x2e, 0x73, 0x40,
	0x40, 0x40, 0xe0, 0x14, 0x89, 0xc0, 0x12, 0x20, 0x81, 0x44, 0xe0, 0x00, 0x24, 0x42, 0x07, 0xfc,
	0x00, 0xc8, 0x10, 0x91, 0xc9, 0x08, 0xfd, 0x07, 0x2c, 0xa1, 0xea, 0x9e, 0x39, 0x9f, 0x67, 0xb3,
	0xa9, 0xaf, 0xab, 0xaa, 0xbf, 0xae, 0xfa, 0xaa, 0x76, 0x09, 0x19, 0x4f, 0x8e, 0xef, 0x7d, 0x70,
	0x34, 0x9b, 0xce, 0xa7, 0x4e, 0x65, 0x74, 0x74, 0xe0, 0x0e, 0x49, 0x6d, 0x67, 0x3c, 0x39, 0x1e,
	0x3b, 0xcb, 0xa4, 0x19, 0x7a, 0x6a, 0xbb, 0x2f, 0x65, 0x0c, 0x4b, 0xce, 0x1a, 0x69, 0x07, 0x92,
	0x09, 0xdf, 0x4b, 0x68, 0x5f, 0x49, 0x28, 0x39, 0x84, 0xd4, 0x7d, 0xa6, 0x39, 0xdd, 0x85, 0x32,
	0xba, 0xfa, 0x4c, 0x77, 0x99, 0xa0, 0xbb, 0x50, 0x71, 0xda, 0xa4, 0xe1, 0x33, 0xe1, 0x89, 0x80,
	0x42, 0x15, 0xdd, 0x7a, 0x94, 0x33, 0xc1, 0xa0, 0xe6, 0x6e, 0x92, 0xb6, 0xb7, 0xb7, 0x37, 0x3d,
	0x9e, 0xcc, 0xf9, 0x74, 0x7f, 0xec, 0x34, 0x49, 0x35, 0xa4, 0x5c, 0xc2, 0x12, 0x7e, 0xc5, 0x6c,
	0x87, 0x42, 0x09, 0xaf, 0xf1, 0xbd, 0x60, 0x5b, 0xd3, 0x44, 0x33, 0xd1, 0x83, 0xb2, 0x7b, 0xf5,
	0x34, 0x46, 0x9f, 0x1c, 0x8d, 0x9d, 0x06, 0xa9, 0x08, 0xaa, 0x61, 0xc9, 0x69, 0x91, 0x5a, 0x44,
	0xc3, 0x1e, 0x85, 0x92, 0x7b, 0x8d, 0xb4, 0x0c, 0x63, 0xe3, 0xd0, 0x24, 0xd5, 0xa4, 0x2f, 0xd1,
	0xa3, 0x4d, 0x1a, 0xdd, 0x81, 0x1e, 0x28, 0x9a, 0x40, 0xc9, 0xfd, 0x88, 0x34, 0x83, 0xe3, 0xd9,
	0x6c, 0x3c, 0xd9, 0x3b, 0xc1, 0x1c, 0xbe, 0x0e, 0x60, 0x09, 0x3f, 0x06, 0x49, 0x08, 0x25, 0xfc,
	0xa0, 0x3a, 0x82, 0x32, 0x7e, 0xc4, 0x3a, 0x80, 0x8a, 0xf1, 0x09, 0x22, 0xa8, 0xda, 0xa3, 0x00,
	0x6a, 0xee, 0x8f, 0x25, 0xd2, 0xe8, 0xcf, 0xa6, 0xfb, 0xc7, 0x7b, 0x73, 0xf3, 0x42, 0x1d, 0xa4,
	0x18, 0x6c, 0xee, 0xa1, 0x3a, 0x4a, 0x31, 0x65, 0x29, 0x37, 0xf0, 0xa4, 0x8c, 0x46, 0x9c, 0xb9,
	0x55, 0x72, 0x03, 0xdd, 0xaa, 0xb9, 0x81, 0x97, 0xd6, 0x4c, 0xb6, 0xc0, 0xc6, 0xd4, 0x73, 0x03,
	0xdd, 0x1a, 0xb9, 0x81, 0x6e, 0x4d, 0x9b, 0xda, 0x66, 0x6b, 0xe5, 0x06, 0xba, 0x91, 0xdc, 0x40,
	0xb7, 0xb6, 0xfb, 0xb0, 0x44, 0x88, 0x9c, 0xed, 0x8f, 0x67, 0xc9, 0x7c, 0x34, 0x1f, 0xe3, 0x59,
	0xa2, 0x3d, 0xa5, 0x29, 0x52, 0x25, 0xa4, 0xde, 0x8f, 0xbd, 0x80, 0xe2, 0x9b, 0x97, 0x49, 0x33,
	0xc0, 0x1e, 0xc5, 0x34, 0xa3, 0xda, 0xf7, 0x94, 0x66, 0x5e, 0x0c, 0x15, 0x74, 0xeb, 0xb2, 0x18,
	0x0f, 0xaa, 0xe8, 0xa6, 0xe8, 0xc7, 0x34, 0xc0, 0x04, 0x86, 0x2a, 0xdd, 0xed, 0x33, 0x45, 0x91,
	0xea, 0x1a, 0x69, 0x2b, 0xfa, 0xc9, 0x80, 0x26, 0x3a, 0xf5, 0xc2, 0x10, 0x1a, 0x8e, 0x43, 0x56,
	0x73, 0x80, 0xcb, 0x90, 0x75, 0x87, 0xd0, 0x3c, 0x8b, 0xd9, 0xeb, 0xa0, 0xe5, 0x76, 0x08, 0x18,
	0x86, 0xd8, 0xb0, 0xee, 0xc1, 0xe1, 0xe1, 0xc1, 0xe4, 0x73, 0xac, 0x73, 0x57, 0x6e, 0xdb, 0xa6,
	0x30, 0x19, 0x58, 0x81, 0x29, 0xaa, 0x07, 0x4a, 0x40, 0xd9, 0x3d, 0x21, 0x75, 0x35, 0x1e, 0x7d,
	0x31, 0x9d, 0x38, 0x40, 0x96, 0xa5, 0x0a, 0xa9, 0x4a, 0x83, 0x98, 0x51, 0x81, 0x7d, 0x3e, 0x45,
	0xb8, 0xf4, 0x59, 0x8c, 0x22, 0x5a, 0x21, 0x2d, 0x8b, 0xdc, 0xa5, 0x3e, 0x94, 0x91, 0x82, 0x35,
	0x13, 0xad, 0x3c, 0x4d, 0x7b, 0x43, 0xa8, 0xe0, 0xb3, 0x32, 0x2c, 0xb6, 0x8f, 0xb4, 0x96, 0xee,
	0x43, 0xed, 0xcc, 0x99, 0x84, 0xba, 0x1b, 0x90, 0x95, 0x53, 0xb2, 0xfa, 0xe0, 0x9e, 0x91, 0x60,
	0x2f, 0x97, 0x4f, 0xe8, 0x0d, 0xed, 0x7d, 0x49, 0x9f, 0x06, 0xac, 0xcb, 0x4c, 0x2d, 0xcf, 0x91,
	0x95, 0x53, 0x33, 0x45, 0x8f, 0x8a, 0xbb, 0x45, 0x56, 0x4d, 0x12, 0x3a, 0x99, 0xcf, 0x4e, 0x8c,
	0x4e, 0xeb, 0xa4, 0xcc, 0x84, 0x4d, 0x22, 0x07, 0x1a, 0x4a, 0x28, 0x68, 0x26, 0xf0, 0xb3, 0x8c,
	0x2f, 0x97, 0x03, 0x9d, 0xfa, 0x18, 0x79, 0x99, 0x54, 0x93, 0x83, 0x7d, 0x73, 0xab, 0x3f, 0x18,
	0xda, 0x59, 0x49, 0x68, 0x1c, 0x43, 0xc9, 0x8d, 0x49, 0xeb, 0x94, 0x19, 0xc6, 0x70, 0x4f, 0x6d,
	0xe7, 0xb3, 0x11, 0x33, 0xce, 0x30, 0x2b, 0x7a, 0x6b, 0xd9, 0x87, 0xb2, 0xb3, 0x4a, 0x08, 0x7e,
	0xa5, 0xf6, 0xa4, 0x82, 0x76, 0x10, 0xcb, 0x84, 0x89, 0x1e, 0x5e, 0x54, 0x75, 0x7f, 0x2e, 0x91,
	0x66, 0x38, 0x1e, 0x1d, 0x9a, 0x6c, 0xcb, 0xa4, 0xd9, 0x97, 0x09, 0xd3, 0x4c, 0x0a, 0xab, 0x70,
	0xdf, 0x8b, 0xcd, 0x40, 0x9b, 0xb6, 0x04, 0x8a, 0x86, 0x2c, 0x23, 0x1a, 0x44, 0x9e, 0xea, 0xd1,
	0x2c, 0x9f, 0x54, 0x8a, 0x06, 0x26, 0xa8, 0x8a, 0x24, 0x7c, 0x29, 0x06, 0x09, 0xd4, 0xec, 0x11,
	0xe7, 0x2c, 0x49, 0xf0, 0xa8, 0x8e, 0xd9, 0x99, 0xd0, 0x54, 0xd1, 0x44, 0x43, 0x03, 0xfb, 0xe7,
	0x0f, 0x86, 0xe9, 0xa9, 0x18, 0x9b, 0xa6, 0x80, 0x34, 0x8e, 0x9f, 0x43, 0x2d, 0xb3, 0x8c, 0xd8,
	0x0e, 0x0b, 0xa9, 0x08, 0x81, 0xb8, 0x9a, 0xb4, 0xf5, 0x6c, 0xb4, 0x3f, 0xf6, 0xf6, 0xe6, 0x07,
	0xd3, 0x89, 0x5d, 0x24, 0x5e, 0x6c, 0x99, 0xf6, 0xa9, 0x08, 0x71, 0x75, 0xd8, 0xb7, 0xc7, 0xba,
	0x6f, 0x79, 0x66, 0x82, 0xac, 0x58, 0x59, 0x71, 0xb9, 0x43, 0x6d, 0xdf, 0xb1, 0x06, 0x14, 0x2b,
	0x50, 0x73, 0xff, 0xa9, 0x91, 0x86, 0x1a, 0xcf, 0xf7, 0x70, 0x37, 0xb5, 0x49, 0xc3, 0xca, 0x7e,
	0xd7, 0x8e, 0x8d, 0x35, 0xb2, 0x27, 0x5b, 0x1d, 0x57, 0x90, 0xb9, 0x1d, 0xa7, 0x54, 0x2b, 0x2f,
	0xc4, 0x84, 0xc8, 0x44, 0x0a, 0x0a, 0x35, 0x3c, 0xc3, 0xaf, 0x34, 0x9f, 0xaa, 0x3a, 0x16, 0x84,
	0x2a, 0x25, 0x95, 0x9d, 0x6b, 0xcd, 0x38, 0xc5, 0x6e, 0x9b, 0xb9, 0x66, 0x62, 0xc7, 0x8b, 0x19,
	0xbe, 0xd3, 0x21, 0xab, 0x99, 0x91, 0xee, 0xc8, 0x78, 0xc0, 0x29, 0x10, 0x2c, 0x47, 0x8e, 0xf5,
	0x15, 0x0b, 0x28, 0xb4, 0xcf, 0x42, 0xd8, 0xd4, 0x04, 0x96, 0x31, 0xd2, 0xb0, 0x48, 0x43, 0x96,
	0x78, 0x3e, 0x56, 0x6d, 0x05, 0xdd, 0xac, 0x28, 0x52, 0xf3, 0xcc, 0x10, 0x56, 0xf1, 0xc9, 0x42,
	0xa6, 0x5c, 0x0a, 0x3a, 0x84, 0x35, 0x74, 0x30, 0x29, 0xd3, 0x20, 0xf2, 0x44, 0x8f, 0x86, 0x00,
	0x28, 0x66, 0x0b, 0xc9, 0x6e, 0x17, 0xce, 0x39, 0x17, 0x89, 0x93, 0xdf, 0x64, 0x26, 0xdf, 0x33,
	0xed, 0x75, 0x30, 0x32, 0x9b, 0xc3, 0x2c, 0xf2, 0xbc, 0xb3, 0x4e, 0xce, 0x69, 0x29, 0x53, 0xee,
	0x89, 0x61, 0x9a, 0xcd, 0x7c, 0x02, 0xeb, 0xd8, 0x7d, 0x21, 0x33, 0xb7, 0x04, 0x2e, 0x62, 0xc6,
	0x84, 0xaa, 0x1d, 0xaa, 0x72, 0xa6, 0x49, 0xea, 0x69, 0xb8, 0x84, 0xb8, 0x9d, 0xe9, 0x17, 0xf0,
	0x97, 0xb0, 0xe2, 0xb1, 0x0c, 0xb6, 0x69, 0x08, 0x97, 0xcd, 0x66, 0x52, 0xf2, 0x53, 0x2a, 0xe0,
	0x65, 0xac, 0x70, 0xce, 0x0c, 0xb7, 0x15, 0xbc, 0x62, 0x75, 0x26, 0x44, 0x26, 0xc1, 0x2b, 0x66,
	0x0f, 0x88, 0x18, 0xc9, 0x78, 0x31, 0xbc, 0x8a, 0x01, 0x46, 0xfc, 0xa9, 0x21, 0x9e, 0xc0, 0x6b,
	0xcf, 0x91, 0xac, 0xd6, 0xaf, 0x9f, 0x2d, 0xac, 0xf1, 0x82, 0x37, 0x9c, 0xf3, 0x64, 0x2d, 0x9f,
	0x85, 0xbc, 0x8c, 0x57, 0xf1, 0xad, 0x56, 0x39, 0xb6, 0x08, 0x74, 0x97, 0x25, 0x1a, 0xae, 0xa1,
	0xaf, 0x4d, 0x98, 0x47, 0x24, 0xf0, 0x26, 0xe6, 0xb4, 0xf2, 0xc9, 0x37, 0xe0, 0x5b, 0xc8, 0x2c,
	0x96, 0xa2, 0x97, 0x22, 0x3d, 0x78, 0xdb, 0xcc, 0x66, 0x24, 0x95, 0xb6, 0xf6, 0x3b, 0xf9, 0x6c,
	0x52, 0x6b, 0xbf, 0xeb, 0x5c, 0x26, 0xeb, 0xf9, 0x12, 0xbd, 0xcb, 0x74, 0x94, 0x0a, 0x99, 0x6a,
	0xb9, 0x4d, 0x05, 0xbc, 0x77, 0x96, 0xb0, 0x85, 0xde, 0x47, 0x12, 0x39, 0x94, 0x45, 0x81, 0xeb,
	0x3e, 0xab, 0x92, 0x76, 0x6f, 0x36, 0x9a, 0x1c, 0x1f, 0x8e, 0x66, 0x07, 0xf3, 0x13, 0x94, 0x4b,
	0x4f, 0x79, 0x62, 0x10, 0x7b, 0x8a, 0xe9, 0x61, 0xda, 0xe1, 0xb0, 0x54, 0xc4, 0x36, 0x38, 0x7c,
	0x58, 0xc4, 0x36, 0x39, 0x7c, 0xe9, 0x9c, 0x7f, 0x11, 0xbb, 0xce, 0xe1, 0xd7, 0x52, 0x11, 0xbc,
	0xc1, 0xe1, 0xe9, 0x02, 0x78, 0x93, 0xc3, 0x2f, 0xe5, 0x22, 0x78, 0x8b, 0xc3, 0x7f, 0x0b, 0xe0,
	0x6d, 0x0e, 0x3f, 0x54, 0x8a, 0xe0, 0x16, 0x87, 0x27, 0x0b, 0xe0, 0x1d, 0x0e, 0xdf, 0x55, 0x9d,
	0x0b, 0x64, 0xed, 0x05, 0xea, 0x1d, 0x0e, 0x7f, 0x2f, 0xa2, 0x37, 0x39, 0x7c, 0xd5, 0x28, 0xa2,
	0x9b, 0x1d, 0x0e, 0x8f, 0x5a, 0x45, 0xf4, 0x7a, 0x87, 0xc3, 0xd7, 0xab, 0x45, 0xf4, 0x46, 0x87,
	0xc3, 0x13, 0xa7, 0x88, 0xde, 0xec, 0x70, 0xf8, 0xfd, 0x52, 0x91, 0xd8, 0x46, 0x04, 0x0f, 0xae,
	0x14, 0xc1, 0xcd, 0x08, 0x1e, 0x6e, 0x2d, 0x14, 0x30, 0x82, 0x47, 0x7a, 0xa1, 0x80, 0x11, 0x3c,
	0x3e, 0x72, 0x2e, 0x14, 0x0a, 0x18, 0xc1, 0x9f, 0xdf, 0x94, 0x8a, 0xe8, 0xad, 0x08, 0x9e, 0xfc,
	0xb4, 0x80, 0xde, 0x8e, 0xe0, 0xe9, 0x1f, 0x0b, 0xe8, 0x56, 0x04, 0xf7, 0xff, 0x5d, 0x40, 0xef,
	0x44, 0xf0, 0xe0, 0x59, 0xc9, 0x59, 0x2f, 0x56, 0x31, 0x82, 0x87, 0xdf, 0x96, 0x17, 0xe0, 0x8d,
	0x08, 0x1e, 0xfd, 0xb6, 0x08, 0x6f, 0x46, 0xf0, 0xf8, 0xaf, 0x72, 0x31, 0xf5, 0x46, 0x08, 0xf7,
	0xbf, 0xaf, 0xb9, 0x1d, 0xb2, 0x12, 0x8c, 0x26, 0xfb, 0x87, 0xe3, 0xde, 0x6c, 0x7a, 0x7c, 0xe4,
	0x9f, 0xe0, 0xaa, 0xc4, 0x1d, 0x68, 0xd7, 0x6b, 0x36, 0x7f, 0xe6, 0x57, 0xd0, 0xee, 0xd2, 0xf2,
	0x67, 0x75, 0xf3, 0xa7, 0xf4, 0xfa, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x13, 0x3d, 0x91,
	0xa2, 0x0a, 0x00, 0x00,
}
