// Code generated by protoc-gen-go. DO NOT EDIT.
// source: marketdata.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Market Data
type Item struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Volume               float64  `protobuf:"fixed64,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b85761666e9c8c, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Item) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Orderbook struct {
	Product              string   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Venue                string   `protobuf:"bytes,2,opt,name=venue,proto3" json:"venue,omitempty"`
	SystemTimestamp      string   `protobuf:"bytes,3,opt,name=system_timestamp,json=systemTimestamp,proto3" json:"system_timestamp,omitempty"`
	VenueTimestamp       string   `protobuf:"bytes,4,opt,name=venue_timestamp,json=venueTimestamp,proto3" json:"venue_timestamp,omitempty"`
	Levels               int64    `protobuf:"varint,5,opt,name=levels,proto3" json:"levels,omitempty"`
	Asks                 []*Item  `protobuf:"bytes,6,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids                 []*Item  `protobuf:"bytes,7,rep,name=bids,proto3" json:"bids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Orderbook) Reset()         { *m = Orderbook{} }
func (m *Orderbook) String() string { return proto.CompactTextString(m) }
func (*Orderbook) ProtoMessage()    {}
func (*Orderbook) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b85761666e9c8c, []int{1}
}

func (m *Orderbook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orderbook.Unmarshal(m, b)
}
func (m *Orderbook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orderbook.Marshal(b, m, deterministic)
}
func (m *Orderbook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orderbook.Merge(m, src)
}
func (m *Orderbook) XXX_Size() int {
	return xxx_messageInfo_Orderbook.Size(m)
}
func (m *Orderbook) XXX_DiscardUnknown() {
	xxx_messageInfo_Orderbook.DiscardUnknown(m)
}

var xxx_messageInfo_Orderbook proto.InternalMessageInfo

func (m *Orderbook) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *Orderbook) GetVenue() string {
	if m != nil {
		return m.Venue
	}
	return ""
}

func (m *Orderbook) GetSystemTimestamp() string {
	if m != nil {
		return m.SystemTimestamp
	}
	return ""
}

func (m *Orderbook) GetVenueTimestamp() string {
	if m != nil {
		return m.VenueTimestamp
	}
	return ""
}

func (m *Orderbook) GetLevels() int64 {
	if m != nil {
		return m.Levels
	}
	return 0
}

func (m *Orderbook) GetAsks() []*Item {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *Orderbook) GetBids() []*Item {
	if m != nil {
		return m.Bids
	}
	return nil
}

type Trade struct {
	Product              string   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Venue                string   `protobuf:"bytes,2,opt,name=venue,proto3" json:"venue,omitempty"`
	SystemTimestamp      string   `protobuf:"bytes,3,opt,name=system_timestamp,json=systemTimestamp,proto3" json:"system_timestamp,omitempty"`
	VenueTimestamp       string   `protobuf:"bytes,4,opt,name=venue_timestamp,json=venueTimestamp,proto3" json:"venue_timestamp,omitempty"`
	Price                float64  `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Volume               float64  `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	OrderSide            Side     `protobuf:"varint,7,opt,name=order_side,json=orderSide,proto3,enum=api.Side" json:"order_side,omitempty"`
	Asks                 []*Item  `protobuf:"bytes,9,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids                 []*Item  `protobuf:"bytes,10,rep,name=bids,proto3" json:"bids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b85761666e9c8c, []int{2}
}

func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *Trade) GetVenue() string {
	if m != nil {
		return m.Venue
	}
	return ""
}

func (m *Trade) GetSystemTimestamp() string {
	if m != nil {
		return m.SystemTimestamp
	}
	return ""
}

func (m *Trade) GetVenueTimestamp() string {
	if m != nil {
		return m.VenueTimestamp
	}
	return ""
}

func (m *Trade) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Trade) GetOrderSide() Side {
	if m != nil {
		return m.OrderSide
	}
	return Side_BUY
}

func (m *Trade) GetAsks() []*Item {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *Trade) GetBids() []*Item {
	if m != nil {
		return m.Bids
	}
	return nil
}

type Ticker struct {
	Product              string   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Venue                string   `protobuf:"bytes,2,opt,name=venue,proto3" json:"venue,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	OrderSide            Side     `protobuf:"varint,5,opt,name=order_side,json=orderSide,proto3,enum=api.Side" json:"order_side,omitempty"`
	BestBid              float64  `protobuf:"fixed64,6,opt,name=best_bid,json=bestBid,proto3" json:"best_bid,omitempty"`
	BestAsk              float64  `protobuf:"fixed64,7,opt,name=best_ask,json=bestAsk,proto3" json:"best_ask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticker) Reset()         { *m = Ticker{} }
func (m *Ticker) String() string { return proto.CompactTextString(m) }
func (*Ticker) ProtoMessage()    {}
func (*Ticker) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b85761666e9c8c, []int{3}
}

func (m *Ticker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticker.Unmarshal(m, b)
}
func (m *Ticker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticker.Marshal(b, m, deterministic)
}
func (m *Ticker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticker.Merge(m, src)
}
func (m *Ticker) XXX_Size() int {
	return xxx_messageInfo_Ticker.Size(m)
}
func (m *Ticker) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticker.DiscardUnknown(m)
}

var xxx_messageInfo_Ticker proto.InternalMessageInfo

func (m *Ticker) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *Ticker) GetVenue() string {
	if m != nil {
		return m.Venue
	}
	return ""
}

func (m *Ticker) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Ticker) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Ticker) GetOrderSide() Side {
	if m != nil {
		return m.OrderSide
	}
	return Side_BUY
}

func (m *Ticker) GetBestBid() float64 {
	if m != nil {
		return m.BestBid
	}
	return 0
}

func (m *Ticker) GetBestAsk() float64 {
	if m != nil {
		return m.BestAsk
	}
	return 0
}

type Candle struct {
	Venue                string   `protobuf:"bytes,1,opt,name=venue,proto3" json:"venue,omitempty"`
	Product              string   `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Granularity          int64    `protobuf:"varint,3,opt,name=granularity,proto3" json:"granularity,omitempty"`
	Point                int64    `protobuf:"varint,4,opt,name=point,proto3" json:"point,omitempty"`
	Open                 float64  `protobuf:"fixed64,5,opt,name=open,proto3" json:"open,omitempty"`
	Close                float64  `protobuf:"fixed64,6,opt,name=close,proto3" json:"close,omitempty"`
	High                 float64  `protobuf:"fixed64,7,opt,name=high,proto3" json:"high,omitempty"`
	Low                  float64  `protobuf:"fixed64,8,opt,name=low,proto3" json:"low,omitempty"`
	Volume               float64  `protobuf:"fixed64,9,opt,name=volume,proto3" json:"volume,omitempty"`
	Total                float64  `protobuf:"fixed64,10,opt,name=total,proto3" json:"total,omitempty"`
	TotalTrades          int64    `protobuf:"varint,11,opt,name=total_trades,json=totalTrades,proto3" json:"total_trades,omitempty"`
	BuyTotal             int64    `protobuf:"varint,12,opt,name=buy_total,json=buyTotal,proto3" json:"buy_total,omitempty"`
	SellTotal            int64    `protobuf:"varint,13,opt,name=sell_total,json=sellTotal,proto3" json:"sell_total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candle) Reset()         { *m = Candle{} }
func (m *Candle) String() string { return proto.CompactTextString(m) }
func (*Candle) ProtoMessage()    {}
func (*Candle) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b85761666e9c8c, []int{4}
}

func (m *Candle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candle.Unmarshal(m, b)
}
func (m *Candle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candle.Marshal(b, m, deterministic)
}
func (m *Candle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candle.Merge(m, src)
}
func (m *Candle) XXX_Size() int {
	return xxx_messageInfo_Candle.Size(m)
}
func (m *Candle) XXX_DiscardUnknown() {
	xxx_messageInfo_Candle.DiscardUnknown(m)
}

var xxx_messageInfo_Candle proto.InternalMessageInfo

func (m *Candle) GetVenue() string {
	if m != nil {
		return m.Venue
	}
	return ""
}

func (m *Candle) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *Candle) GetGranularity() int64 {
	if m != nil {
		return m.Granularity
	}
	return 0
}

func (m *Candle) GetPoint() int64 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *Candle) GetOpen() float64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *Candle) GetClose() float64 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *Candle) GetHigh() float64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *Candle) GetLow() float64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *Candle) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Candle) GetTotal() float64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Candle) GetTotalTrades() int64 {
	if m != nil {
		return m.TotalTrades
	}
	return 0
}

func (m *Candle) GetBuyTotal() int64 {
	if m != nil {
		return m.BuyTotal
	}
	return 0
}

func (m *Candle) GetSellTotal() int64 {
	if m != nil {
		return m.SellTotal
	}
	return 0
}

func init() {
	proto.RegisterType((*Item)(nil), "api.Item")
	proto.RegisterType((*Orderbook)(nil), "api.Orderbook")
	proto.RegisterType((*Trade)(nil), "api.Trade")
	proto.RegisterType((*Ticker)(nil), "api.Ticker")
	proto.RegisterType((*Candle)(nil), "api.Candle")
}

func init() { proto.RegisterFile("marketdata.proto", fileDescriptor_e6b85761666e9c8c) }

var fileDescriptor_e6b85761666e9c8c = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xcb, 0x8e, 0xd3, 0x30,
	0x14, 0x55, 0x92, 0x36, 0x6d, 0x6e, 0x87, 0x4e, 0x65, 0xa1, 0x91, 0x79, 0x8c, 0x54, 0xba, 0xa1,
	0x6c, 0xba, 0x80, 0x2f, 0xe0, 0xb1, 0x61, 0x85, 0x14, 0xba, 0x8f, 0x9c, 0xda, 0x9a, 0xb1, 0xe2,
	0xc4, 0x91, 0xed, 0x14, 0xf5, 0x73, 0xf8, 0x1f, 0xf8, 0x0c, 0xfe, 0x03, 0xf9, 0x3a, 0x6d, 0x53,
	0x40, 0x23, 0xb1, 0x9b, 0xdd, 0x3d, 0xe7, 0x5e, 0x5b, 0xf7, 0x9c, 0xe3, 0x04, 0x16, 0x35, 0x33,
	0x95, 0x70, 0x9c, 0x39, 0xb6, 0x69, 0x8d, 0x76, 0x9a, 0x24, 0xac, 0x95, 0xcf, 0x41, 0x34, 0x5d,
	0x1d, 0x88, 0xd5, 0x27, 0x18, 0x7d, 0x76, 0xa2, 0x26, 0x73, 0x88, 0x25, 0xa7, 0xd1, 0x32, 0x5a,
	0x27, 0x79, 0x2c, 0x39, 0xb9, 0x81, 0x74, 0xaf, 0x55, 0x57, 0x0b, 0x1a, 0x2f, 0xa3, 0x75, 0x94,
	0xf7, 0x88, 0x3c, 0x85, 0x71, 0x6b, 0xe4, 0x4e, 0xd0, 0x04, 0xe9, 0x00, 0x56, 0xbf, 0x22, 0xc8,
	0xbe, 0x18, 0x2e, 0x4c, 0xa9, 0x75, 0x45, 0x28, 0x4c, 0x5a, 0xa3, 0x79, 0xb7, 0x73, 0x78, 0x61,
	0x96, 0x1f, 0xa1, 0x3f, 0xbd, 0x17, 0x4d, 0x17, 0x2e, 0xcd, 0xf2, 0x00, 0xc8, 0x1b, 0x58, 0xd8,
	0x83, 0x75, 0xa2, 0x2e, 0x9c, 0xac, 0x85, 0x75, 0xac, 0x6e, 0xf1, 0xfa, 0x2c, 0xbf, 0x0e, 0xfc,
	0xf6, 0x48, 0x93, 0xd7, 0x70, 0x8d, 0x67, 0x06, 0x93, 0x23, 0x9c, 0x9c, 0x23, 0x7d, 0x1e, 0xbc,
	0x81, 0x54, 0x89, 0xbd, 0x50, 0x96, 0x8e, 0x51, 0x53, 0x8f, 0xc8, 0x2d, 0x8c, 0x98, 0xad, 0x2c,
	0x4d, 0x97, 0xc9, 0x7a, 0xf6, 0x36, 0xdb, 0xb0, 0x56, 0x6e, 0xbc, 0x01, 0x39, 0xd2, 0xbe, 0x5d,
	0x4a, 0x6e, 0xe9, 0xe4, 0xaf, 0xb6, 0xa7, 0x57, 0xdf, 0x63, 0x18, 0x6f, 0x0d, 0xe3, 0xe2, 0x51,
	0x68, 0x3c, 0x65, 0x31, 0x1e, 0x64, 0x31, 0x48, 0x2e, 0xbd, 0x48, 0x6e, 0x0d, 0xa0, 0x7d, 0x44,
	0x85, 0x95, 0x5c, 0xd0, 0xc9, 0x32, 0x5a, 0xcf, 0x7b, 0x81, 0x5f, 0x25, 0x17, 0x79, 0x86, 0x4d,
	0x5f, 0x9e, 0x3c, 0xca, 0x1e, 0xf6, 0x08, 0xfe, 0xed, 0xd1, 0x8f, 0x08, 0xd2, 0xad, 0xdc, 0x55,
	0xc2, 0xfc, 0xb7, 0x49, 0x2f, 0x21, 0xbb, 0x74, 0x27, 0xc9, 0xcf, 0xc4, 0x59, 0xee, 0x68, 0x28,
	0xf7, 0x52, 0xd6, 0xf8, 0x01, 0x59, 0xcf, 0x60, 0x5a, 0x0a, 0xeb, 0x8a, 0x52, 0xf2, 0xde, 0x9a,
	0x89, 0xc7, 0x1f, 0x24, 0x3f, 0xb5, 0x98, 0xad, 0xd0, 0x99, 0xbe, 0xf5, 0xde, 0x56, 0xab, 0x9f,
	0x31, 0xa4, 0x1f, 0x59, 0xc3, 0x95, 0x38, 0x2f, 0x1d, 0x0d, 0x97, 0x1e, 0x88, 0x8c, 0x2f, 0x45,
	0x2e, 0x61, 0x76, 0x67, 0x58, 0xd3, 0x29, 0x66, 0xa4, 0x3b, 0xf4, 0x82, 0x86, 0x14, 0x4a, 0xd2,
	0xb2, 0x71, 0x28, 0x29, 0xc9, 0x03, 0x20, 0x04, 0x46, 0xba, 0x15, 0x4d, 0x1f, 0x2b, 0xd6, 0x7e,
	0x72, 0xa7, 0xb4, 0x3d, 0x86, 0x1a, 0x80, 0x9f, 0xbc, 0x97, 0x77, 0xf7, 0xfd, 0xce, 0x58, 0x93,
	0x05, 0x24, 0x4a, 0x7f, 0xa3, 0x53, 0xa4, 0x7c, 0x39, 0x78, 0x11, 0xd9, 0x9f, 0xdf, 0xb2, 0xd3,
	0x8e, 0x29, 0x0a, 0xe1, 0x4e, 0x04, 0xe4, 0x15, 0x5c, 0x61, 0x51, 0x38, 0xff, 0xd0, 0x2d, 0x9d,
	0x85, 0xb5, 0x91, 0xc3, 0xb7, 0x6f, 0xc9, 0x0b, 0xc8, 0xca, 0xee, 0x50, 0x84, 0xc3, 0x57, 0xd8,
	0x9f, 0x96, 0xdd, 0x61, 0x8b, 0xe7, 0x6f, 0x01, 0xac, 0x50, 0xaa, 0xef, 0x3e, 0x09, 0x29, 0x7a,
	0x06, 0xdb, 0x65, 0x8a, 0xff, 0x9d, 0x77, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x54, 0x80,
	0xa9, 0x9c, 0x04, 0x00, 0x00,
}
