// Code generated by protoc-gen-go. DO NOT EDIT.
// source: products.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	ProductId              int32    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VenueId                int32    `protobuf:"varint,2,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Kind                   string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	BaseCurrency           int32    `protobuf:"varint,4,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	QuoteCurrency          int32    `protobuf:"varint,5,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	SystemSymbolIdentifier string   `protobuf:"bytes,6,opt,name=system_symbol_identifier,json=systemSymbolIdentifier,proto3" json:"system_symbol_identifier,omitempty"`
	IndividualConnection   bool     `protobuf:"varint,7,opt,name=individual_connection,json=individualConnection,proto3" json:"individual_connection,omitempty"`
	StreamingSave          bool     `protobuf:"varint,8,opt,name=streaming_save,json=streamingSave,proto3" json:"streaming_save,omitempty"`
	VenueSymbolIdentifier  string   `protobuf:"bytes,9,opt,name=venue_symbol_identifier,json=venueSymbolIdentifier,proto3" json:"venue_symbol_identifier,omitempty"`
	MinimumOrdersSize      float64  `protobuf:"fixed64,10,opt,name=minimum_orders_size,json=minimumOrdersSize,proto3" json:"minimum_orders_size,omitempty"`
	StepSize               float64  `protobuf:"fixed64,11,opt,name=step_size,json=stepSize,proto3" json:"step_size,omitempty"`
	PricePrecision         int32    `protobuf:"varint,12,opt,name=price_precision,json=pricePrecision,proto3" json:"price_precision,omitempty"`
	MakerFee               float64  `protobuf:"fixed64,13,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`
	TakerFee               float64  `protobuf:"fixed64,14,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	Enabled                bool     `protobuf:"varint,15,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Settlement             string   `protobuf:"bytes,16,opt,name=settlement,proto3" json:"settlement,omitempty"`
	Expiration             string   `protobuf:"bytes,17,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *Product) GetVenueId() int32 {
	if m != nil {
		return m.VenueId
	}
	return 0
}

func (m *Product) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Product) GetBaseCurrency() int32 {
	if m != nil {
		return m.BaseCurrency
	}
	return 0
}

func (m *Product) GetQuoteCurrency() int32 {
	if m != nil {
		return m.QuoteCurrency
	}
	return 0
}

func (m *Product) GetSystemSymbolIdentifier() string {
	if m != nil {
		return m.SystemSymbolIdentifier
	}
	return ""
}

func (m *Product) GetIndividualConnection() bool {
	if m != nil {
		return m.IndividualConnection
	}
	return false
}

func (m *Product) GetStreamingSave() bool {
	if m != nil {
		return m.StreamingSave
	}
	return false
}

func (m *Product) GetVenueSymbolIdentifier() string {
	if m != nil {
		return m.VenueSymbolIdentifier
	}
	return ""
}

func (m *Product) GetMinimumOrdersSize() float64 {
	if m != nil {
		return m.MinimumOrdersSize
	}
	return 0
}

func (m *Product) GetStepSize() float64 {
	if m != nil {
		return m.StepSize
	}
	return 0
}

func (m *Product) GetPricePrecision() int32 {
	if m != nil {
		return m.PricePrecision
	}
	return 0
}

func (m *Product) GetMakerFee() float64 {
	if m != nil {
		return m.MakerFee
	}
	return 0
}

func (m *Product) GetTakerFee() float64 {
	if m != nil {
		return m.TakerFee
	}
	return 0
}

func (m *Product) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Product) GetSettlement() string {
	if m != nil {
		return m.Settlement
	}
	return ""
}

func (m *Product) GetExpiration() string {
	if m != nil {
		return m.Expiration
	}
	return ""
}

type ProductRequest struct {
	Token                string      `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ProductId            string      `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 AccountMode `protobuf:"varint,3,opt,name=name,proto3,enum=api.AccountMode" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProductRequest) Reset()         { *m = ProductRequest{} }
func (m *ProductRequest) String() string { return proto.CompactTextString(m) }
func (*ProductRequest) ProtoMessage()    {}
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{1}
}
func (m *ProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductRequest.Unmarshal(m, b)
}
func (m *ProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductRequest.Marshal(b, m, deterministic)
}
func (dst *ProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductRequest.Merge(dst, src)
}
func (m *ProductRequest) XXX_Size() int {
	return xxx_messageInfo_ProductRequest.Size(m)
}
func (m *ProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductRequest proto.InternalMessageInfo

func (m *ProductRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ProductRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductRequest) GetName() AccountMode {
	if m != nil {
		return m.Name
	}
	return AccountMode_DEMO
}

type ProductResponse struct {
	Retcode              Retcode    `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Currencies           []*Product `protobuf:"bytes,2,rep,name=currencies,proto3" json:"currencies,omitempty"`
	Comment              string     `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Elapsed              string     `protobuf:"bytes,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProductResponse) Reset()         { *m = ProductResponse{} }
func (m *ProductResponse) String() string { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()    {}
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{2}
}
func (m *ProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductResponse.Unmarshal(m, b)
}
func (m *ProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductResponse.Marshal(b, m, deterministic)
}
func (dst *ProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductResponse.Merge(dst, src)
}
func (m *ProductResponse) XXX_Size() int {
	return xxx_messageInfo_ProductResponse.Size(m)
}
func (m *ProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductResponse proto.InternalMessageInfo

func (m *ProductResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *ProductResponse) GetCurrencies() []*Product {
	if m != nil {
		return m.Currencies
	}
	return nil
}

func (m *ProductResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ProductResponse) GetElapsed() string {
	if m != nil {
		return m.Elapsed
	}
	return ""
}

type ProductPostRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Product              *Product `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Action               Action   `protobuf:"varint,3,opt,name=action,proto3,enum=api.Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductPostRequest) Reset()         { *m = ProductPostRequest{} }
func (m *ProductPostRequest) String() string { return proto.CompactTextString(m) }
func (*ProductPostRequest) ProtoMessage()    {}
func (*ProductPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{3}
}
func (m *ProductPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductPostRequest.Unmarshal(m, b)
}
func (m *ProductPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductPostRequest.Marshal(b, m, deterministic)
}
func (dst *ProductPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductPostRequest.Merge(dst, src)
}
func (m *ProductPostRequest) XXX_Size() int {
	return xxx_messageInfo_ProductPostRequest.Size(m)
}
func (m *ProductPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductPostRequest proto.InternalMessageInfo

func (m *ProductPostRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ProductPostRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *ProductPostRequest) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_INSERT
}

type ProductPostResponse struct {
	Retcode              Retcode  `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Elapsed              string   `protobuf:"bytes,3,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductPostResponse) Reset()         { *m = ProductPostResponse{} }
func (m *ProductPostResponse) String() string { return proto.CompactTextString(m) }
func (*ProductPostResponse) ProtoMessage()    {}
func (*ProductPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{4}
}
func (m *ProductPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductPostResponse.Unmarshal(m, b)
}
func (m *ProductPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductPostResponse.Marshal(b, m, deterministic)
}
func (dst *ProductPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductPostResponse.Merge(dst, src)
}
func (m *ProductPostResponse) XXX_Size() int {
	return xxx_messageInfo_ProductPostResponse.Size(m)
}
func (m *ProductPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductPostResponse proto.InternalMessageInfo

func (m *ProductPostResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *ProductPostResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ProductPostResponse) GetElapsed() string {
	if m != nil {
		return m.Elapsed
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "api.Product")
	proto.RegisterType((*ProductRequest)(nil), "api.ProductRequest")
	proto.RegisterType((*ProductResponse)(nil), "api.ProductResponse")
	proto.RegisterType((*ProductPostRequest)(nil), "api.ProductPostRequest")
	proto.RegisterType((*ProductPostResponse)(nil), "api.ProductPostResponse")
}

func init() { proto.RegisterFile("products.proto", fileDescriptor_8c6e54f42122eb82) }

var fileDescriptor_8c6e54f42122eb82 = []byte{
	// 580 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x95, 0xb6, 0x5b, 0xdb, 0xdb, 0x9a, 0x6d, 0xde, 0x06, 0x06, 0x04, 0xaa, 0x3a, 0x18,
	0x7d, 0x40, 0x7d, 0xd8, 0x24, 0xc4, 0x2b, 0x9a, 0x84, 0xb4, 0x07, 0xc4, 0x94, 0x7d, 0x80, 0xc8,
	0x8d, 0x6f, 0xc8, 0x6a, 0x63, 0x67, 0xb6, 0x53, 0xe8, 0xbe, 0x0a, 0x1f, 0x95, 0x17, 0x94, 0x73,
	0x92, 0x75, 0x9b, 0x10, 0xe2, 0xad, 0xfe, 0xff, 0xfe, 0xf1, 0xdd, 0xfd, 0x75, 0x2e, 0xc4, 0x85,
	0x35, 0xb2, 0xcc, 0xbc, 0x9b, 0x15, 0xd6, 0x78, 0xc3, 0xba, 0xa2, 0x50, 0x2f, 0x01, 0x75, 0x99,
	0x07, 0x61, 0xf2, 0xbb, 0x07, 0xfd, 0xab, 0xe0, 0x61, 0xaf, 0x01, 0x6a, 0x7b, 0xaa, 0x24, 0x8f,
	0xc6, 0xd1, 0x74, 0x2b, 0x19, 0xd6, 0xca, 0xa5, 0x64, 0x2f, 0x60, 0xb0, 0x42, 0x5d, 0x62, 0x05,
	0x3b, 0x04, 0xfb, 0x74, 0xbe, 0x94, 0x8c, 0x41, 0x6f, 0xa1, 0xb4, 0xe4, 0xdd, 0x71, 0x34, 0x1d,
	0x26, 0xf4, 0x9b, 0x9d, 0xc0, 0x68, 0x2e, 0x1c, 0xa6, 0x59, 0x69, 0x2d, 0xea, 0x6c, 0xcd, 0x7b,
	0xf4, 0xcd, 0x6e, 0x25, 0x5e, 0xd4, 0x1a, 0x7b, 0x07, 0xf1, 0x6d, 0x69, 0xfc, 0x86, 0x6b, 0x8b,
	0x5c, 0x23, 0x52, 0x5b, 0xdb, 0x27, 0xe0, 0x6e, 0xed, 0x3c, 0xe6, 0xa9, 0x5b, 0xe7, 0x73, 0xb3,
	0x4c, 0x95, 0x44, 0xed, 0xd5, 0x8d, 0x42, 0xcb, 0xb7, 0xa9, 0xe6, 0xb3, 0xc0, 0xaf, 0x09, 0x5f,
	0xb6, 0x94, 0x9d, 0xc3, 0xb1, 0xd2, 0x52, 0xad, 0x94, 0x2c, 0xc5, 0x32, 0xcd, 0x8c, 0xd6, 0x98,
	0x79, 0x65, 0x34, 0xef, 0x8f, 0xa3, 0xe9, 0x20, 0x39, 0xba, 0x87, 0x17, 0x2d, 0xab, 0xba, 0x72,
	0xde, 0xa2, 0xc8, 0x95, 0xfe, 0x9e, 0x3a, 0xb1, 0x42, 0x3e, 0x20, 0xf7, 0xa8, 0x55, 0xaf, 0xc5,
	0x0a, 0xd9, 0x47, 0x78, 0x1e, 0x02, 0x79, 0xda, 0xd4, 0x90, 0x9a, 0x3a, 0x26, 0xfc, 0xa4, 0xa7,
	0x19, 0x1c, 0xe6, 0x4a, 0xab, 0xbc, 0xcc, 0x53, 0x63, 0x25, 0x5a, 0x97, 0x3a, 0x75, 0x87, 0x1c,
	0xc6, 0xd1, 0x34, 0x4a, 0x0e, 0x6a, 0xf4, 0x8d, 0xc8, 0xb5, 0xba, 0x43, 0xf6, 0x0a, 0x86, 0xce,
	0x63, 0x11, 0x5c, 0x3b, 0xe4, 0x1a, 0x54, 0x02, 0xc1, 0xf7, 0xb0, 0x57, 0x58, 0x95, 0x61, 0x5a,
	0x58, 0xcc, 0x94, 0xab, 0x46, 0xdb, 0xa5, 0x08, 0x63, 0x92, 0xaf, 0x1a, 0xb5, 0xba, 0x25, 0x17,
	0x0b, 0xb4, 0xe9, 0x0d, 0x22, 0x1f, 0x85, 0x5b, 0x48, 0xf8, 0x82, 0x54, 0xc2, 0xb7, 0x30, 0x0e,
	0xd0, 0x37, 0x90, 0x43, 0x1f, 0xb5, 0x98, 0x2f, 0x51, 0xf2, 0x3d, 0xca, 0xa1, 0x39, 0xb2, 0x37,
	0x00, 0x0e, 0xbd, 0x5f, 0x62, 0x8e, 0xda, 0xf3, 0x7d, 0x1a, 0x7a, 0x43, 0xa9, 0x38, 0xfe, 0x2c,
	0x94, 0x15, 0x14, 0xf9, 0x41, 0xe0, 0xf7, 0xca, 0x64, 0x01, 0x71, 0xbd, 0x7c, 0x09, 0xde, 0x96,
	0xe8, 0x3c, 0x3b, 0x82, 0x2d, 0x6f, 0x16, 0xa8, 0x69, 0xfd, 0x86, 0x49, 0x38, 0x3c, 0xda, 0xcc,
	0x0e, 0xa1, 0x8d, 0xcd, 0x7c, 0x0b, 0x3d, 0x2d, 0x72, 0xa4, 0xf5, 0x8b, 0xcf, 0xf6, 0x67, 0xa2,
	0x50, 0xb3, 0xcf, 0x59, 0x66, 0x4a, 0xed, 0xbf, 0x1a, 0x89, 0x09, 0xd1, 0xc9, 0xaf, 0x08, 0xf6,
	0xda, 0x6a, 0xae, 0x30, 0xda, 0x21, 0x3b, 0x85, 0xbe, 0x45, 0x9f, 0x19, 0x89, 0x54, 0x30, 0x3e,
	0xdb, 0xa5, 0x8f, 0x93, 0xa0, 0x25, 0x0d, 0x64, 0x1f, 0x00, 0xea, 0x0d, 0x55, 0xe8, 0x78, 0x67,
	0xdc, 0x9d, 0xee, 0xd4, 0xd6, 0xe6, 0xc6, 0x0d, 0x5e, 0x05, 0x96, 0x99, 0x9c, 0x32, 0x09, 0x2f,
	0xa2, 0x39, 0x52, 0x94, 0x4b, 0x51, 0x38, 0x94, 0xf4, 0x1c, 0x86, 0x49, 0x73, 0x9c, 0xfc, 0x00,
	0x56, 0x5f, 0x75, 0x65, 0xdc, 0x3f, 0xe2, 0x38, 0x85, 0x7e, 0x3d, 0x3c, 0x65, 0xf1, 0xb8, 0x95,
	0x06, 0xb2, 0x13, 0xd8, 0x16, 0x61, 0xdb, 0x43, 0x32, 0x3b, 0x75, 0x32, 0x95, 0x94, 0xd4, 0x68,
	0x72, 0x0b, 0x87, 0x0f, 0x0a, 0xff, 0x67, 0x32, 0x1b, 0xb3, 0x76, 0xfe, 0x3a, 0x6b, 0xf7, 0xc1,
	0xac, 0xf3, 0x6d, 0xfa, 0xef, 0x39, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x28, 0x53, 0x4e,
	0x9e, 0x04, 0x00, 0x00,
}
