// Code generated by protoc-gen-go. DO NOT EDIT.
// source: products.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	ProductId            int32    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProductDescription   string   `protobuf:"bytes,3,opt,name=product_description,json=productDescription,proto3" json:"product_description,omitempty"`
	MinConfirmation      int32    `protobuf:"varint,4,opt,name=min_confirmation,json=minConfirmation,proto3" json:"min_confirmation,omitempty"`
	Active               bool     `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	TxFee                float64  `protobuf:"fixed64,6,opt,name=tx_fee,json=txFee,proto3" json:"tx_fee,omitempty"`
	CreateDate           string   `protobuf:"bytes,7,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	LastUpdate           string   `protobuf:"bytes,8,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetProductDescription() string {
	if m != nil {
		return m.ProductDescription
	}
	return ""
}

func (m *Product) GetMinConfirmation() int32 {
	if m != nil {
		return m.MinConfirmation
	}
	return 0
}

func (m *Product) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Product) GetTxFee() float64 {
	if m != nil {
		return m.TxFee
	}
	return 0
}

func (m *Product) GetCreateDate() string {
	if m != nil {
		return m.CreateDate
	}
	return ""
}

func (m *Product) GetLastUpdate() string {
	if m != nil {
		return m.LastUpdate
	}
	return ""
}

type ProductRequest struct {
	Token                string      `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ProductId            string      `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 AccountMode `protobuf:"varint,3,opt,name=name,proto3,enum=api.AccountMode" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProductRequest) Reset()         { *m = ProductRequest{} }
func (m *ProductRequest) String() string { return proto.CompactTextString(m) }
func (*ProductRequest) ProtoMessage()    {}
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{1}
}
func (m *ProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductRequest.Unmarshal(m, b)
}
func (m *ProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductRequest.Marshal(b, m, deterministic)
}
func (dst *ProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductRequest.Merge(dst, src)
}
func (m *ProductRequest) XXX_Size() int {
	return xxx_messageInfo_ProductRequest.Size(m)
}
func (m *ProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductRequest proto.InternalMessageInfo

func (m *ProductRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ProductRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductRequest) GetName() AccountMode {
	if m != nil {
		return m.Name
	}
	return AccountMode_DEMO
}

type ProductResponse struct {
	Retcode              Retcode    `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Currencies           []*Product `protobuf:"bytes,2,rep,name=currencies,proto3" json:"currencies,omitempty"`
	Comment              string     `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Elapsed              string     `protobuf:"bytes,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProductResponse) Reset()         { *m = ProductResponse{} }
func (m *ProductResponse) String() string { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()    {}
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{2}
}
func (m *ProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductResponse.Unmarshal(m, b)
}
func (m *ProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductResponse.Marshal(b, m, deterministic)
}
func (dst *ProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductResponse.Merge(dst, src)
}
func (m *ProductResponse) XXX_Size() int {
	return xxx_messageInfo_ProductResponse.Size(m)
}
func (m *ProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductResponse proto.InternalMessageInfo

func (m *ProductResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *ProductResponse) GetCurrencies() []*Product {
	if m != nil {
		return m.Currencies
	}
	return nil
}

func (m *ProductResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ProductResponse) GetElapsed() string {
	if m != nil {
		return m.Elapsed
	}
	return ""
}

type ProductPostRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Product              *Product `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Action               Action   `protobuf:"varint,3,opt,name=action,proto3,enum=api.Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductPostRequest) Reset()         { *m = ProductPostRequest{} }
func (m *ProductPostRequest) String() string { return proto.CompactTextString(m) }
func (*ProductPostRequest) ProtoMessage()    {}
func (*ProductPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{3}
}
func (m *ProductPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductPostRequest.Unmarshal(m, b)
}
func (m *ProductPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductPostRequest.Marshal(b, m, deterministic)
}
func (dst *ProductPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductPostRequest.Merge(dst, src)
}
func (m *ProductPostRequest) XXX_Size() int {
	return xxx_messageInfo_ProductPostRequest.Size(m)
}
func (m *ProductPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductPostRequest proto.InternalMessageInfo

func (m *ProductPostRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ProductPostRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *ProductPostRequest) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_INSERT
}

type ProductPostResponse struct {
	Retcode              Retcode  `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Elapsed              string   `protobuf:"bytes,3,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductPostResponse) Reset()         { *m = ProductPostResponse{} }
func (m *ProductPostResponse) String() string { return proto.CompactTextString(m) }
func (*ProductPostResponse) ProtoMessage()    {}
func (*ProductPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{4}
}
func (m *ProductPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductPostResponse.Unmarshal(m, b)
}
func (m *ProductPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductPostResponse.Marshal(b, m, deterministic)
}
func (dst *ProductPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductPostResponse.Merge(dst, src)
}
func (m *ProductPostResponse) XXX_Size() int {
	return xxx_messageInfo_ProductPostResponse.Size(m)
}
func (m *ProductPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductPostResponse proto.InternalMessageInfo

func (m *ProductPostResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *ProductPostResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ProductPostResponse) GetElapsed() string {
	if m != nil {
		return m.Elapsed
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "api.Product")
	proto.RegisterType((*ProductRequest)(nil), "api.ProductRequest")
	proto.RegisterType((*ProductResponse)(nil), "api.ProductResponse")
	proto.RegisterType((*ProductPostRequest)(nil), "api.ProductPostRequest")
	proto.RegisterType((*ProductPostResponse)(nil), "api.ProductPostResponse")
}

func init() { proto.RegisterFile("products.proto", fileDescriptor_8c6e54f42122eb82) }

var fileDescriptor_8c6e54f42122eb82 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xe1, 0x6a, 0x14, 0x31,
	0x10, 0xc7, 0xd9, 0xbb, 0xde, 0x6d, 0x6f, 0x4e, 0xb6, 0x65, 0xaa, 0xb2, 0x08, 0xe2, 0xb2, 0x4a,
	0x59, 0x41, 0x4e, 0x38, 0x9f, 0x40, 0x2c, 0x82, 0x1f, 0x84, 0x12, 0xf0, 0xf3, 0x12, 0x93, 0x29,
	0x84, 0x76, 0x93, 0x34, 0xc9, 0x6a, 0x5f, 0xc1, 0x67, 0xf0, 0x65, 0xe5, 0x92, 0xac, 0x6e, 0x0b,
	0x22, 0x7e, 0xbb, 0xf9, 0xff, 0xff, 0xc9, 0x64, 0x7e, 0x73, 0x0b, 0x95, 0x75, 0x46, 0x8e, 0x22,
	0xf8, 0x9d, 0x75, 0x26, 0x18, 0x5c, 0x72, 0xab, 0x9e, 0x01, 0xe9, 0x71, 0x48, 0x42, 0xfb, 0x63,
	0x01, 0xe5, 0x65, 0xca, 0xe0, 0x73, 0x80, 0x1c, 0xef, 0x95, 0xac, 0x8b, 0xa6, 0xe8, 0x56, 0x6c,
	0x93, 0x95, 0x4f, 0x12, 0x11, 0x8e, 0x34, 0x1f, 0xa8, 0x5e, 0x34, 0x45, 0xb7, 0x61, 0xf1, 0x37,
	0xbe, 0x85, 0xb3, 0xe9, 0x88, 0x24, 0x2f, 0x9c, 0xb2, 0x41, 0x19, 0x5d, 0x2f, 0x63, 0x04, 0xb3,
	0x75, 0xf1, 0xc7, 0xc1, 0xd7, 0x70, 0x3a, 0x28, 0xdd, 0x0b, 0xa3, 0xaf, 0x94, 0x1b, 0x78, 0x4c,
	0x1f, 0xc5, 0x4e, 0x27, 0x83, 0xd2, 0x1f, 0x66, 0x32, 0x3e, 0x85, 0x35, 0x17, 0x41, 0x7d, 0xa3,
	0x7a, 0xd5, 0x14, 0xdd, 0x31, 0xcb, 0x15, 0x3e, 0x81, 0x75, 0xb8, 0xeb, 0xaf, 0x88, 0xea, 0x75,
	0x53, 0x74, 0x05, 0x5b, 0x85, 0xbb, 0x8f, 0x44, 0xf8, 0x02, 0xb6, 0xc2, 0x11, 0x0f, 0xd4, 0x4b,
	0x1e, 0xa8, 0x2e, 0xe3, 0x13, 0x20, 0x49, 0x17, 0x3c, 0xc4, 0xc0, 0x0d, 0xf7, 0xa1, 0x1f, 0x6d,
	0x0c, 0x1c, 0xa7, 0xc0, 0x41, 0xfa, 0x12, 0x95, 0xf6, 0x1a, 0xaa, 0x8c, 0x82, 0xd1, 0xed, 0x48,
	0x3e, 0xe0, 0x63, 0x58, 0x05, 0x73, 0x4d, 0x3a, 0xc2, 0xd8, 0xb0, 0x54, 0x3c, 0xe0, 0x94, 0x70,
	0xcc, 0x38, 0xbd, 0xca, 0x9c, 0x0e, 0x10, 0xaa, 0xfd, 0xe9, 0x8e, 0x5b, 0xb5, 0x7b, 0x2f, 0x84,
	0x19, 0x75, 0xf8, 0x6c, 0x24, 0x25, 0x72, 0xed, 0xcf, 0x02, 0x4e, 0x7e, 0x77, 0xf3, 0xd6, 0x68,
	0x4f, 0x78, 0x0e, 0xa5, 0xa3, 0x20, 0x8c, 0xa4, 0xd8, 0xb0, 0xda, 0x3f, 0x8a, 0x87, 0x59, 0xd2,
	0xd8, 0x64, 0xe2, 0x1b, 0x00, 0x31, 0x3a, 0x47, 0x5a, 0x28, 0xf2, 0xf5, 0xa2, 0x59, 0x76, 0xdb,
	0x1c, 0x9d, 0x6e, 0x9c, 0xf9, 0x58, 0x43, 0x29, 0xcc, 0x30, 0x90, 0x0e, 0x79, 0x2f, 0x53, 0x79,
	0x70, 0xe8, 0x86, 0x5b, 0x4f, 0x32, 0xee, 0x60, 0xc3, 0xa6, 0xb2, 0xfd, 0x0e, 0x98, 0xaf, 0xba,
	0x34, 0xfe, 0x1f, 0x38, 0xce, 0xa1, 0xcc, 0xc3, 0x47, 0x16, 0x0f, 0x9f, 0x32, 0x99, 0xf8, 0x32,
	0xed, 0x33, 0xff, 0x3d, 0xaa, 0xfd, 0x36, 0x93, 0x39, 0x48, 0x2c, 0x5b, 0xed, 0x2d, 0x9c, 0xdd,
	0x6b, 0xfc, 0x9f, 0x64, 0x66, 0xb3, 0x2e, 0xfe, 0x3a, 0xeb, 0xf2, 0xde, 0xac, 0x5f, 0xd7, 0xf1,
	0x4b, 0x78, 0xf7, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xa9, 0xad, 0x99, 0x2c, 0x03, 0x00, 0x00,
}
