// Code generated by protoc-gen-go. DO NOT EDIT.
// source: products.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	ProductId             int32    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VenueId               int32    `protobuf:"varint,2,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Kind                  string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	BaseCurrency          int32    `protobuf:"varint,4,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	QuoteCurrency         int32    `protobuf:"varint,5,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	IndividualConnection  bool     `protobuf:"varint,6,opt,name=individual_connection,json=individualConnection,proto3" json:"individual_connection,omitempty"`
	StreamingSave         bool     `protobuf:"varint,7,opt,name=streaming_save,json=streamingSave,proto3" json:"streaming_save,omitempty"`
	VenueSymbolIdentifier string   `protobuf:"bytes,8,opt,name=venue_symbol_identifier,json=venueSymbolIdentifier,proto3" json:"venue_symbol_identifier,omitempty"`
	MinimumOrdersSize     float64  `protobuf:"fixed64,9,opt,name=minimum_orders_size,json=minimumOrdersSize,proto3" json:"minimum_orders_size,omitempty"`
	StepSize              float64  `protobuf:"fixed64,10,opt,name=step_size,json=stepSize,proto3" json:"step_size,omitempty"`
	PricePrecision        int32    `protobuf:"varint,11,opt,name=price_precision,json=pricePrecision,proto3" json:"price_precision,omitempty"`
	MakerFee              float64  `protobuf:"fixed64,12,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`
	TakerFee              float64  `protobuf:"fixed64,13,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	Enabled               bool     `protobuf:"varint,14,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Settlement            string   `protobuf:"bytes,15,opt,name=settlement,proto3" json:"settlement,omitempty"`
	Expiration            string   `protobuf:"bytes,16,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *Product) GetVenueId() int32 {
	if m != nil {
		return m.VenueId
	}
	return 0
}

func (m *Product) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Product) GetBaseCurrency() int32 {
	if m != nil {
		return m.BaseCurrency
	}
	return 0
}

func (m *Product) GetQuoteCurrency() int32 {
	if m != nil {
		return m.QuoteCurrency
	}
	return 0
}

func (m *Product) GetIndividualConnection() bool {
	if m != nil {
		return m.IndividualConnection
	}
	return false
}

func (m *Product) GetStreamingSave() bool {
	if m != nil {
		return m.StreamingSave
	}
	return false
}

func (m *Product) GetVenueSymbolIdentifier() string {
	if m != nil {
		return m.VenueSymbolIdentifier
	}
	return ""
}

func (m *Product) GetMinimumOrdersSize() float64 {
	if m != nil {
		return m.MinimumOrdersSize
	}
	return 0
}

func (m *Product) GetStepSize() float64 {
	if m != nil {
		return m.StepSize
	}
	return 0
}

func (m *Product) GetPricePrecision() int32 {
	if m != nil {
		return m.PricePrecision
	}
	return 0
}

func (m *Product) GetMakerFee() float64 {
	if m != nil {
		return m.MakerFee
	}
	return 0
}

func (m *Product) GetTakerFee() float64 {
	if m != nil {
		return m.TakerFee
	}
	return 0
}

func (m *Product) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Product) GetSettlement() string {
	if m != nil {
		return m.Settlement
	}
	return ""
}

func (m *Product) GetExpiration() string {
	if m != nil {
		return m.Expiration
	}
	return ""
}

type ProductRequest struct {
	Token                string      `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ProductId            string      `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 AccountMode `protobuf:"varint,3,opt,name=name,proto3,enum=api.AccountMode" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProductRequest) Reset()         { *m = ProductRequest{} }
func (m *ProductRequest) String() string { return proto.CompactTextString(m) }
func (*ProductRequest) ProtoMessage()    {}
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{1}
}
func (m *ProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductRequest.Unmarshal(m, b)
}
func (m *ProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductRequest.Marshal(b, m, deterministic)
}
func (dst *ProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductRequest.Merge(dst, src)
}
func (m *ProductRequest) XXX_Size() int {
	return xxx_messageInfo_ProductRequest.Size(m)
}
func (m *ProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductRequest proto.InternalMessageInfo

func (m *ProductRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ProductRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductRequest) GetName() AccountMode {
	if m != nil {
		return m.Name
	}
	return AccountMode_DEMO
}

type ProductResponse struct {
	Retcode              Retcode    `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Currencies           []*Product `protobuf:"bytes,2,rep,name=currencies,proto3" json:"currencies,omitempty"`
	Comment              string     `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Elapsed              string     `protobuf:"bytes,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProductResponse) Reset()         { *m = ProductResponse{} }
func (m *ProductResponse) String() string { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()    {}
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{2}
}
func (m *ProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductResponse.Unmarshal(m, b)
}
func (m *ProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductResponse.Marshal(b, m, deterministic)
}
func (dst *ProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductResponse.Merge(dst, src)
}
func (m *ProductResponse) XXX_Size() int {
	return xxx_messageInfo_ProductResponse.Size(m)
}
func (m *ProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductResponse proto.InternalMessageInfo

func (m *ProductResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *ProductResponse) GetCurrencies() []*Product {
	if m != nil {
		return m.Currencies
	}
	return nil
}

func (m *ProductResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ProductResponse) GetElapsed() string {
	if m != nil {
		return m.Elapsed
	}
	return ""
}

type ProductPostRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Product              *Product `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Action               Action   `protobuf:"varint,3,opt,name=action,proto3,enum=api.Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductPostRequest) Reset()         { *m = ProductPostRequest{} }
func (m *ProductPostRequest) String() string { return proto.CompactTextString(m) }
func (*ProductPostRequest) ProtoMessage()    {}
func (*ProductPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{3}
}
func (m *ProductPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductPostRequest.Unmarshal(m, b)
}
func (m *ProductPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductPostRequest.Marshal(b, m, deterministic)
}
func (dst *ProductPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductPostRequest.Merge(dst, src)
}
func (m *ProductPostRequest) XXX_Size() int {
	return xxx_messageInfo_ProductPostRequest.Size(m)
}
func (m *ProductPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductPostRequest proto.InternalMessageInfo

func (m *ProductPostRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ProductPostRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *ProductPostRequest) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_INSERT
}

type ProductPostResponse struct {
	Retcode              Retcode  `protobuf:"varint,1,opt,name=retcode,proto3,enum=api.Retcode" json:"retcode,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Elapsed              string   `protobuf:"bytes,3,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductPostResponse) Reset()         { *m = ProductPostResponse{} }
func (m *ProductPostResponse) String() string { return proto.CompactTextString(m) }
func (*ProductPostResponse) ProtoMessage()    {}
func (*ProductPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{4}
}
func (m *ProductPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductPostResponse.Unmarshal(m, b)
}
func (m *ProductPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductPostResponse.Marshal(b, m, deterministic)
}
func (dst *ProductPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductPostResponse.Merge(dst, src)
}
func (m *ProductPostResponse) XXX_Size() int {
	return xxx_messageInfo_ProductPostResponse.Size(m)
}
func (m *ProductPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductPostResponse proto.InternalMessageInfo

func (m *ProductPostResponse) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_REJECTX
}

func (m *ProductPostResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ProductPostResponse) GetElapsed() string {
	if m != nil {
		return m.Elapsed
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "api.Product")
	proto.RegisterType((*ProductRequest)(nil), "api.ProductRequest")
	proto.RegisterType((*ProductResponse)(nil), "api.ProductResponse")
	proto.RegisterType((*ProductPostRequest)(nil), "api.ProductPostRequest")
	proto.RegisterType((*ProductPostResponse)(nil), "api.ProductPostResponse")
}

func init() { proto.RegisterFile("products.proto", fileDescriptor_8c6e54f42122eb82) }

var fileDescriptor_8c6e54f42122eb82 = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xd1, 0x4e, 0xdb, 0x4c,
	0x10, 0x85, 0xe5, 0x24, 0xe0, 0x78, 0x20, 0x86, 0x7f, 0x01, 0xfd, 0xdb, 0x56, 0xad, 0xa2, 0xd0,
	0xd2, 0x5c, 0x54, 0xb9, 0x00, 0xa9, 0xf7, 0x15, 0x52, 0x25, 0x2e, 0xaa, 0x22, 0xf3, 0x00, 0xd6,
	0xc6, 0x3b, 0x54, 0xab, 0xc4, 0xbb, 0x66, 0x77, 0x9d, 0x16, 0x5e, 0xa5, 0x4f, 0xd3, 0x37, 0xab,
	0x3c, 0x6b, 0x9b, 0x80, 0x54, 0x55, 0xbd, 0x63, 0xce, 0x77, 0x3c, 0xcb, 0x1c, 0x1d, 0x05, 0xd2,
	0xca, 0x1a, 0x59, 0x17, 0xde, 0x2d, 0x2a, 0x6b, 0xbc, 0x61, 0x43, 0x51, 0xa9, 0x97, 0x80, 0xba,
	0x2e, 0x83, 0x30, 0xfb, 0x35, 0x82, 0xf8, 0x3a, 0x78, 0xd8, 0x6b, 0x80, 0xd6, 0x9e, 0x2b, 0xc9,
	0xa3, 0x69, 0x34, 0xdf, 0xc9, 0x92, 0x56, 0xb9, 0x92, 0xec, 0x05, 0x8c, 0x37, 0xa8, 0x6b, 0x6c,
	0xe0, 0x80, 0x60, 0x4c, 0xf3, 0x95, 0x64, 0x0c, 0x46, 0x2b, 0xa5, 0x25, 0x1f, 0x4e, 0xa3, 0x79,
	0x92, 0xd1, 0xdf, 0xec, 0x14, 0x26, 0x4b, 0xe1, 0x30, 0x2f, 0x6a, 0x6b, 0x51, 0x17, 0xf7, 0x7c,
	0x44, 0xdf, 0xec, 0x37, 0xe2, 0x65, 0xab, 0xb1, 0x77, 0x90, 0xde, 0xd5, 0xc6, 0x6f, 0xb9, 0x76,
	0xc8, 0x35, 0x21, 0xb5, 0xb7, 0x5d, 0xc0, 0x89, 0xd2, 0x52, 0x6d, 0x94, 0xac, 0xc5, 0x3a, 0x2f,
	0x8c, 0xd6, 0x58, 0x78, 0x65, 0x34, 0xdf, 0x9d, 0x46, 0xf3, 0x71, 0x76, 0xfc, 0x08, 0x2f, 0x7b,
	0xd6, 0xec, 0x76, 0xde, 0xa2, 0x28, 0x95, 0xfe, 0x96, 0x3b, 0xb1, 0x41, 0x1e, 0x93, 0x7b, 0xd2,
	0xab, 0x37, 0x62, 0x83, 0xec, 0x23, 0xfc, 0x1f, 0xce, 0x72, 0xf7, 0xe5, 0xd2, 0xac, 0x73, 0x25,
	0x51, 0x7b, 0x75, 0xab, 0xd0, 0xf2, 0x31, 0x9d, 0x73, 0x42, 0xf8, 0x86, 0xe8, 0x55, 0x0f, 0xd9,
	0x02, 0x8e, 0x4a, 0xa5, 0x55, 0x59, 0x97, 0xb9, 0xb1, 0x12, 0xad, 0xcb, 0x9d, 0x7a, 0x40, 0x9e,
	0x4c, 0xa3, 0x79, 0x94, 0xfd, 0xd7, 0xa2, 0xaf, 0x44, 0x6e, 0xd4, 0x03, 0xb2, 0x57, 0x90, 0x38,
	0x8f, 0x55, 0x70, 0x01, 0xb9, 0xc6, 0x8d, 0x40, 0xf0, 0x3d, 0x1c, 0x54, 0x56, 0x15, 0x98, 0x57,
	0x16, 0x0b, 0xe5, 0x9a, 0xd3, 0xf6, 0x28, 0x88, 0x94, 0xe4, 0xeb, 0x4e, 0x6d, 0xb6, 0x94, 0x62,
	0x85, 0x36, 0xbf, 0x45, 0xe4, 0xfb, 0x61, 0x0b, 0x09, 0x9f, 0x91, 0x9e, 0xf0, 0x3d, 0x9c, 0x04,
	0xe8, 0x3b, 0xc8, 0x21, 0x46, 0x2d, 0x96, 0x6b, 0x94, 0x3c, 0xa5, 0x1c, 0xba, 0x91, 0xbd, 0x01,
	0x70, 0xe8, 0xfd, 0x1a, 0x4b, 0xd4, 0x9e, 0x1f, 0xd0, 0xd1, 0x5b, 0x4a, 0xc3, 0xf1, 0x47, 0xa5,
	0xac, 0xa0, 0xc8, 0x0f, 0x03, 0x7f, 0x54, 0x66, 0x2b, 0x48, 0xdb, 0x0a, 0x65, 0x78, 0x57, 0xa3,
	0xf3, 0xec, 0x18, 0x76, 0xbc, 0x59, 0xa1, 0xa6, 0x12, 0x25, 0x59, 0x18, 0x9e, 0xf5, 0x6b, 0x40,
	0x68, 0xab, 0x5f, 0x6f, 0x61, 0xa4, 0x45, 0x89, 0x54, 0xa2, 0xf4, 0xfc, 0x70, 0x21, 0x2a, 0xb5,
	0xf8, 0x54, 0x14, 0xa6, 0xd6, 0xfe, 0x8b, 0x91, 0x98, 0x11, 0x9d, 0xfd, 0x8c, 0xe0, 0xa0, 0x7f,
	0xcd, 0x55, 0x46, 0x3b, 0x64, 0x67, 0x10, 0x5b, 0xf4, 0x85, 0x91, 0x48, 0x0f, 0xa6, 0xe7, 0xfb,
	0xf4, 0x71, 0x16, 0xb4, 0xac, 0x83, 0xec, 0x03, 0x40, 0xdb, 0x33, 0x85, 0x8e, 0x0f, 0xa6, 0xc3,
	0xf9, 0x5e, 0x6b, 0xed, 0x36, 0x6e, 0xf1, 0x26, 0xb0, 0xc2, 0x94, 0x94, 0x49, 0xe8, 0x75, 0x37,
	0x52, 0x94, 0x6b, 0x51, 0x39, 0x94, 0x54, 0xea, 0x24, 0xeb, 0xc6, 0xd9, 0x77, 0x60, 0xed, 0xaa,
	0x6b, 0xe3, 0xfe, 0x12, 0xc7, 0x19, 0xc4, 0xed, 0xf1, 0x94, 0xc5, 0xf3, 0x7f, 0xa5, 0x83, 0xec,
	0x14, 0x76, 0x45, 0x68, 0x7b, 0x48, 0x66, 0xaf, 0x4d, 0xa6, 0x91, 0xb2, 0x16, 0xcd, 0xee, 0xe0,
	0xe8, 0xc9, 0xc3, 0xff, 0x98, 0xcc, 0xd6, 0xad, 0x83, 0x3f, 0xde, 0x3a, 0x7c, 0x72, 0xeb, 0x72,
	0x97, 0x7e, 0x41, 0x2e, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xb7, 0x44, 0x7c, 0x64, 0x04,
	0x00, 0x00,
}
